from . import Loc as Data

# Weather and Time requirements seem like nonsense
# https://xenoblade.github.io/xbx/bdat/common_ms/ITM_CollectList_ms.html
# flake8: noqa
collepedia_data: list[Data] = [
Data("Ajira Melon - Prim", rules=["Blade License"]),
Data("Lacey Potato - Prim: Southwest", rules=["Blade License"]),
Data("Sadelana Lettuce - Prim: Southeast", rules=["Blade License"]),
Data("Mosa Cabbage - Prim: Northeast", rules=["Blade License"]),
Data("Keppo Carrot - Prim: Middle/Southwest", rules=["Blade License"]),
Data("Amidresian Tomato - Prim: Middle", rules=["Blade License"]),
Data("Caseras Mushroom - Noct: Mountain Trail", rules=["Blade License"], depends=["Divine Roost"]),
Data("Zandemo Eggplant - Noct: Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("Flowering Morrow Fern - Noct: Lake/Mountain Trail", rules=["Blade License"], depends=["Chapter 3"]),
Data("Fodornallow Greens - Noct: Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("Sibercaseras Mushroom - Noct: Cave/Ravine/South Forest", rules=["Blade License"], depends=["Chapter 3"]),
Data("Gubura Cabbage Leaf - Obli", rules=["Blade License"], depends=["Chapter 3"]),
Data("Shinuyuni Garlic - Obli: Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Cosse Bean - Obli: Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("Beagflea Squash - Obli: Cave/Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("Will Pepper - Obli: Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Charupa Leaves - Obli: Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("Dobobora Broccoli - Obli: Northern Coast/Floating Reef", rules=["Blade License"], depends=["Chapter 3"]),
Data("Ruge Daikon - Sylv: Western Sands", rules=["Blade License"], depends=["Chapter 3"]),
Data("Dosoram Bean - Sylv: Lake/Southeast Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Yaya Sesame - Sylv: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Pale Maize - Sylv: Upper Delusian Mountains", rules=["Blade License"], depends=["Chapter 3"]),
Data("Mizaria Celery - Sylv: Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("Kyatara Onion - Caul: Solitary Island", rules=["Blade License"], depends=["Chapter 3"]),
Data("Charged Cayenne - Caul: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Brambloo Shoot - Caul: Old Battleground/Solitary Island", rules=["Blade License"], depends=["Chapter 3"]),
Data("Belzadozebu Scallions - Caul: White Phosphorus", rules=["Blade License"], depends=["Chapter 3"]),
Data("Cranjelly - Prim", rules=["Blade License"]),
Data("Rock-Orange - Prim: Southeast", rules=["Blade License"]),
Data("Strawlenny - Prim: Southwest", rules=["Blade License"]),
Data("Starlight Apple - Prim: Southwest", rules=["Blade License"]),
Data("Mondcherry - Prim: Southeast", rules=["Blade License"]),
Data("Sonar Lemon - Prim: Northeast", rules=["Blade License"]),
Data("Socha Guava - Noct", rules=["Blade License"], depends=["Chapter 3"]),
Data("Prapaya - Noct: Mountain Trail", rules=["Blade License"], depends=["Divine Roost"]),
Data("Babaco Leaf - Noct: North Forest", rules=["Blade License"], depends=["Chapter 3"]),
Data("Amana Durian - Noct: North Forest", rules=["Blade License"], depends=["Chapter 3"]),
Data("Lava Mango - Noct: Cave/Ravine", rules=["Blade License"], depends=["Chapter 3"]),
Data("Sour Plum - Noct: Cave/Falls", rules=["Blade License"], depends=["Chapter 3"]),
Data("Bananaleaf - Noct: North Forest", rules=["Blade License"], depends=["Chapter 3"]),
Data("Godmelon - Noct: North Forest/Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Suna Watermelon - Obli: Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Royal Grape - Obli: Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Kiwegg - Obli: Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("Spiked Pomegranate - Obli: Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Shido Persimmon - Sylv: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Coldberry - Sylv: Southeast Coast/Western Sands", rules=["Blade License"], depends=["Chapter 3"]),
Data("White Cassis - Sylv: Northern Sands", rules=["Blade License"], depends=["Chapter 3"]),
Data("Emerald Grape - Sylv: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Cluster Papaya - Sylv: Southeast Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Gyulali - Caul: Solitary Island", rules=["Blade License"], depends=["Chapter 3"]),
Data("Lava Chestnut - Caul: Magma", rules=["Blade License"], depends=["Chapter 3"]),
Data("Iron Akebi Fruit - Caul: Kwarah Cloister", rules=["Blade License"], depends=["Chapter 3"]),
Data("Mottled Mums - Caul: Old Battleground/Solitary Island", rules=["Blade License"], depends=["Chapter 3"]),
Data("Nightmare Pineapple - Caul: Old Battleground/Solitary Island", rules=["Blade License"], depends=["Chapter 3"]),
Data("Zesian Fleawort - Prim", rules=["Blade License"]),
Data("Noranlily - Prim: North", rules=["Blade License"]),
Data("Sweet Nerine - Prim: Southwest", rules=["Blade License"]),
Data("Kiran Catnip - Prim: Northwest", rules=["Blade License"]),
Data("Doga Dandelion - Prim: Southeast", rules=["Blade License"]),
Data("Sona Herb - Prim: North Shore", rules=["Blade License"]),
Data("Garudo Pellionia Minima - Prim: Cave", rules=["Blade License"]),
Data("Nirvana Jonquil - Prim: Middle/North Shore/Southeast", rules=["Blade License"]),
Data("Timid Sunflower - Noct", rules=["Blade License"], depends=["Chapter 3"]),
Data("Lea Lily - Noct: Rocky Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Chameleon Creeping Plant - Noct: North Forest", rules=["Blade License"], depends=["Chapter 3"]),
Data("Muneria Flower - Noct: South Forest", rules=["Blade License"], depends=["Chapter 3"]),
Data("Sekka Cosmos - Noct: South Forest", rules=["Blade License"], depends=["Chapter 3"]),
Data("False Cedar - Noct: North Forest", rules=["Blade License"], depends=["Chapter 3"]),
Data("Sleeping Amaryllis - Noct: Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("Jobo Primrose - Obli: Southern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Gudo Rocambole - Obli: Cove", rules=["Blade License"], depends=["Chapter 3"]),
Data("Blast Chard - Obli: Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Mya Oats - Obli: Floating Reef", rules=["Blade License"], depends=["Chapter 3"]),
Data("Myuena Cactus - Obli: Northern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Kepha Holly - Obli: Southern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Bude Mugwort - Sylv", rules=["Blade License"], depends=["Chapter 3"]),
Data("Exploding Pansy - Sylv: Southern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Sese Lily - Sylv: Upper Delusian Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Antorus Rose - Sylv: Lake/Southern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Shia Cattleya - Sylv: Southern Coast/Western Sands", rules=["Blade License"], depends=["Chapter 3"]),
Data("Poron Tulip - Caul: Volcano/White Phosphorus", rules=["Blade License"], depends=["Chapter 3"]),
Data("Jaharmum - Caul: Magma/Solitary Island", rules=["Blade License"], depends=["Chapter 3"]),
Data("Bogano Weed - Caul: Volcano", rules=["Blade License"], depends=["Chapter 3"]),
Data("Muranadium - Caul: Magma/Volcano", rules=["Blade License"], depends=["Chapter 3"]),
Data("Rizattice - Prim", rules=["Blade License"]),
Data("Coaletri - Prim: Talon Rock", rules=["Blade License"]),
Data("Grinding Squirrel - Prim: North", rules=["Blade License"]),
Data("Crawling Bat - Prim: Northwest", rules=["Blade License"]),
Data("Golden Sardine - Prim: Southwest", rules=["Blade License"]),
Data("Zizi Rabbit - Prim: Northwest", rules=["Blade License"]),
Data("Ashizel - Prim: Southeast", rules=["Blade License"]),
Data("Rock Armadillo - Noct", rules=["Blade License"], depends=["Chapter 3"]),
Data("Morphling Flounder - Noct: Falls", rules=["Blade License"], depends=["Chapter 3"]),
Data("Gluttonutan - Noct: Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Iguari - Noct: North Forest", rules=["Blade License"], depends=["Chapter 3"]),
Data("Mirrored Peacock - Noct: Ravine", rules=["Blade License"], depends=["Chapter 3"]),
Data("Continental Jellyfish - Noct: Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Doragaroo - Obli", rules=["Blade License"], depends=["Chapter 3"]),
Data("Phantom Tanuki - Obli: Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Denemozumi Mouse - Obli: Southern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Octo-suka - Obli: Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Jet Turtle - Obli", rules=["Blade License"], depends=["Chapter 3"]),
Data("Sand Cucumber - Obli: Northern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Gormless Monkey - Obli: Crevasse", rules=["Blade License"], depends=["Chapter 3"]),
Data("Fleeting Baboon - Obli: Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Diresheep - Sylv: Cave/Upper Delusian Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Medusa Squid - Sylv: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Beaporge - Sylv: Great Sand Hill", rules=["Blade License"], depends=["Chapter 3"]),
Data("Penginion - Sylv: Cave/Upper Delusian Mountains", rules=["Blade License"], depends=["Chapter 3"]),
Data("Gun Snake - Caul: Old Battleground", rules=["Blade License"], depends=["Chapter 3"]),
Data("Demon Boar - Caul: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Dulcet Goose - Caul: Volcano", rules=["Blade License"], depends=["Chapter 3"]),
Data("Lava Fox - Caul: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Gibney Jackal - Caul: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Ball Mosquito - Prim", rules=["Blade License"]),
Data("Stretching Locust - Prim: Middle", rules=["Blade License"]),
Data("Tractor Beetle - Prim: Northeast", rules=["Blade License"]),
Data("Multi-speckled Ladybug - Prim: Cave/Middle", rules=["Blade License"]),
Data("Meteo Eater - Prim: Northeast", rules=["Blade License"]),
Data("Vagabond Ant - Prim: Middle", rules=["Blade License"]),
Data("Assassin Springtail - Prim: Northeast", rules=["Blade License"]),
Data("Noctilucent Dragonfly - Noct", rules=["Blade License"], depends=["Chapter 3"]),
Data("Strobing Horsefly - Noct: Rocky Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Tenacious Moth - Noct: Mountain Trail", rules=["Blade License"], depends=["Divine Roost"]),
Data("Madame Mantis - Noct: Ravine", rules=["Blade License"], depends=["Chapter 3"]),
Data("Madness Hornet - Noct", rules=["Blade License"], depends=["Chapter 3"]),
Data("Pardo Spider - Noct: Ravine", rules=["Blade License"], depends=["Chapter 3"]),
Data("Kusakiri Stag Beetle - Noct: South Forest", rules=["Blade License"], depends=["Chapter 3"]),
Data("Absop's Swallowtail - Noct: South Forest/Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Fullbelly Gecko - Obli", rules=["Blade License"], depends=["Chapter 3"]),
Data("Moleworm - Obli: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Imposter Bug - Obli: Northern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Shadow Fly - Obli: Northern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Common Stick Insect - Obli: Northern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Whip Scorpion - Obli: Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Slasher Beetle - Obli: Southern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("White Sand Beetle - Sylv", rules=["Blade License"], depends=["Chapter 3"]),
Data("Baibai Beetle - Sylv: Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("Glassy Cricket - Sylv: Delusain Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Rainy Cricket - Sylv: Upper Delusian Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Crystal Butterfly - Sylv: Southern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Snowy Angelhair - Sylv: Lake/Southern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Shooting Firefly - Caul: Solitary Island", rules=["Blade License"], depends=["Chapter 3"]),
Data("Abyssal Cricket - Caul: Old Battleground", rules=["Blade License"], depends=["Chapter 3"]),
Data("Cetecegem Beetle - Caul: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Bullet Fly - Caul: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Prickly Cricket - Caul: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Logunie's Driftwood - Prim: North", rules=["Blade License"]),
Data("White Iron Sand - Prim: Northeast", rules=["Blade License"]),
Data("Fillal Filth - Prim: North/Talon Rock", rules=["Blade License"]),
Data("Sanelac Pearl - Prim: Cave/Talon Rock", rules=["Blade License"]),
Data("Arnacian Orewood - Prim: Southwest", rules=["Blade License"]),
Data("Auroran Bone - Prim: Cave/North", rules=["Blade License"]),
Data("Katoan Leaf - Noct", rules=["Blade License"], depends=["Chapter 3"]),
Data("Gluttonutan Clay - Noct: North Forest", rules=["Blade License"], depends=["Chapter 3"]),
Data("Cane Soil - Noct: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Noka Mirrorstone - Noct: Cave/Mountain Trail", rules=["Blade License"], depends=["Chapter 3"]),
Data("Galjim Crystal - Noct: Rocky Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Harnenga Cotton - Noct: Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Eternal Moss - Noct: Falls", rules=["Blade License"], depends=["Chapter 3"]),
Data("Wainess Fossil - Obli: Cave/Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Zedis Twig - Obli: Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("Exubera Stalactite - Obli: Cove/Floating Reef", rules=["Blade License"], depends=["Chapter 3"]),
Data("Silvery Cactaceous Resin - Obli: Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Kridokan Air - Obli: Cave/Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Dring Slick - Sylv", rules=["Blade License"], depends=["Chapter 3"]),
Data("Acton Rock Shards - Sylv: Great Sand Hill", rules=["Blade License"], depends=["Chapter 3"]),
Data("Fullerene Coral - Sylv: Delusian Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Taoman Acid - Sylv: Southern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Grandan Rock - Sylv: Western Sands", rules=["Blade License"], depends=["Chapter 3"]),
Data("Jagitos Copper - Sylv: Southeast Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Pomio Spore - Sylv: Northern Sands/Southern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Cooling Lava - Caul: Magma", rules=["Blade License"], depends=["Chapter 3"]),
Data("Zalon Dirt - Caul: Volcano", rules=["Blade License"], depends=["Chapter 3"]),
Data("Rogebra Shockstone - Caul: Castle/Volcano", rules=["Blade License"], depends=["Chapter 3"]),
Data("Autiga Powder - Caul: White Phosporus", rules=["Blade License"], depends=["Chapter 3"]),
Data("Zagyrin Cragstone - Caul: Magma/Volcano", rules=["Blade License"], depends=["Chapter 3"]),
Data("Cliord Oil - Caul: Magma", rules=["Blade License"], depends=["Chapter 3"]),
Data("Deflection Shield Mirror - Prim", rules=["Blade License"]),
Data("Anhydrous Radiator - Prim: Northwest", rules=["Blade License"]),
Data("Heatproof Inox Pipe - Prim: Southeast", rules=["Blade License"]),
Data("L-002 Fuel Tank - Prim", rules=["Blade License"]),
Data("L-002 Space Analyzer - Prim", rules=["Blade License"]),
Data("US-X Space Suit - Prim: North Shore", rules=["Blade License"]),
Data("Centrifugal Beam Generator - Prim: Middle", rules=["Blade License"]),
Data("Earthfreezer - Noct", rules=["Blade License"], depends=["Chapter 3"]),
Data("Nostalgia L-002 - Noct: Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("HI9 Ion Thruster - Noct: Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Mk IX Hypercooler - Noct: Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("Gesture Glove - Noct: Falls", rules=["Blade License"], depends=["Chapter 3"]),
Data("3D Printer - Noct: Mountain Trail/Ravine", rules=["Blade License"], depends=["Chapter 3"]),
Data("Cruise Deflector AiR - Obli: Crevasse", rules=["Blade License"], depends=["Chapter 3"]),
Data("Multi-mirror Solar Drone - Obli: Crevasse", rules=["Blade License"], depends=["Chapter 3"]),
Data("5th Gen Recycler - Obli: Crevasse", rules=["Blade License"], depends=["Chapter 3"]),
Data("L-002 Degeneration Reactor - Obli: Cove/Crevasse", rules=["Blade License"], depends=["Chapter 3"]),
Data("Cordless Transformer - Sylv: Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("Hard Skin - Sylv: Delusian Mountain/Northern Sands", rules=["Blade License"], depends=["Chapter 3"]),
Data("Decoy DNA - Sylv: Great Sand Hill/Lake", rules=["Blade License"], depends=["Chapter 3"]),
Data("L-002 Dagoo Heat Ray - Sylv: Delusian Mountain/Northern Sands", rules=["Blade License"], depends=["Chapter 3"]),
Data("A-HAB autonomous AI - Sylv: Delusian Mountain/Great Sand Hill/Northern Sands", rules=["Blade License"], depends=["Chapter 3"]),
Data("Solar Wind Converter - Caul: Distant", rules=["Blade License"], depends=["Chapter 3"]),
Data("Oxygen Airbrake - Caul: Castle", rules=["Blade License"], depends=["Chapter 3"]),
Data("Exalting Paint - Caul: Castle", rules=["Blade License"], depends=["Chapter 3"]),
Data("Autoposturizer - Caul: Distant", rules=["Blade License"], depends=["Chapter 3"]),
Data("Planter - Caul: Distant/White Phosphorus", rules=["Blade License"], depends=["Chapter 3"]),
Data("FN Prototype 3 - Caul: Castle", rules=["Blade License"], depends=["Chapter 3"]),
Data("Octopus Regulator - Caul: White Phosphorus", rules=["Blade License"], depends=["Chapter 3"]),
Data("Jagged Mortar - Prim: North Shore", rules=["Blade License"]),
Data("Acorn Abacus - Prim: North/North Shore", rules=["Blade License"]),
Data("Facewood - Prim: North", rules=["Blade License"]),
Data("Hemp Wallet - Prim: Northwest", rules=["Blade License"]),
Data("Hummingstone - Prim: Northeast/Southwest", rules=["Blade License"]),
Data("Loathsome Blob - Noct: Falls", rules=["Blade License"], depends=["Chapter 3"]),
Data("Sea Anemone Platter - Noct: Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Logunie's Driftwood Boat - Noct: Falls", rules=["Blade License"], depends=["Chapter 3"]),
Data("Shiny Lamp - Noct: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Spine-O-Corrector - Obli", rules=["Blade License"], depends=["Chapter 3"]),
Data("Thornbox - Obli: Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Perished Stone Spear - Obli: Floating Reef", rules=["Blade License"], depends=["Chapter 3"]),
Data("Sandstone Etching - Obli: Cave/Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Magical Finding Rod - Obli: Crevasse", rules=["Blade License"], depends=["Chapter 3"]),
Data("Ouroboros Bracelet - Obli: Cove", rules=["Blade License"], depends=["Chapter 3"]),
Data("Drum of Valor - Obli: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Nopolith - Obli: Lake/Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Yabuyabu Ointment - Sylv", rules=["Blade License"], depends=["Chapter 3"]),
Data("Straw Buoy - Sylv: Western Sands", rules=["Blade License"], depends=["Chapter 3"]),
Data("Spore Balloon - Sylv: Southeast Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Stargazer - Sylv: Upper Delusian Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Camocloak - Sylv: Northern Sands", rules=["Blade License"], depends=["Chapter 3"]),
Data("Spirit Wand - Sylv: Western Sands", rules=["Blade License"], depends=["Chapter 3"]),
Data("Chrampoline - Caul: Old Battleground", rules=["Blade License"], depends=["Chapter 3"]),
Data("Sharpening Stone - Caul: White Phosphorus", rules=["Blade License"], depends=["Chapter 3"]),
Data("Charred Crock - Caul: Magma", rules=["Blade License"], depends=["Chapter 3"]),
Data("Stone Lens - Caul: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Dark Lantern - Caul: Solitary Island", rules=["Blade License"], depends=["Chapter 3"]),
Data("Icarus Wings - Caul: Kwarah Cloister", rules=["Blade License"], depends=["Chapter 3"]),
Data("Bogano Sleeping Bag - Caul: Old Battleground", rules=["Blade License"], depends=["Chapter 3"]),
Data("Extra-large Cash Box - Caul: Kwarah Cloister", rules=["Blade License"], depends=["Chapter 3"]),
Data("High Accelerator - Prim: Talon Rock", rules=["Blade License"]),
Data("Crush Ring - Prim: North", rules=["Blade License"]),
Data("T-ray Light - Prim: Southeast", rules=["Blade License"]),
Data("Flecked Bottle - Prim: Talon Rock", rules=["Blade License"]),
Data("Grosium Core - Prim: Northwest", rules=["Blade License"]),
Data("Brain Terminal - Noct: Ravine", rules=["Blade License"], depends=["Chapter 3"]),
Data("Hexagauge - Noct: Rocky Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Joadtank - Noct: Mountain Trail", rules=["Blade License"], depends=["Divine Roost"]),
Data("Resonating Madonater - Noct: Lake/Rocky Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Ultra Filter - Obli", rules=["Blade License"], depends=["Chapter 3"]),
Data("Eradicator Eyepiece - Obli: Cove", rules=["Blade License"], depends=["Chapter 3"]),
Data("Sacrificial Reactor - Obli: Crevasse", rules=["Blade License"], depends=["Chapter 3"]),
Data("Steel Tail Sheath - Obli: Cove", rules=["Blade License"], depends=["Chapter 3"]),
Data("Horned Helmet - Obli: Southern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Warbone - Obli: Cove", rules=["Blade License"], depends=["Chapter 3"]),
Data("Shimmering Skin - Sylv", rules=["Blade License"], depends=["Chapter 3"]),
Data("Detilid Device - Sylv: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Missile Wiring - Sylv: Great Sand Hill", rules=["Blade License"], depends=["Chapter 3"]),
Data("Berzerker Unit - Sylv: Great Sand Hill", rules=["Blade License"], depends=["Chapter 3"]),
Data("Thunderbolt Emblem - Sylv: Delusian Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Trying Crown - Sylv: Southeast Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Intelligent Liquid Metal - Sylv: Western Sands", rules=["Blade License"], depends=["Chapter 3"]),
Data("Pan-analysis Chips - Caul: White Phosphorus", rules=["Blade License"], depends=["Chapter 3"]),
Data("Savage Claw - Caul: Distant", rules=["Blade License"], depends=["Chapter 3"]),
Data("Elemental Battery - Caul: Kwarah Cloister", rules=["Blade License"], depends=["Chapter 3"]),
Data("Spatial Control Jointer - Caul: Castle/Distant", rules=["Blade License"], depends=["Chapter 3"]),
Data("Dithblade Fragment - Caul: Distant", rules=["Blade License"], depends=["Chapter 3"]),
Data("Voltant Scanner - Caul: Distant", rules=["Blade License"], depends=["Chapter 3"]),
Data("Meditation Powder - Prim: Talon Rock", rules=["Blade License"]),
Data("California Sunset - Prim: Cave", rules=["Blade License"]),
Data("Mirage Scope - Prim: Cave", rules=["Blade License"]),
Data("Ancient Allure - Prim: Northwest", rules=["Blade License"]),
Data("Goddess's Kiss - Prim: North Shore", rules=["Blade License"]),
Data("Gleaming Magnet - Noct: Rocky Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Fraudulent Mirror - Noct: Caves/Rocky Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Scales of Justice - Noct: South Forest", rules=["Blade License"], depends=["Chapter 3"]),
Data("Spherical EM Motor - Noct: Rocky Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Primitive Colossus Statue - Noct: Falls/Mountain Trail", rules=["Blade License"], depends=["Chapter 3"]),
Data("Strong Iron - Obli", rules=["Blade License"], depends=["Chapter 3"]),
Data("Chameleon Sand - Obli: Floating Reef/Stream", rules=["Blade License"], depends=["Chapter 3"]),
Data("Maiden's Guardian Star - Obli: Cave", rules=["Blade License"], depends=["Chapter 3"]),
Data("Echo Rock - Obli: Cave/Southern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Illogical Etchings - Obli: Floating Reef/Southern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Angel Stone - Obli: Northern Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Lost Memory Synthesizer - Obli: Floating Reef", rules=["Blade License"], depends=["Chapter 3"]),
Data("Double Helical Salt - Sylv", rules=["Blade License"], depends=["Chapter 3"]),
Data("Brilliant Green Liquid - Sylv: Great Sand Hill", rules=["Blade License"], depends=["Chapter 3"]),
Data("Flowering Egg - Sylv: Northern Sands", rules=["Blade License"], depends=["Chapter 3"]),
Data("Queen's Rapture - Sylv", rules=["Blade License"], depends=["Chapter 3"]),
Data("Stone Screw - Sylv", rules=["Blade License"], depends=["Chapter 3"]),
Data("Starmaker - Sylv: Southeast Coast", rules=["Blade License"], depends=["Chapter 3"]),
Data("Hello Transmitter - Sylv: Delusian Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Affinity Soulchain - Sylv: Upper Delusian Mountain", rules=["Blade License"], depends=["Chapter 3"]),
Data("Mega Muscle Builder - Caul: Kwarah Cloister", rules=["Blade License"], depends=["Chapter 3"]),
Data("Rod of Brutality +10 - Caul: Volcano", rules=["Blade License"], depends=["Chapter 3"]),
Data("Capricious Kettle - Caul: Magma", rules=["Blade License"], depends=["Chapter 3"]),
Data("Megajolt Rattle - Caul: Kwarah Cloister", rules=["Blade License"], depends=["Chapter 3"]),
Data("Superior Scepter - Caul: Kwarah Cloister", rules=["Blade License"], depends=["Chapter 3"]),
Data("Doom Mask - Caul: Castle", rules=["Blade License"], depends=["Chapter 3"]),
Data("Savage Sketch - Caul: Kwarah Cloister", rules=["Blade License"], depends=["Chapter 3"]),
Data("Book of Death and Rebirth - Caul: Castle/Distant", rules=["Blade License"], depends=["Chapter 3"]),
]
