from . import Loc as Data

# from helper folder
# flake8: noqa
fn_nodes_data: list[Data] = [
Data("FN Node 101 - Prim", rules=["FNet", "Mechanical 5"]),
Data("FN Node 102 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 103 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 104 - Prim", rules=["FNet", "Mechanical 3"]),
Data("FN Node 106 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 108 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 107 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 109 - Prim", rules=["FNet", "Mechanical 2"], depends=["FN Site 109"]), # Skell with transform 
Data("FN Node 110 - Prim", rules=["FNet", "Mechanical 1"], depends=["Talon Rock Summit", "Chapter 3"]),  # TAJ with Skell
Data("FN Node 111 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 112 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 113 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 114 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 115 - Prim", rules=["FNet", "Mechanical 2"]),
Data("FN Node 116 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 117 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 118 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 119 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 120 - Prim", rules=["FNet", "Mechanical 3"]),
Data("FN Node 121 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 105 - Prim", rules=["FNet", "Mechanical 1"]),
Data("FN Node 201 - Noct", rules=["FNet", "Mechanical 3"], depends=["Divine Roost"]),  # TAJ with Skell
Data("FN Node 202 - Noct", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 203 - Noct", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 204 - Noct", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 205 - Noct", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 206 - Noct", rules=["FNet", "Mechanical 5"], depends=["Divine Roost"]),  # TAJ with Skell
Data("FN Node 207 - Noct", rules=["FNet", "Mechanical 2"], depends=["Divine Roost"]),  # TAJ with Skell
Data("FN Node 208 - Noct", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 209 - Noct", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 210 - Noct", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 211 - Noct", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 212 - Noct", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 213 - Noct", rules=["FNet", "Mechanical 4"], depends=["Divine Roost"]),  # TAJ with Skell
Data("FN Node 214 - Noct", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 215 - Noct", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 216 - Noct", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 217 - Noct", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 218 - Noct", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 219 - Noct", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 220 - Noct", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 221 - Noct", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 222 - Noct", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 223 - Noct", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 224 - Noct", rules=["FNet", "Mechanical 4"], depends=["Chapter 3"]),
Data("FN Node 225 - Noct", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 206", valid=False),
Data("FN Node 207", valid=False),
Data("FN Node 301 - Obli", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 302 - Obli", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 303 - Obli", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 304 - Obli", rules=["FNet", "Mechanical 5"], depends=["Chapter 3"]),
Data("FN Node 305 - Obli", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 306 - Obli", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 307 - Obli", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 308 - Obli", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 309 - Obli", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 310 - Obli", rules=["FNet", "Mechanical 2"], depends=["FN Site 310"]),  # Needs advanced jumping
Data("FN Node 311 - Obli", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 312 - Obli", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 313 - Obli", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 314 - Obli", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 315 - Obli", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 316 - Obli", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 317 - Obli", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 318 - Obli", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 320 - Obli", rules=["FNet", "Mechanical 3"], depends=["Floating Reef"]),  # Technically doable with only Skell but very hard
Data("FN Node 321 - Obli", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 319 - Obli", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 322 - Obli", rules=["FNet", "Mechanical 4"], depends=["Chapter 3"]),
Data("FN Node 313", valid=False),
Data("FN Node 314", valid=False),
Data("FN Node 315", valid=False),
Data("FN Node 401 - Sylv", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 402 - Sylv", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 403 - Sylv", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 404 - Sylv", rules=["FNet", "Mechanical 5"], depends=["Chapter 3"]),
Data("FN Node 405 - Sylv", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 406 - Sylv", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 407 - Sylv", rules=["FNet", "Mechanical 4"], depends=["Chapter 3"]),
Data("FN Node 408 - Sylv", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 409 - Sylv", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 410 - Sylv", rules=["FNet", "Mechanical 4"], depends=["Chapter 3"]),
Data("FN Node 411 - Sylv", rules=["FNet", "Mechanical 4"], depends=["Chapter 3"]),
Data("FN Node 412 - Sylv", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 413 - Sylv", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 414 - Sylv", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 415 - Sylv", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 416 - Sylv", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 417 - Sylv", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 418 - Sylv", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 419 - Sylv", rules=["FNet", "Mechanical 5"], depends=["Chapter 3"]),
Data("FN Node 420 - Sylv", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 501 - Caul", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 502 - Caul", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
Data("FN Node 503 - Caul", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 504 - Caul", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 505 - Caul", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 506 - Caul", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 507 - Caul", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 508 - Caul", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 509 - Caul", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 510 - Caul", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 511 - Caul", rules=["FNet", "Mechanical 2"], depends=["Chapter 3"]),
Data("FN Node 512 - Caul", rules=["FNet", "Mechanical 4"], depends=["Chapter 3"]),
Data("FN Node 513 - Caul", rules=["FNet", "Mechanical 4"], depends=["Chapter 3"]),
Data("FN Node 514 - Caul", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 515 - Caul", rules=["FNet", "Mechanical 3"], depends=["Chapter 3"]),
Data("FN Node 516 - Caul", rules=["FNet", "Mechanical 1"], depends=["Chapter 3"]),
]
# https://xenoblade.github.io/xbx/bdat/common_local_us/FnetVeinList.html match name in
# https://xenoblade.github.io/xbx/bdat/common_local_us/FLD_Location.html