from . import Loc as Data

#https://xenoblade.github.io/xbx/bdat/common_local_us/FLD_Location.html
# flake8: noqa
locations_data: list[Data] = [
Data("Barracks Interior - BLADE Barracks"),
Data("Interior - Lifehold Core - Chp 12", depends=["Chapter 12"]),
Data("West Gate - Indu Dist"),
Data("Central Industrial District"),
Data("Integrated Production Plant - Indu Dist"),
Data("Outfitters Test Hangar - Indu Dist"),
Data("Repenta Diner - Indu Dist"),
Data("Professor Bs Lab - Indu Dist", depends=["Mystery Man"]),
Data("West Melville Street - Comm Dist"),
Data("Central Melville Street - Comm Dist"),
Data("East Melville Street - Comm Dist"),
Data("Barista Court - Comm Dist"),
Data("North Founders Street - Comm Dist"),
Data("Nopon Bazaar - Comm Dist", depends=["BFFs"]),
Data("Deck - Ma-non Ship - Chp 5", depends=["Chapter 5"]),
Data("Starboard - Ma-non Ship - Chp 5", depends=["Chapter 5"]),
Data("Port Side - Ma-non Ship - Chp 5", depends=["Chapter 5", "Prone Sweet Prone"]),
Data("Water Purification Plant - Resi Dist"),
Data("Deliverance Park - Resi Dist"),
Data("Cathedral - Resi Dist"),
Data("Sports Complex - Resi Dist"),
Data("Ishmael Hills - Resi Dist"),
Data("Division Drive - Admi Dist"),
Data("Armory Alley - Admi Dist"),
Data("Yardleys Hideaway - Admi Dist", depends=["House of Cards"]),
Data("East Gate - Admi Dist"),
Data("BLADE Tower - Admi Dist"),
Data("BLADE Concourse - Admi Dist"),
Data("BLADE Barracks"),
Data("Mimeosome Maintenance Center - Admi Dist"),
Data("Hangar - Admi Dist"),
Data("Restricted Hangar Entrance - Admi Dist"),
Data("Bedrock Hold - Prim"),
Data("Stonelattice Cavern - Prim", rules=["Skell License"]),  # maybe possible without if you MenuReset
Data("Greater Gemini Bridge - Prim"),
Data("Castaway Cavern - Prim"),
Data("Stickstone Rise - Prim"),
Data("Lesser Gemini Bridge - Prim"),
Data("Plundered Ruin - Prim"),
Data("Unicorn Rock - Prim"),
Data("Turtle Nest - Prim"),
Data("Molten Hollow - Prim"),
Data("Bedrock Hold Approach - Prim"),
Data("Biahno River - Prim"),
Data("Green Threshold - Prim"),
Data("Headwater Cavern - Prim"),
Data("Headwater Summit - Prim"),
Data("Headwater Cliff - Prim"),
Data("Biahno Water-Purification Plant - Prim", depends=["Water Woes"]),
Data("Biahno Lake - Prim"),
Data("Fallshorn Isle - Prim"),
Data("Grieving Plains - Prim"),
Data("Biahno Grassland - Prim"),
Data("Drop Shaft - Prim", depends=["Talon Rock Summit"]),
Data("Silent Mire - Prim"),
Data("Seaswept Base - Prim"),
Data("Wonderment Bluff - Prim"),
Data("Sickle Rock Rise - Prim"),
Data("Roof Rock - Prim"),
Data("Janpath Lake - Prim"),
Data("La Mancha - Prim"),
Data("North Janpath Plain - Prim"),
Data("Arendt Bridge - Prim"),
Data("Tallpach Peak - Prim"),
Data("Beasts Lair - Prim"),
Data("Northpointe Cove - Prim"),
Data("Northpointe Beach - Prim"),
Data("East Janpath Plain - Prim"),
Data("South Janpath Plain - Prim"),
Data("West Janpath Plain - Prim"),
Data("Cliffside Beach - Prim"),
Data("East Gate Plain - Prim"),
Data("West Gate Plain - Prim"),
Data("Talon Rock Prominence - Prim", depends=["Talon Rock Summit"]),
Data("Talon Rock Third Terrane - Prim"),
Data("Talon Rock Second Terrane - Prim"),
Data("Sayram Northeast Plain - Prim"),
Data("Shadow Rise - Prim"),
Data("Biahno Hills - Prim"),
Data("Starfall Basin - Prim"),
Data("Rock Cavern - Prim"),
Data("Seaswept Rise - Prim"),
Data("Sayram Lake - Prim"),
Data("Talon Rock Summit - Prim", rules=["Skell License"]),  # TAJ
Data("FN Site 101 - Prim", rules=["FNet"]),
Data("FN Site 102 - Prim", rules=["FNet"]),
Data("FN Site 103 - Prim", rules=["FNet"]),
Data("FN Site 104 - Prim", rules=["FNet"]),
Data("FN Site 106 - Prim", rules=["FNet"]),
Data("Seaswept Ridge - Prim"),
Data("FN Site 108 - Prim", rules=["FNet"]),
Data("FN Site 107 - Prim", rules=["FNet"]),
Data("FN Site 109 - Prim", rules=["FNet", "Skell License"]),
Data("FN Site 110 - Prim", rules=["FNet"], depends=["Talon Rock Summit"]),
Data("FN Site 111 - Prim", rules=["FNet"]),
Data("FN Site 112 - Prim", rules=["FNet"]),
Data("FN Site 113 - Prim", rules=["FNet"]),
Data("FN Site 114 - Prim", rules=["FNet"]),
Data("FN Site 115 - Prim", rules=["FNet"]),
Data("FN Site 116 - Prim", rules=["FNet"]),
Data("FN Site 117 - Prim", rules=["FNet"]),
Data("FN Site 118 - Prim", rules=["FNet"]),
Data("FN Site 119 - Prim", rules=["FNet"]),
Data("FN Site 120 - Prim", rules=["FNet"]),
Data("FN Site 121 - Prim", rules=["FNet"]),
Data("FN Site 105 - Prim", rules=["FNet"]),
Data("Rustpool Banks - Noct", depends=["Chapter 3"]),
Data("Potters Rock - Noct", depends=["Chapter 3"]),
Data("Whales Gullet - Noct", depends=["Chapter 3"]),
Data("Rust Lake - Noct", depends=["Chapter 3"]),
Data("Waterway Tangle - Noct", depends=["Chapter 3"]),
Data("Ensanguined Font - Noct", depends=["Chapter 3"]),
Data("Lakeview Stronghold - Noct", depends=["Chapter 3"]),
Data("Jasper Incline - Noct", depends=["Chapter 3"]),
Data("Old Dragontail Tree - Noct", depends=["Chapter 3"]),
Data("Redsnake Pass - Noct", depends=["Chapter 3"]),
Data("Whales Nostril - Noct", depends=["Chapter 3"]),
Data("Yagamis Vista - Noct", depends=["Chapter 3"]),
Data("Sapphire Carpet - Noct", depends=["Chapter 3"]),
Data("Sapphire Table - Noct", depends=["Chapter 3"]),
Data("Garden Spring - Noct", depends=["Chapter 3"]),
Data("Tripod Rock - Noct", depends=["Chapter 3"]),
Data("Humdrum Peaks - Noct", depends=["Chapter 3"]),
Data("Goblins Narrow - Noct", depends=["Chapter 3"]),
Data("Sunlit Spring - Noct", depends=["Chapter 3"]),
Data("Orochis Belly - Noct", depends=["Chapter 3"]),
Data("Elephants Trunk - Noct", depends=["Chapter 3"]),
Data("Seabound Coil Tree - Noct", depends=["Chapter 3"]),
Data("Nopon Highroad - Noct", depends=["Chapter 3"]),
Data("Coil Tree Cape - Noct", depends=["Chapter 3"]),
Data("Decapotamon Vista - Noct", depends=["Chapter 3"]),
Data("Decapotamon - Noct", depends=["Chapter 3"]),
Data("Cascade Isle - Noct", depends=["Chapter 3"]),
Data("Serpentine Pass - Noct", depends=["Chapter 3"]),
Data("Vitriol Cesspool - Noct", depends=["Chapter 3"]),
Data("Qing Long Glade - Noct", depends=["Chapter 3"]),
Data("Rockmoles Burrow - Noct", depends=["Chapter 3"]),
Data("Fukai Pass - Noct", depends=["Chapter 3"]),
Data("Everwhelm Falls - Noct", depends=["Chapter 3"]),
Data("Sato Headwater - Noct", depends=["Chapter 3"]),
Data("Weeping Whitewood - Noct", depends=["Chapter 3"]),
Data("Ensconced Citadel - Noct", depends=["Chapter 3"]),
Data("Suncatch Ravine - Noct", depends=["Chapter 3"]),
Data("Middle Hushflood - Noct", depends=["Chapter 3"]),
Data("Great Trident Crossing - Noct", depends=["Chapter 3"]),
Data("Bloodpond Basin - Noct", depends=["Chapter 3"]),
Data("Millstone Ridge - Noct", depends=["Chapter 3"]),
Data("Dead Mans Gulch - Noct", depends=["Chapter 3"]),
Data("Sharks Jaws - Noct", depends=["Chapter 3"]),
Data("Dead Mans Ingress - Noct", depends=["Chapter 3"]),
Data("Upper Hushflood - Noct", depends=["Chapter 3"]),
Data("Divine Roost - Noct", rules=["Skell License"], depends=["Chapter 3"]),  # TAJ
Data("Whales Weeper - Noct", depends=["Chapter 3"]),
Data("Nopon Braidbridge - Noct", depends=["Chapter 3"]),
Data("Skybound Coil Tree - Noct", depends=["Chapter 3"]),
Data("Great Nail - Noct", depends=["Chapter 3"]),
Data("Bident Crossing - Noct", depends=["Chapter 3"]),
Data("Blackback Bridge - Noct", depends=["Chapter 3"]),
Data("Narcissus Tree - Noct", depends=["Chapter 3"]),
Data("Celestial Ascent - Noct", depends=["Chapter 3"]),
Data("Celestial Cleave - Noct", depends=["Divine Roost"]),
Data("Sentinels Nest - Noct", depends=["Divine Roost"]),
Data("Canopied Nightwood - Noct", depends=["Chapter 3"]),
Data("Lotus Keep Building Site - Noct", depends=["Chapter 3"]),
Data("Twin Hammers - Noct", depends=["Chapter 3"]),
Data("Breakwater Narrow - Noct", depends=["Chapter 3"]),
Data("Skygazers Atrium - Noct", depends=["Chapter 3"]),
Data("Idyll Beach - Noct", depends=["Chapter 3"]),
Data("FN Site 201 - Noct", rules=["FNet"], depends=["Divine Roost"]),
Data("FN Site 202 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 203 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 204 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 205 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 206 - Noct", rules=["FNet"], depends=["Divine Roost"]),
Data("FN Site 207 - Noct", rules=["FNet"], depends=["Divine Roost"]),
Data("FN Site 208 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 209 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 210 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 211 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 212 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 213 - Noct", rules=["FNet"], depends=["Divine Roost"]),
Data("FN Site 214 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 215 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 216 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 217 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 218 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 219 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 220 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 221 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 222 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 223 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 224 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 225 - Noct", rules=["FNet"], depends=["Chapter 3"]),
Data("Oblivia Ingress - Obli", depends=["Chapter 3"]),
Data("Yawning Giant - Obli", depends=["Chapter 3"]),
Data("Mesa Fortress - Obli", depends=["Chapter 3"]),
Data("Demons Pocket - Obli", rules=["Skell License"], depends=["Chapter 3"]),  # TAJ helpful but i guess not required
Data("Scabland Fortress - Obli", depends=["Chapter 3"]),
Data("River Isle - Obli", depends=["Chapter 3"]),
Data("Rooney Cavern - Obli", depends=["Chapter 3"]),
Data("Atop the Giant Ring - Obli", depends=["Chapter 3"]),  # advanced jump but long detour via Primeval Meadow
Data("Ejiri Promontory - Obli", depends=["Chapter 3"]),
Data("Leaning Ring - Obli", depends=["Chapter 3"]),
Data("Drowning Ring - Obli", depends=["Chapter 3"]),
Data("Beachside Trove - Obli", depends=["Chapter 3"]),
Data("Azure Lagoon - Obli", depends=["Chapter 3"]),
Data("Balance Rock - Obli", depends=["Chapter 3"]),
Data("South Coast - Obli", depends=["Chapter 3"]),
Data("Barbarich Desert - Obli", depends=["Chapter 3"]),
Data("Primeval Meadow - Obli", depends=["Chapter 3"]),  # advanced jump but long debtour
Data("Cryptic Sign - Obli", rules=["Skell License"], depends=["Chapter 3"]),  # maybe TAJ
Data("Jair Fortress - Obli", depends=["Chapter 3"]),
Data("Sea Whisper Valley - Obli", depends=["Chapter 3"]),
Data("West Ibra Ravine - Obli", depends=["Chapter 3"]),
Data("Central Ibra Ravine - Obli", depends=["Chapter 3"]),
Data("East Ibra Ravine - Obli", depends=["Chapter 3"]),
Data("Victory Rock - Obli", depends=["Chapter 3"]),
Data("Alexander Ridge - Obli", depends=["Chapter 3"]),
Data("Wrothian Stronghold - Obli", depends=["A Challenger Approaches"]),
Data("Dorian Caravan Location - Obli", depends=["Chapter 3"]),
Data("Lake Basel - Obli", depends=["Chapter 3"]),
Data("Floating Reef - Obli", rules=["Flight Module"], depends=["Chapter 3"]),  # technically accessable with only a skell but really really hard
Data("Ruins on the Sandbank - Obli", depends=["Chapter 3"]),
Data("Kings Falls - Obli", depends=["Chapter 3"]),
Data("Milligan Supply Base - Obli", depends=["Chapter 3"]),
Data("North Coast - Obli", depends=["Chapter 3"]),
Data("Big Arch - Obli", depends=["Chapter 3"]),
Data("Ruins on the Butte - Obli", depends=["Chapter 3"]),
Data("Kintrees - Obli", depends=["Chapter 3"]),  # advanced jump via Beehive Rock
Data("Aaroy Plain - Obli", depends=["Chapter 3"]),
Data("Twin Arches - Obli", depends=["Chapter 3"]),
Data("Devils Colony - Obli", depends=["Chapter 3"]),
Data("Great Washington Isle - Obli", rules=["Skell License"], depends=["Chapter 3"]),
Data("Cliffside Camp - Obli", depends=["Chapter 3"]),
Data("Crater Oasis - Obli", depends=["Chapter 3"]),
Data("North Ants Nest - Obli", depends=["Chapter 3"]),
Data("Ants Nest - Obli", depends=["Chapter 3"]),  # not sure what this even is
Data("South Ants Nest - Obli", depends=["Chapter 3"]),
Data("Keegan Ridge - Obli", depends=["Chapter 3"]),
Data("Stoyanov Trail - Obli", depends=["Chapter 3"]),
Data("Mount Edge Peak - Obli", rules=["Skell License"], depends=["Chapter 3"]),  # needs a few ramps
Data("Beehive Rock - Obli", depends=["Chapter 3"]),  # advanced jump from above
Data("Eddies Conquest - Obli", depends=["Chapter 3"]), # advanced jump
Data("FN Site 301 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 302 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 303 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 304 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 305 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 306 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 307 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 308 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 309 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 310 - Obli", rules=["FNet"], depends=["Chapter 3"]), # advanced jump
Data("FN Site 311 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 312 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 313 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 314 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 315 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 316 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 317 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 318 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 320 - Obli", rules=["FNet"], depends=["Floating Reef"]),
Data("FN Site 321 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 319 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 322 - Obli", rules=["FNet"], depends=["Chapter 3"]),
Data("Seabirds Beak - Sylv", depends=["Chapter 3"]),
Data("Needle Rock Sandsea - Sylv", depends=["Chapter 3"]),
Data("South Silent Sandsea - Sylv", depends=["Chapter 3"]),
Data("North Silent Sandsea - Sylv", depends=["Chapter 3"]),
Data("Lake Ciel - Sylv", depends=["Chapter 3"]),
Data("South Ciel Sandsea - Sylv", depends=["Chapter 3"]),
Data("West Ciel Sandsea - Sylv", depends=["Chapter 3"]),
Data("East Ciel Sandsea - Sylv", depends=["Chapter 3"]),
Data("North Ciel Sandsea - Sylv", depends=["Chapter 3"]),
Data("Shivering Sands - Sylv", depends=["Chapter 3"]),
Data("Xanadu Overlook - Sylv", depends=["Chapter 3"]),
Data("Cleansing Spring - Sylv", depends=["Chapter 3"]),
Data("Badr Stonebridge - Sylv", depends=["Chapter 3"]),
Data("Anvil Rock Two - Sylv", depends=["Chapter 3"]),
Data("Anvil Rock One - Sylv", depends=["Chapter 3"]),
Data("Anvil Sandplain - Sylv", depends=["Chapter 3"]),
Data("South Hardheart Canyon - Sylv", depends=["Chapter 3"]),
Data("Hardheart Canyon - Sylv", depends=["Chapter 3"]),
Data("North Hardheart Canyon - Sylv", depends=["Chapter 3"]),
Data("Southern Searoad - Sylv", depends=["Chapter 3"]),
Data("Sylvalum Searoad - Sylv", depends=["Chapter 3"]),
Data("Northern Searoad - Sylv", depends=["Chapter 3"]),
Data("Delusians North Summit - Sylv", depends=["Chapter 3"]),
Data("Gehenna Span - Sylv", depends=["Chapter 3"]),
Data("Delusians South Summit - Sylv", depends=["Chapter 3"]),
Data("South Cinderdunes - Sylv", depends=["Chapter 3"]),
Data("West Cinderdunes - Sylv", depends=["Chapter 3"]),
Data("North Cinderdunes - Sylv", depends=["Chapter 3"]),
Data("Samuel Incline - Sylv", depends=["Chapter 3"]),
Data("Cauldros Threshold - Sylv", depends=["Chapter 3"]),
Data("Hilal Meadow - Sylv", depends=["Chapter 3"]),
Data("Hilal Stronghold - Sylv", depends=["Chapter 3"]),
Data("Badr Basin - Sylv", depends=["Chapter 3"]),
Data("Badr Stronghold - Sylv", depends=["Chapter 3"]),
Data("Secluded Lava Lake - Sylv", depends=["Chapter 3"]),
Data("Cavernous Abyss - Sylv", rules=["Skell License"], depends=["Chapter 3"]),  # TAJ
Data("Banshee Cave - Sylv", depends=["Chapter 3"]),
Data("Quay Hollows - Sylv", rules=["Skell License"], depends=["Chapter 3"]),  # TAJ
Data("Den of the Dead - Sylv", depends=["Chapter 3"]),  # from above with jump
Data("Behemoths Shadows - Sylv", depends=["Chapter 3"]),
Data("Sandsprint Slope - Sylv", depends=["Chapter 3"]),
Data("Lesser Anvil - Sylv", depends=["Chapter 3"]),  # available from below but needs skell to get on top
Data("Arc Rock - Sylv", rules=["Skell License"], depends=["Chapter 3"]),  # TAJ
Data("Abyss Reservoir - Sylv", depends=["Cavernous Abyss"]),
Data("Noctilucent Sphere - Sylv", rules=["Skell License"], depends=["Chapter 3"]),  # TAJ
Data("Lower Delusian Mountains - Sylv", depends=["Chapter 3"]),
Data("Sandsprint Cavity - Sylv", depends=["Chapter 3"]),  # advanced jump, MenuReset from south side top because north has invisible wall
Data("Noctilucent Sphere Interior - Sylv", depends=["Noctilucent Sphere"]),
Data("FN Site 401 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 402 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 403 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 404 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 405 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 406 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 407 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 408 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 409 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 410 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 411 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 412 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 413 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 414 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 415 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 416 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 417 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 418 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 419 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 420 - Sylv", rules=["FNet"], depends=["Chapter 3"]),
Data("Drongo Caravan - Caul", depends=["Chapter 3"]),
Data("Scholes Battlegrounds - Caul", depends=["Chapter 3"]),
Data("Infernal Ledges - Caul", depends=["Chapter 3"]),
Data("Ancient Warscape - Caul", depends=["Chapter 3"]),
Data("Wildcat Fortress - Caul", depends=["Chapter 3"]),
Data("White Phosphor Lake - Caul", depends=["Chapter 3"]),
Data("Orrh Sim Gate - Caul", depends=["Chapter 3"]),
Data("Ganglion Antropolis - Caul", depends=["Chapter 3"]),  # accessable but not inside without mission
Data("Ruined City of Orrh Sim - Caul", depends=["Chapter 3"]),
Data("Gnahan Villa - Caul", depends=["Chapter 3"]),
Data("Emerian Battlegrounds - Caul", depends=["Chapter 3"]),
Data("Forgotten Mining Frigates - Caul", depends=["Chapter 3"]),
Data("Adder Byroad - Caul", depends=["Chapter 3"]),
Data("Bandits Refuge - Caul", depends=["Chapter 3"]),
Data("Slavebird Isle - Caul", depends=["Chapter 3"]),  # advanced jump
Data("Ganglion Weapons Hangar - Caul", depends=["Chapter 3"]),
Data("Orrh Sim Castle Ruins - Caul", depends=["Chapter 3"]),
Data("Tengus Playground - Caul", depends=["Chapter 3"]),
Data("Tphnom Shelf - Caul", depends=["Chapter 3"]),
Data("Kitsune Stronghold - Caul", depends=["Chapter 3"]),
Data("Sunset Falls - Caul", depends=["Chapter 3"]),
Data("Kwarah Villa - Caul", depends=["Chapter 3"]),
Data("Kwarah Cloister - Caul", depends=["Chapter 3"]),
Data("Boxtrap Checkpoint - Caul", depends=["Chapter 3"]),
Data("Mgando Mineral Spring - Caul", depends=["Chapter 3"]),
Data("Bestial Utopia - Caul", depends=["Chapter 3"]),
Data("Mgando Volcanic Crater - Caul", depends=["Chapter 3"]),
Data("Mount Mgando - Caul", depends=["Chapter 3"]),
Data("Old Ceremonial Hollow - Caul", depends=["Chapter 3"]),
Data("Old Ceremonial Hollow_1 - Caul", valid=False),
Data("Beneath Orrh Sim Keep - Caul", depends=["Chapter 3"]),
Data("Dragonbone Promontory - Caul", depends=["Chapter 3"]),
Data("Ternion Fork - Caul", depends=["Chapter 3"]),
Data("Abandoned Bivouac - Caul", depends=["Chapter 3"]),
Data("Mgando Gorge - Caul", depends=["Chapter 3"]),
Data("Titans Table - Caul", depends=["Chapter 3"]),
Data("Cauldros Gate - Caul", depends=["Chapter 3"]),
Data("Capital Wreckage - Caul", depends=["Chapter 3"]),
Data("Orrh Sim Capital Remains - Caul", depends=["Chapter 3"]),
Data("Orrh Sim Watchtowers - Caul", depends=["Chapter 3"]),
Data("Far Isle of Tzuo - Caul", depends=["Chapter 3"]),
Data("FN Site 501 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 502 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 503 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 504 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 505 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 506 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 507 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 508 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 509 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 510 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 511 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 512 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 513 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 514 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 515 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("FN Site 516 - Caul", rules=["FNet"], depends=["Chapter 3"]),
Data("Shadow Rise BC", depends=["Chapter 3"]),
Data("Shadow Beach BC", depends=["Chapter 3"]),
Data("East Gate BC", depends=["Chapter 3"]),
Data("South Janpath BC", depends=["Chapter 3"]),
Data("Biahno Grassland BC", depends=["Chapter 3"]),
Data("North Janpath BC", depends=["Chapter 3"]),
Data("Sayram Lake BC", depends=["Chapter 3"]),
Data("Roof Rock BC", depends=["Chapter 3"]),
Data("camp1501_09", valid=False),
Data("camp1501_10", valid=False),
Data("Rustpool Banks BC - Noct", depends=["Chapter 3"]),
Data("Whales Nostril BC - Noct", depends=["Chapter 3"]),
Data("Tripod Rock BC - Noct", depends=["Chapter 3"]),
Data("Canopied Nightwood BC - Noct", depends=["Chapter 3"]),
Data("Decapotamon BC - Noct", depends=["Chapter 3"]),
Data("Qing Long Glade BC - Noct", depends=["Chapter 3"]),
Data("Bloodpond Basin BC - Noct", depends=["Chapter 3"]),
Data("Dead Mans Ingress BC - Noct", depends=["Chapter 3"]),
Data("camp1601_09", valid=False),
Data("camp1601_10", valid=False),
Data("Oblivia Ingress BC - Obli", depends=["Chapter 3"]),
Data("Aaroy Plain BC - Obli", depends=["Chapter 3"]),
Data("Needle Bridge BC - Obli", depends=["Chapter 3"]),
Data("Broken Hill BC - Obli", depends=["Chapter 3"]),
Data("River Isle BC - Obli", depends=["Chapter 3"]),
Data("Balance Rock BC - Obli", depends=["Chapter 3"]),
Data("North Coast BC - Obli", depends=["Chapter 3"]),
Data("Cliffs Edge BC - Obli", depends=["Chapter 3"]),
Data("camp1701_09", valid=False),
Data("camp1701_10", valid=False),
Data("Ancient Warscape BC - Caul", depends=["Chapter 3"]),
Data("Titans Table BC - Caul", depends=["Chapter 3"]),
Data("Emerian Battlegrounds BC - Caul", depends=["Chapter 3"]),
Data("Rocky Lagoon BC - Caul", depends=["Chapter 3"]),
Data("Adder Byroad BC - Caul", depends=["Chapter 3"]),
Data("Ternion Fork BC - Caul", depends=["Chapter 3"]),
Data("Tphnom Shelf BC - Caul", depends=["Chapter 3"]),
Data("Mgando Gorge BC - Caul", depends=["Chapter 3"]),
Data("camp2001_09", valid=False),
Data("camp2001_10", valid=False),
Data("Seabirds Beak BC - Sylv", depends=["Chapter 3"]),
Data("Needle Rock BC - Sylv", depends=["Chapter 3"]),
Data("NW Ciel Sandsea BC - Sylv", depends=["Chapter 3"]),
Data("Hardheart Ravine BC - Sylv", depends=["Chapter 3"]),
Data("Delusians North Summit BC - Sylv", depends=["Chapter 3"]),
Data("Samuel Incline BC - Sylv", depends=["Chapter 3"]),
Data("North Silent Sandsea BC - Sylv", depends=["Chapter 3"]),
Data("Cauldros Threshold BC - Sylv", depends=["Chapter 3"]),
Data("camp2201_09", valid=False),
Data("camp2201_10", valid=False),
Data("NLA Last Defense Line - Chp 8", depends=["Chapter 8"]),
Data("NLA Primary Defense Line - Chp 8", depends=["Chapter 8"]),
Data("Zu Pharg Interception Line - Chp 10", depends=["Chapter 10"]),
Data("Lifehold Core - Chp 12", depends=["Chapter 12"]),
Data("Orrh Sim Keep - Caul", depends=["Chapter 3"]),
]