from . import Loc as Data

# flake8: noqa
# https://xenoblade.github.io/xbx/bdat/common_local_us/FLD_questlist.html
quests_data: list[Data] = [
Data("qstM00_title"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Chapter 1"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Chapter 2"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Chapter 3"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Chapter 4"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Chapter 5"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Chapter 6"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Chapter 7"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Chapter 8"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Chapter 9"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Chapter 10"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Chapter 11"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Chapter 12"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Story Missions Complete"),
Data("PLACEHOLDER", valid=False),
Data("qstM14_title"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("qstM15_title"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Hero's Ride"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Cinicula Assault"),
Data("PLACEHOLDER", valid=False),
Data("Better Latte Than Never"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Welcome Back, Conner"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("City Saviors"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Painful Lesson"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Law and Orders"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Data Miner"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Forest Foray"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Mayday"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Mayhem"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Mamma Mia!"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Mia Is Missing!"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Adventure!"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Mighty Mia"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("It's-a Mia!"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Proper Chopper"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Celeste Three"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Frontier Spirit"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Unknown Assailant"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Close Encounters"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Alien Nation"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Shotgun Diplomacy"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Line of Fire"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Alex's Last Stand"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Lakeside Getaway"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Predator and Prey"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Rise of the Blood Lobster"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Water Woes"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Booming Business"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Myles to Go"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Probe-fessional"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Planetary Pioneer (Part I)"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Primordia Trailblazing 1"),
Data("PLACEHOLDER", valid=False),
Data("Primordia Trailblazing 2"),
Data("PLACEHOLDER", valid=False),
Data("Primordia Trailblazing 3"),
Data("PLACEHOLDER", valid=False),
Data("Planetary Pioneer (Part II)"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Noctilum Trailblazing 1"),
Data("PLACEHOLDER", valid=False),
Data("Noctilum Trailblazing 2"),
Data("PLACEHOLDER", valid=False),
Data("Noctilum Trailblazing 3"),
Data("PLACEHOLDER", valid=False),
Data("Planetary Pioneer (Part III)"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Oblivia Trailblazing 1"),
Data("PLACEHOLDER", valid=False),
Data("Oblivia Trailblazing 2"),
Data("PLACEHOLDER", valid=False),
Data("Oblivia Trailblazing 3"),
Data("PLACEHOLDER", valid=False),
Data("Planetary Pioneer (Part IV)"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Sylvalum Trailblazing 1"),
Data("PLACEHOLDER", valid=False),
Data("Sylvalum Trailblazing 2"),
Data("PLACEHOLDER", valid=False),
Data("Sylvalum Trailblazing 3"),
Data("PLACEHOLDER", valid=False),
Data("Planetary Pioneer (Part V)"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Cauldros Trailblazing 1"),
Data("PLACEHOLDER", valid=False),
Data("Cauldros Trailblazing 2"),
Data("PLACEHOLDER", valid=False),
Data("Cauldros Trailblazing 3"),
Data("PLACEHOLDER", valid=False),
Data("Data Probe Challenge"),
Data("PLACEHOLDER", valid=False),
Data("Data Probe Progress"),
Data("PLACEHOLDER", valid=False),
Data("Data Probe Breakthrough"),
Data("PLACEHOLDER", valid=False),
Data("Data Probe Evolution"),
Data("PLACEHOLDER", valid=False),
Data("Data Probe Revolution"),
Data("PLACEHOLDER", valid=False),
Data("The Membership"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Silver Membership"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Gold Membership"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Platinum Membership"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Orphean Pluck"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Wrothian Innovation"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Root of All Evil"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Entrepreneurial Spirit"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("New Frontier"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Murder Most Foul"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("No Ma-non Need Apply"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Pip-Squeak"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Handy Ma-non"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Emotion Commotion"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Fashionista"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Miracle Maker"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Rites of Ruin"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("That's In-Credible!"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Waste Not, Want Not"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Snipe Hunt"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Party Line"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Tree-mendous"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Kidnapped: Oll Valdileo"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Kidnapped: Rada Valdileo"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Kidnapped: Uzoma Vassago"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Grim Undertaking"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Here Come the Brides"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Quegga's Gift"),
Data("PLACEHOLDER", valid=False),
Data("A New Life"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Herbivores, Unite!"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Forbidden Love"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Art of War"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("An Ancient Legend"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Training Day"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Ultimate Price"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Slovity's Rampage"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Slovity's Revenge"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("My Angel, My Lana"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Missing in Action"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Setting Forth"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Muimui's Meltdown"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Tip of the Cap"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Bread and a Circus"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Sword of Legendaryness"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Bodyguard"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Special Delivery"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Trading Floor"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Trade Agreement"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Sparking a Smile"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Unsatisfied Customer"),
Data("PLACEHOLDER", valid=False),
Data("Castle in the Sky"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Big Bang"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Hair Apparent"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Supplies Surprise"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Divine Nopopon"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Two Warriors"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Dish Served Cold"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Until the End"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Leaving the Nest"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Cooking Schooled"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Queen Is Dead"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Lend an Ear"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Unbreakable Sword"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Gold Rush"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Plans of Attack"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Gauntlet"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Sun'celeg Rises"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Lone Survivors"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Journey Begins"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Circle of Life"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("House Call"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("No-show Nen'celeg"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Bug Whisperer"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Going Viral"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Ovah and Out"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Fateful Choice"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Good Neighbors"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Haywire!"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Dubious Operation"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Good Thief"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Gorkwa Games"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Voltant Visionary"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Pollution Solution"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Child of Mira"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Pack It In"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Stop, Thief!"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Old Gods"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Good Fortun"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Definian Downfall"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Definian Love"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Definian Love"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Attack on Biahno Hills"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Mystery Man"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Professor B's Return"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Professorial"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Duel (Part I)"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Duel (Part II)"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Duel (Part III)"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Duel (Part IV)"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Lurker"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Lesson from the Grave"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Fortun and Glory"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Prone Sweet Prone"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Rescue at the Ensconced Citadel"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Dead Men Tell No Tales"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Cavern Crushers"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Turf War"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Skell License"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 1"),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 2"),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 3"),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 4"),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 5"),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 6"),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 7"),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 8"),
Data("PLACEHOLDER", valid=False),
Data("White Lifehold"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Black Lifehold"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("BLADE Level Basics"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Mamma Mia!"),
Data("PLACEHOLDER", valid=False),
Data("Mamma Mia!"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Bodyguard"),
Data("PLACEHOLDER", valid=False),
Data("The Bodyguard"),
Data("PLACEHOLDER", valid=False),
Data("The Bodyguard"),
Data("PLACEHOLDER", valid=False),
Data("A Dish Served Cold"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Rise of the Blood Lobster"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Lionhearted"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Manhunt"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Renewed Will"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Fathers and Sons"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Nine Lives"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Boot Camp"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Close Comrades"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Soldier of the Harriers"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Friend in Need"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Matchmaker"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Repair Job"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("To Serve Nopon"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("L's Conundrum"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Nopon Heir"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Ties That Bind"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("BFFs"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("We Were Soldiers"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Then and Now"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("New in New LA"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Fitting In"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Spy Games"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Prospective Partners"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Nagi's Time"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Reporting for Duty"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Day in the Life"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Two Peas in a Pod"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Challenger Approaches"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Lionhearted"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Dodonga Caravan"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Dorian Caravan"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Meeting Yelv", rules=["Lvl 14", "Tissue Sample"], depends=["Chapter 3"]), # depends mission a/b/c
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Arms and the Man"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Yelv's Partner"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Mad Monk", rules=["Blade License", "Lvl 20"], depends=["Chapter 5"]),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Bozé's Way"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Bozé's Ignorance"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A New Rival?", rules=["FNet", "Lvl 15"], depends=["Chapter 3", "FN Node 118"]),  # depends Installation, Research, Miranium
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The King of Fear"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Climbing the Ladder"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Bottoms Up"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Blitzkrieg"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Blitzkrieg"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Brotherly Love"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Foggy Dilemma"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Great Divide"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("My Dream"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Little Rich Girl"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Serial Thriller"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Weaponized", rules=["Blade License", "Lvl 18", "Quest Weaponized"], depends=["Chapter 4"]),  # depends: Guinea Pigs Wanted!
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("What the Skell?!"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Rapid Misfire"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Hope Springs Eternal"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A False Hope"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Present for Hope"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("A Girl's Wings"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Mia Grows Up"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Yardley's Scheme"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Hackers"),
Data("PLACEHOLDER", valid=False),
Data("Securing Lan'cord"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Haywire!"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Elma's Task A"),
Data("PLACEHOLDER", valid=False),
Data("Elma's Task B"),
Data("PLACEHOLDER", valid=False),
Data("Elma's Task C"),
Data("PLACEHOLDER", valid=False),
Data("Mission A"),
Data("PLACEHOLDER", valid=False),
Data("Mission B"),
Data("PLACEHOLDER", valid=False),
Data("Mission C"),
Data("PLACEHOLDER", valid=False),
Data("Installation"),
Data("PLACEHOLDER", valid=False),
Data("Research"),
Data("PLACEHOLDER", valid=False),
Data("Miranium"),
Data("PLACEHOLDER", valid=False),
Data("Material Hunt A"),
Data("PLACEHOLDER", valid=False),
Data("Material Hunt B"),
Data("PLACEHOLDER", valid=False),
Data("Material Hunt C"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Mayhem"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Fortun and Glory"),
Data("Blitzkrieg"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("qst0001_title"),
Data("PLACEHOLDER", valid=False),
Data("qst0001_title"),
Data("PLACEHOLDER", valid=False),
Data("qst0001_title"),
Data("PLACEHOLDER", valid=False),
Data("qst0001_title"),
Data("PLACEHOLDER", valid=False),
Data("qst0001_title"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("qst0402_title"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("The Divine Napopon"),
Data("PLACEHOLDER", valid=False),
Data("The Divine Nipopon"),
Data("PLACEHOLDER", valid=False),
Data("The Divine Nupopon"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 7"),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 7"),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 7"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 7"),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 7"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Proficiency Exam 7"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Miranium Request"),
Data("PLACEHOLDER", valid=False),
Data("Behold the Cranjelly"),
Data("PLACEHOLDER", valid=False),
Data("Suid Sweep"),
Data("PLACEHOLDER", valid=False),
Data("Arms Testers Wanted"),
Data("PLACEHOLDER", valid=False),
Data("Partners in Pearls"),
Data("PLACEHOLDER", valid=False),
Data("A Clandestine Operation"),
Data("PLACEHOLDER", valid=False),
Data("Archibolt, the Revolutionary"),
Data("PLACEHOLDER", valid=False),
Data("Sirene, the Lost"),
Data("PLACEHOLDER", valid=False),
Data("Search Request"),
Data("PLACEHOLDER", valid=False),
Data("Acorn...Abacuses?"),
Data("PLACEHOLDER", valid=False),
Data("Mortifole Mulching"),
Data("PLACEHOLDER", valid=False),
Data("The Next Big Thing"),
Data("PLACEHOLDER", valid=False),
Data("The Fail Parade"),
Data("PLACEHOLDER", valid=False),
Data("Indigen Investigation"),
Data("PLACEHOLDER", valid=False),
Data("Desdemona, the Subterranean"),
Data("PLACEHOLDER", valid=False),
Data("Blatta Splatter"),
Data("PLACEHOLDER", valid=False),
Data("Evello Eradication"),
Data("PLACEHOLDER", valid=False),
Data("From Idea to Inventory"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Request"),
Data("PLACEHOLDER", valid=False),
Data("Melanya, the Sound Sleeper"),
Data("PLACEHOLDER", valid=False),
Data("Offing Ovis"),
Data("PLACEHOLDER", valid=False),
Data("Partners in Prototyping"),
Data("PLACEHOLDER", valid=False),
Data("Germivores No More"),
Data("PLACEHOLDER", valid=False),
Data("Reclaiming the Whale"),
Data("PLACEHOLDER", valid=False),
Data("Yune, the Ambusher"),
Data("PLACEHOLDER", valid=False),
Data("Skell Repair: Optics"),
Data("PLACEHOLDER", valid=False),
Data("Blatta Splatter"),
Data("PLACEHOLDER", valid=False),
Data("A Spicy New Spark"),
Data("PLACEHOLDER", valid=False),
Data("The Skell Spectrum"),
Data("PLACEHOLDER", valid=False),
Data("Dirty Work"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Request"),
Data("PLACEHOLDER", valid=False),
Data("Rabbit Research"),
Data("PLACEHOLDER", valid=False),
Data("Suid Sirloin"),
Data("PLACEHOLDER", valid=False),
Data("Arms Testers Wanted"),
Data("PLACEHOLDER", valid=False),
Data("A New Taste Sensation"),
Data("PLACEHOLDER", valid=False),
Data("Elusive Orewood"),
Data("PLACEHOLDER", valid=False),
Data("Tourteau, the Delectable"),
Data("PLACEHOLDER", valid=False),
Data("Roderick, the Fleet-Footed"),
Data("PLACEHOLDER", valid=False),
Data("Clean and Green"),
Data("PLACEHOLDER", valid=False),
Data("Partners in Prototyping"),
Data("PLACEHOLDER", valid=False),
Data("Squashing Scirpos"),
Data("PLACEHOLDER", valid=False),
Data("Indigen Investigation"),
Data("PLACEHOLDER", valid=False),
Data("Reclaiming the Whale"),
Data("PLACEHOLDER", valid=False),
Data("Fending Off Forfexes"),
Data("PLACEHOLDER", valid=False),
Data("Schneider, the Cliffpercher"),
Data("PLACEHOLDER", valid=False),
Data("Thinning the Thalluses"),
Data("PLACEHOLDER", valid=False),
Data("Purgovent Purge"),
Data("PLACEHOLDER", valid=False),
Data("A History Lesson"),
Data("PLACEHOLDER", valid=False),
Data("From Idea to Inventory"),
Data("PLACEHOLDER", valid=False),
Data("Celedonio, the Battle-Tested"),
Data("PLACEHOLDER", valid=False),
Data("Papil Punisher"),
Data("PLACEHOLDER", valid=False),
Data("The Jewelmonger"),
Data("PLACEHOLDER", valid=False),
Data("Glamor Girl"),
Data("PLACEHOLDER", valid=False),
Data("A Crickety Cure"),
Data("PLACEHOLDER", valid=False),
Data("Thick-Skinned"),
Data("PLACEHOLDER", valid=False),
Data("Pounding Puges"),
Data("PLACEHOLDER", valid=False),
Data("Arms Testers Wanted"),
Data("PLACEHOLDER", valid=False),
Data("The Next Big Thing"),
Data("PLACEHOLDER", valid=False),
Data("Party Procurement"),
Data("PLACEHOLDER", valid=False),
Data("Angelita, the Blade Bouquet"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Request"),
Data("PLACEHOLDER", valid=False),
Data("Lilting Lilies"),
Data("PLACEHOLDER", valid=False),
Data("Adsecula Extermination"),
Data("PLACEHOLDER", valid=False),
Data("Offing Ovis"),
Data("PLACEHOLDER", valid=False),
Data("Skell Repair: Balancer"),
Data("PLACEHOLDER", valid=False),
Data("Hazmat Hunt"),
Data("PLACEHOLDER", valid=False),
Data("Hephaestus, the Absconder"),
Data("PLACEHOLDER", valid=False),
Data("Gaga for Guavas"),
Data("PLACEHOLDER", valid=False),
Data("No Friends Like Nopon"),
Data("PLACEHOLDER", valid=False),
Data("Filter Testing"),
Data("PLACEHOLDER", valid=False),
Data("Arms Testers Wanted"),
Data("PLACEHOLDER", valid=False),
Data("A Look at Lichen"),
Data("PLACEHOLDER", valid=False),
Data("Xenotech Survey"),
Data("PLACEHOLDER", valid=False),
Data("Oskar, the Summer Squall"),
Data("PLACEHOLDER", valid=False),
Data("Edgardo, the Carefree"),
Data("PLACEHOLDER", valid=False),
Data("Offing Ovis"),
Data("PLACEHOLDER", valid=False),
Data("Popular Peppers"),
Data("PLACEHOLDER", valid=False),
Data("Lost Memento"),
Data("PLACEHOLDER", valid=False),
Data("From Idea to Inventory"),
Data("PLACEHOLDER", valid=False),
Data("Eliane, the Unmoved"),
Data("PLACEHOLDER", valid=False),
Data("Nixing Lepyxes"),
Data("PLACEHOLDER", valid=False),
Data("The Next Big Thing"),
Data("PLACEHOLDER", valid=False),
Data("Lab Rat Run"),
Data("PLACEHOLDER", valid=False),
Data("De-stressing Delicacy"),
Data("PLACEHOLDER", valid=False),
Data("Asana, the Azure Star"),
Data("PLACEHOLDER", valid=False),
Data("Culling Caecuses"),
Data("PLACEHOLDER", valid=False),
Data("Marnuck Masher"),
Data("PLACEHOLDER", valid=False),
Data("Vanquishing Visigels"),
Data("PLACEHOLDER", valid=False),
Data("Recycled Octopi"),
Data("PLACEHOLDER", valid=False),
Data("Nopon Culture 101"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Request"),
Data("PLACEHOLDER", valid=False),
Data("Finding Morrows Today"),
Data("PLACEHOLDER", valid=False),
Data("Primordian Cavern Crawl"),
Data("PLACEHOLDER", valid=False),
Data("An Ancient Mystery"),
Data("PLACEHOLDER", valid=False),
Data("The Fearsome Placid Duoguill"),
Data("PLACEHOLDER", valid=False),
Data("Mesgen, the Fairweathered"),
Data("PLACEHOLDER", valid=False),
Data("Casper, the Unhealthy Eater"),
Data("PLACEHOLDER", valid=False),
Data("Suid Sweep"),
Data("PLACEHOLDER", valid=False),
Data("Arms Testers Wanted"),
Data("PLACEHOLDER", valid=False),
Data("Partners in Prototyping"),
Data("PLACEHOLDER", valid=False),
Data("Productivity Power-Up"),
Data("PLACEHOLDER", valid=False),
Data("Indigen Investigation"),
Data("PLACEHOLDER", valid=False),
Data("Skell Repair: Arm"),
Data("PLACEHOLDER", valid=False),
Data("Yessenia, the Husky-Voiced"),
Data("PLACEHOLDER", valid=False),
Data("Taming Tectinsulas"),
Data("PLACEHOLDER", valid=False),
Data("The Scrubdown"),
Data("PLACEHOLDER", valid=False),
Data("Mephite Mayhem"),
Data("PLACEHOLDER", valid=False),
Data("Standing Tall(er)"),
Data("PLACEHOLDER", valid=False),
Data("A Little Protection"),
Data("PLACEHOLDER", valid=False),
Data("Ferdinand, the Fortuitous"),
Data("PLACEHOLDER", valid=False),
Data("Adsecula Extermination"),
Data("PLACEHOLDER", valid=False),
Data("Mikulas, the Keystone"),
Data("PLACEHOLDER", valid=False),
Data("Partners in Prototyping"),
Data("PLACEHOLDER", valid=False),
Data("Rocky Research"),
Data("PLACEHOLDER", valid=False),
Data("Star Sand Seeker"),
Data("PLACEHOLDER", valid=False),
Data("Laying Lophids Low"),
Data("PLACEHOLDER", valid=False),
Data("The Next Big Thing"),
Data("PLACEHOLDER", valid=False),
Data("The Voltant Void"),
Data("PLACEHOLDER", valid=False),
Data("Marnuck Masher"),
Data("PLACEHOLDER", valid=False),
Data("Megajolt Rattle and Roll"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Request"),
Data("PLACEHOLDER", valid=False),
Data("Garlic 2.0"),
Data("PLACEHOLDER", valid=False),
Data("A Repairman's Resolve"),
Data("PLACEHOLDER", valid=False),
Data("A New Audience"),
Data("PLACEHOLDER", valid=False),
Data("Laying Lophids Low"),
Data("PLACEHOLDER", valid=False),
Data("Squashing Scirpos"),
Data("PLACEHOLDER", valid=False),
Data("Bloodsuckers"),
Data("PLACEHOLDER", valid=False),
Data("Ictus Infestation"),
Data("PLACEHOLDER", valid=False),
Data("Sundering Saltats"),
Data("PLACEHOLDER", valid=False),
Data("Coolest of the Cool"),
Data("PLACEHOLDER", valid=False),
Data("Must-Have Blobs"),
Data("PLACEHOLDER", valid=False),
Data("Alfombra, the Transcendent"),
Data("PLACEHOLDER", valid=False),
Data("Extreme Fluffiness"),
Data("PLACEHOLDER", valid=False),
Data("A Hard Pill to Swallow"),
Data("PLACEHOLDER", valid=False),
Data("Axing Falsaxum"),
Data("PLACEHOLDER", valid=False),
Data("Skell Repair: Frame"),
Data("PLACEHOLDER", valid=False),
Data("Duoguill Duty"),
Data("PLACEHOLDER", valid=False),
Data("Octo-suka Leg Surprise"),
Data("PLACEHOLDER", valid=False),
Data("Ludvik, the Picky Eater"),
Data("PLACEHOLDER", valid=False),
Data("Rainbow Wingtips"),
Data("PLACEHOLDER", valid=False),
Data("Pounding Puges"),
Data("PLACEHOLDER", valid=False),
Data("Skell Repair: Plunger"),
Data("PLACEHOLDER", valid=False),
Data("What's a Taoman?"),
Data("PLACEHOLDER", valid=False),
Data("Lockhart, the Killer of Hope"),
Data("PLACEHOLDER", valid=False),
Data("Sadar, the Unhinged"),
Data("PLACEHOLDER", valid=False),
Data("Shrad Shredder"),
Data("PLACEHOLDER", valid=False),
Data("Night Combat Puge"),
Data("PLACEHOLDER", valid=False),
Data("And Stay Out!"),
Data("PLACEHOLDER", valid=False),
Data("A New Flavor"),
Data("PLACEHOLDER", valid=False),
Data("The Emerian Battlegrounds"),
Data("PLACEHOLDER", valid=False),
Data("Search Request"),
Data("PLACEHOLDER", valid=False),
Data("What's a Rocambole?"),
Data("PLACEHOLDER", valid=False),
Data("Xenotech Research"),
Data("PLACEHOLDER", valid=False),
Data("Papil Punisher"),
Data("PLACEHOLDER", valid=False),
Data("Indigen Investigation"),
Data("PLACEHOLDER", valid=False),
Data("Engrossed in Grosium"),
Data("PLACEHOLDER", valid=False),
Data("Dieter, the Epicure"),
Data("PLACEHOLDER", valid=False),
Data("Arms Testers Wanted"),
Data("PLACEHOLDER", valid=False),
Data("Emergency Stores"),
Data("PLACEHOLDER", valid=False),
Data("Clemente, the Iron Meteor"),
Data("PLACEHOLDER", valid=False),
Data("From Idea to Inventory"),
Data("PLACEHOLDER", valid=False),
Data("Aria, the Zauberflöte"),
Data("PLACEHOLDER", valid=False),
Data("Grex Wrecker"),
Data("PLACEHOLDER", valid=False),
Data("Data Recovery"),
Data("PLACEHOLDER", valid=False),
Data("Ridding Insidias"),
Data("PLACEHOLDER", valid=False),
Data("Partners in Prototyping"),
Data("PLACEHOLDER", valid=False),
Data("An Angelic Accessory"),
Data("PLACEHOLDER", valid=False),
Data("Sviatoslav, the Reproachful"),
Data("PLACEHOLDER", valid=False),
Data("Culling Caecuses"),
Data("PLACEHOLDER", valid=False),
Data("Nopon Chest"),
Data("PLACEHOLDER", valid=False),
Data("Murra Master"),
Data("PLACEHOLDER", valid=False),
Data("Dobromila, the Alluring"),
Data("PLACEHOLDER", valid=False),
Data("Skell Repair: Cylinder"),
Data("PLACEHOLDER", valid=False),
Data("Fell Fashion"),
Data("PLACEHOLDER", valid=False),
Data("Jacul Jaunt"),
Data("PLACEHOLDER", valid=False),
Data("Sweet Maple Goodness"),
Data("PLACEHOLDER", valid=False),
Data("Tents by the Ton"),
Data("PLACEHOLDER", valid=False),
Data("Eddy, the Electric Heat"),
Data("PLACEHOLDER", valid=False),
Data("Dawid, the Destrier"),
Data("PLACEHOLDER", valid=False),
Data("A Probing Issue"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Request"),
Data("PLACEHOLDER", valid=False),
Data("Persimmons, Please!"),
Data("PLACEHOLDER", valid=False),
Data("The Jewelmonger"),
Data("PLACEHOLDER", valid=False),
Data("Talk of the Town"),
Data("PLACEHOLDER", valid=False),
Data("Ridill, the Arrogant"),
Data("PLACEHOLDER", valid=False),
Data("Plucking Auravises"),
Data("PLACEHOLDER", valid=False),
Data("A Precious Legacy"),
Data("PLACEHOLDER", valid=False),
Data("Ridding Insidias"),
Data("PLACEHOLDER", valid=False),
Data("Thinning the Thalluses"),
Data("PLACEHOLDER", valid=False),
Data("From Idea to Inventory"),
Data("PLACEHOLDER", valid=False),
Data("In Search of New Horizons"),
Data("PLACEHOLDER", valid=False),
Data("Shinhwa, the Sagacious"),
Data("PLACEHOLDER", valid=False),
Data("Preparations for War"),
Data("PLACEHOLDER", valid=False),
Data("Straight from the Heart"),
Data("PLACEHOLDER", valid=False),
Data("Arms Testers Wanted"),
Data("PLACEHOLDER", valid=False),
Data("The Stick"),
Data("PLACEHOLDER", valid=False),
Data("Vittorio, the Battle-Scarred"),
Data("PLACEHOLDER", valid=False),
Data("Ramus, the Supersonic"),
Data("PLACEHOLDER", valid=False),
Data("The Poshest Produce"),
Data("PLACEHOLDER", valid=False),
Data("Search Request"),
Data("PLACEHOLDER", valid=False),
Data("Turba Tracker"),
Data("PLACEHOLDER", valid=False),
Data("Skell Repair: Antenna"),
Data("PLACEHOLDER", valid=False),
Data("Andrei, the Cunning"),
Data("PLACEHOLDER", valid=False),
Data("Ictus Infestation"),
Data("PLACEHOLDER", valid=False),
Data("Skell Repair: Thruster"),
Data("PLACEHOLDER", valid=False),
Data("Arms Testers Wanted"),
Data("PLACEHOLDER", valid=False),
Data("Prinsipe, the Ravenous"),
Data("PLACEHOLDER", valid=False),
Data("A Scanner Scheme"),
Data("PLACEHOLDER", valid=False),
Data("A New Spark"),
Data("PLACEHOLDER", valid=False),
Data("Izgnanie, the Smoldering"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Request"),
Data("PLACEHOLDER", valid=False),
Data("Extreme Pansies"),
Data("PLACEHOLDER", valid=False),
Data("Sundering Saltats"),
Data("PLACEHOLDER", valid=False),
Data("Mortifole Mulching"),
Data("PLACEHOLDER", valid=False),
Data("Can't Make an Omelet..."),
Data("PLACEHOLDER", valid=False),
Data("A Moment of Brilliance"),
Data("PLACEHOLDER", valid=False),
Data("Bogdan, the Dense"),
Data("PLACEHOLDER", valid=False),
Data("The Care Package"),
Data("PLACEHOLDER", valid=False),
Data("Germivores No More"),
Data("PLACEHOLDER", valid=False),
Data("Search Request"),
Data("PLACEHOLDER", valid=False),
Data("Research on a Budget"),
Data("PLACEHOLDER", valid=False),
Data("Si-el, the Vacuous"),
Data("PLACEHOLDER", valid=False),
Data("Fending Off Forfexes"),
Data("PLACEHOLDER", valid=False),
Data("Ernest, the Contemplative"),
Data("PLACEHOLDER", valid=False),
Data("The Jewelmonger"),
Data("PLACEHOLDER", valid=False),
Data("Arms Testers Wanted"),
Data("PLACEHOLDER", valid=False),
Data("The Ultimate Pursuit"),
Data("PLACEHOLDER", valid=False),
Data("Reclaiming the Whale"),
Data("PLACEHOLDER", valid=False),
Data("Gathering Thunder"),
Data("PLACEHOLDER", valid=False),
Data("Camille, the Immortal"),
Data("PLACEHOLDER", valid=False),
Data("The Phantasmagoric Fan"),
Data("PLACEHOLDER", valid=False),
Data("Aeviter Ace"),
Data("PLACEHOLDER", valid=False),
Data("Covert Operations"),
Data("PLACEHOLDER", valid=False),
Data("Stola, the Unchained"),
Data("PLACEHOLDER", valid=False),
Data("Pugilith Pounder"),
Data("PLACEHOLDER", valid=False),
Data("Lending a Hand"),
Data("PLACEHOLDER", valid=False),
Data("A Desert Deferred"),
Data("PLACEHOLDER", valid=False),
Data("Eisen, the Ebon Rock"),
Data("PLACEHOLDER", valid=False),
Data("Coil, the Never-Ending"),
Data("PLACEHOLDER", valid=False),
Data("Mount M'gando Mineralogy"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Request"),
Data("PLACEHOLDER", valid=False),
Data("A Spot of Gardening"),
Data("PLACEHOLDER", valid=False),
Data("Indigen Investigation"),
Data("PLACEHOLDER", valid=False),
Data("Mincing Millesaurs"),
Data("PLACEHOLDER", valid=False),
Data("In a Jam"),
Data("PLACEHOLDER", valid=False),
Data("Hayreddin, the Territorial"),
Data("PLACEHOLDER", valid=False),
Data("Ovah Overdrive"),
Data("PLACEHOLDER", valid=False),
Data("Lambert, the Divine Wind"),
Data("PLACEHOLDER", valid=False),
Data("Partners in Prototyping"),
Data("PLACEHOLDER", valid=False),
Data("Dilus Destroyer"),
Data("PLACEHOLDER", valid=False),
Data("Bananaleaf Bonanza"),
Data("PLACEHOLDER", valid=False),
Data("Test Data Retrieval"),
Data("PLACEHOLDER", valid=False),
Data("Simius Smackdown"),
Data("PLACEHOLDER", valid=False),
Data("Silvestre, the Morning Light"),
Data("PLACEHOLDER", valid=False),
Data("The Carrot"),
Data("PLACEHOLDER", valid=False),
Data("The Endless Ring"),
Data("PLACEHOLDER", valid=False),
Data("Legacy of the White Whale"),
Data("PLACEHOLDER", valid=False),
Data("Barnabas, the Despot"),
Data("PLACEHOLDER", valid=False),
Data("Arms Testers Wanted"),
Data("PLACEHOLDER", valid=False),
Data("From Idea to Inventory"),
Data("PLACEHOLDER", valid=False),
Data("Tersqual Takedown"),
Data("PLACEHOLDER", valid=False),
Data("Gathering Grenades"),
Data("PLACEHOLDER", valid=False),
Data("Anselm, the Triumphant"),
Data("PLACEHOLDER", valid=False),
Data("Candelario, the Bronze"),
Data("PLACEHOLDER", valid=False),
Data("New Product!"),
Data("PLACEHOLDER", valid=False),
Data("The Taste of Tersqual"),
Data("PLACEHOLDER", valid=False),
Data("Arms Testers Wanted"),
Data("PLACEHOLDER", valid=False),
Data("Skell Repair: Head"),
Data("PLACEHOLDER", valid=False),
Data("A Community Service"),
Data("PLACEHOLDER", valid=False),
Data("Vainamo, the Bellower"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Request"),
Data("PLACEHOLDER", valid=False),
Data("Beating the Heat"),
Data("PLACEHOLDER", valid=False),
Data("Partners in Prototyping"),
Data("PLACEHOLDER", valid=False),
Data("Caesar, the Hundred-Eyed"),
Data("PLACEHOLDER", valid=False),
Data("A Novel Proposal"),
Data("PLACEHOLDER", valid=False),
Data("Squashing Scirpos"),
Data("PLACEHOLDER", valid=False),
Data("Aprica Assault"),
Data("PLACEHOLDER", valid=False),
Data("Sarcosuchus, the Iron-Eater"),
Data("PLACEHOLDER", valid=False),
Data("The Next Big Thing"),
Data("PLACEHOLDER", valid=False),
Data("Arms Testers Wanted"),
Data("PLACEHOLDER", valid=False),
Data("Scaling Up"),
Data("PLACEHOLDER", valid=False),
Data("Sumptuous Sleeping"),
Data("PLACEHOLDER", valid=False),
Data("Plucking Auravises"),
Data("PLACEHOLDER", valid=False),
Data("Vilem, the Gold-Scaled"),
Data("PLACEHOLDER", valid=False),
Data("Petramand Patrol"),
Data("PLACEHOLDER", valid=False),
Data("The Herbalist"),
Data("PLACEHOLDER", valid=False),
Data("A Hero's Welcome"),
Data("PLACEHOLDER", valid=False),
Data("Partners in Prototyping"),
Data("PLACEHOLDER", valid=False),
Data("Ictus Infestation"),
Data("PLACEHOLDER", valid=False),
Data("Goliath, the Stronghold"),
Data("PLACEHOLDER", valid=False),
Data("Bottomless Baggage"),
Data("PLACEHOLDER", valid=False),
Data("Juicy Analysis"),
Data("PLACEHOLDER", valid=False),
Data("Incomprehensible Weapon"),
Data("PLACEHOLDER", valid=False),
Data("Laurencio, the Fog Bow"),
Data("PLACEHOLDER", valid=False),
Data("Petramand Patrol"),
Data("PLACEHOLDER", valid=False),
Data("Ya-rhat, the Thundercloud"),
Data("PLACEHOLDER", valid=False),
Data("The Jewelmonger"),
Data("PLACEHOLDER", valid=False),
Data("A Revised Regimen"),
Data("PLACEHOLDER", valid=False),
Data("Vortice, the Deific Blast"),
Data("PLACEHOLDER", valid=False),
Data("Search Request"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Exchange"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Exchange"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Exchange"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Exchange"),
Data("PLACEHOLDER", valid=False),
Data("Miranium Exchange"),
Data("PLACEHOLDER", valid=False),
Data("New Orders"),
Data("PLACEHOLDER", valid=False),
Data("New Orders"),
Data("PLACEHOLDER", valid=False),
Data("New Orders"),
Data("PLACEHOLDER", valid=False),
Data("New Orders"),
Data("PLACEHOLDER", valid=False),
Data("New Orders"),
Data("PLACEHOLDER", valid=False),
Data("New Orders"),
Data("PLACEHOLDER", valid=False),
Data("New Orders"),
Data("PLACEHOLDER", valid=False),
Data("New Orders"),
Data("PLACEHOLDER", valid=False),
Data("New Orders"),
Data("PLACEHOLDER", valid=False),
Data("qstM00_title"),
Data("PLACEHOLDER", valid=False),
Data("qstM00_title"),
Data("PLACEHOLDER", valid=False),
Data("qstM00_title"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("House of Cards"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Off the Record"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Off the Record"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Off the Record"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
Data("Backup Request"),
Data("PLACEHOLDER", valid=False),
Data("Guinea Pigs Wanted!"),
Data("PLACEHOLDER", valid=False),
Data("Marry Me!"),
Data("PLACEHOLDER", valid=False),
Data("Backup Request"),
Data("PLACEHOLDER", valid=False),
Data("Leafy Learning"),
Data("PLACEHOLDER", valid=False),
Data("Find the Freighter"),
Data("PLACEHOLDER", valid=False),
Data("Team Corwin in Crisis"),
Data("PLACEHOLDER", valid=False),
Data("A Concerned Citizen"),
Data("PLACEHOLDER", valid=False),
Data("Escort Requested"),
Data("PLACEHOLDER", valid=False),
Data("Settling the Score"),
Data("PLACEHOLDER", valid=False),
Data("Securing Our Safety"),
Data("PLACEHOLDER", valid=False),
Data("Miranium for Fun and Profit"),
Data("PLACEHOLDER", valid=False),
Data("A Miranium Problem"),
Data("PLACEHOLDER", valid=False),
Data("Wanted: Miranium Expert"),
Data("PLACEHOLDER", valid=False),
Data("Skell Maintenance"),
Data("PLACEHOLDER", valid=False),
Data("Find My Doc!"),
Data("PLACEHOLDER", valid=False),
Data("Calling All Testers!"),
Data("PLACEHOLDER", valid=False),
Data("Weapons Cleanup Crew"),
Data("PLACEHOLDER", valid=False),
Data("One Little Problem"),
Data("PLACEHOLDER", valid=False),
Data("The Rescue Request"),
Data("PLACEHOLDER", valid=False),
Data("The Scars of War"),
Data("PLACEHOLDER", valid=False),
Data("Tree Lovers Only"),
Data("PLACEHOLDER", valid=False),
Data("A Practice Partner"),
Data("PLACEHOLDER", valid=False),
Data("Misery of Moimoi!"),
Data("PLACEHOLDER", valid=False),
Data("Partner Wanted!"),
Data("PLACEHOLDER", valid=False),
Data("Search Support Request"),
Data("PLACEHOLDER", valid=False),
Data("Departure's Eve"),
Data("PLACEHOLDER", valid=False),
Data("The Search for Kun'luarb"),
Data("PLACEHOLDER", valid=False),
Data("Under the Weather"),
Data("PLACEHOLDER", valid=False),
Data("In Support of Science"),
Data("PLACEHOLDER", valid=False),
Data("Anomaly Analysis"),
Data("PLACEHOLDER", valid=False),
Data("Tech Supply"),
Data("PLACEHOLDER", valid=False),
Data("Buddies on the Brink"),
Data("PLACEHOLDER", valid=False),
Data("The Call to Counterattack"),
Data("PLACEHOLDER", valid=False),
Data("The Final Faceoff"),
Data("PLACEHOLDER", valid=False),
Data("Ambush"),
Data("PLACEHOLDER", valid=False),
Data("Rendezvous at the Lab!"),
Data("PLACEHOLDER", valid=False),
Data("A President Not Present"),
Data("PLACEHOLDER", valid=False),
Data("In Need of a Hand"),
Data("PLACEHOLDER", valid=False),
Data("Hailing the Chief!"),
Data("PLACEHOLDER", valid=False),
Data("A Covert Rescue"),
Data("PLACEHOLDER", valid=False),
Data("Top-Secret Mission"),
Data("PLACEHOLDER", valid=False),
Data("Scouting in Secret"),
Data("PLACEHOLDER", valid=False),
Data("Top-Secret Mission"),
Data("PLACEHOLDER", valid=False),
Data("A Question of Causes"),
Data("PLACEHOLDER", valid=False),
Data("Skell License"),
Data("PLACEHOLDER", valid=False),
Data("Top-Secret Mission"),
Data("PLACEHOLDER", valid=False),
Data("Flight Module"),
Data("PLACEHOLDER", valid=False),
Data("Partners in Prototyping"),
Data("PLACEHOLDER", valid=False),
Data("PLACEHOLDER", valid=False),
]
