from . import Loc as Data

# from helper
# flake8: noqa
segments_data: list[Data] = [
Data("Celica 5 H2H - Indu Dist: Test Hangar - Night", rules=["Celica 5"], depends=["Celica 4 H2H"]), 
Data("Nagi 2 H2H - Indu Dist: Test Hangar - Morning", rules=["Nagi 2"], depends=["Nagi 1 H2H"]), 
Data("The Gauntlet - Indu Dist: Test Hangar - Chp 12", rules=["Lvl 90"], depends=["Chapter 12", "A Present for Hope", "Haywire!", "An Ancient Legend", "Definian Love", "A Dish Served Cold", "The Lurker"]),
Data("Two Warriors - Indu Dist: Test Hangar - Night - Chp 11", rules=["Lvl 48"], depends=["Chapter 11", "A Challenger Approaches", "Welkin Levitath"]),
Data("Data Probe Challenge - Indu Dist: Test Hangar - Chp 8", rules=["Miranium 10"], depends=["Chapter 8", "The Probe-fessional"]),
Data("Good Fortun - Indu Dist: Central - Chp 10", rules=["Lvl 40"], depends=["Chapter 10", "Attack on Biahno Hills", "Rites of Ruin", "Alexs Last Stand"]),
Data("Celica 4 H2H - Indu Dist: Production Plant - Cat", rules=["Celica 4"], depends=["Celica 3 H2H", "Nine Lives"]),
Data("New in New LA - Indu Dist: Production Plant - Chp 9", rules=["Lvl 44"], depends=["Chapter 9", "Manhunt"]),
Data("Celica - Indu Dist: Production Plant", depends=["New in New LA"]),
Data("Yardleys Scheme - Indu Dist: Test Hangar - Chp 3", depends=["Chapter 3"]),
Data("Off the Record Biological - Indu Dist: Test Hangar - Chp 3", rules=["Blade License", "Biological 4", "Lvl 41"], depends=["Chapter 3"]), # not quite sure but dont think it needs the field skill lvls
Data("Boot Camp - Indu Dist: Test Hangar - Gwin 1 - Chp 10", rules=["Gwin 1", "Shop Boot Camp", "Lvl 46"], depends=["Chapter 10", "Nine Lives"]),
Data("Alien Wreckage 1 - Indu Dist: Test Hangar - Chp 8 - Archeological 2", rules=["Archeological 2"], depends=["Chapter 8"]),
Data("A Girls Wings - Indu Dist: Test Hangar - Chp 9", rules=["Skell License", "Lvl 27"], depends=["Chapter 9", "The Skell License"]), # depends flight module quest
Data("Muimuis Meltdown - Indu Dist: Central - Chp 9", rules=["Lvl 32"], depends=["Chapter 9", "Setting Forth"]),
Data("Turf War - Indu Dist: Central - Chp 10", rules=["Lvl 36", "Blood-Soaked Beast Fur"], depends=["Chapter 10", "Waste Not, Want Not"]),
Data("Doug 2 H2H - Indu Dist: Central - Morning", rules=["Doug 2"], depends=["Doug 1 H2H"]), 
Data("A Proper Chopper - Indu Dist: Central - Chp 4", rules=["Lvl 13"], depends=["Chapter 4"]),
Data("Murderess 3 H2H - Indu Dist: Production Plant", rules=["Murderess 3"], depends=["Murderess 2 H2H", "The Little Rich Girl"]), 
Data("Forest Foray - Indu Dist: Production Plant - Chp 3", rules=["Noct 15", "Phosphorus-Tree Seed"], depends=["Chapter 3"]),
Data("Pollution Solution - Indu Dist: Production Plant - Chp 7", rules=["FNet"], depends=["Chapter 7", "The Voltant Visionary", "Prone Sweet Prone"]),
Data("Good Neighbors - Indu Dist: Test Hangar - Chp 7", rules=["FNet Resource", "Lvl 30"], depends=["Chapter 7", "Circle of Life", "Lakeside Getaway", "Sunceleg Rises"]),
Data("Irina 4 H2H - Indu Dist: Test Hangar", rules=["Irina 4"], depends=["Irina 3 H2H", "The Skell License"]), 
Data("Lin 1 H2H - Indu Dist: Test Hangar - Night", rules=["Lin 1"], depends=["Lin"]), 
Data("Data Probe Breakthrough - Indu Dist: Test Hangar - Chp 11", rules=["Miranium 20"], depends=["Chapter 11", "Data Probe Progress"]),
Data("Data Probe Revolution - Indu Dist: Test Hangar - Chp 12", rules=["Miranium 40"], depends=["Chapter 12", "Data Probe Evolution"]),
Data("Elma 1 H2H - Indu Dist: Central - Afternoon", rules=["Elma 1"], depends=["Elma"]), 
Data("Lone Survivors - Indu Dist: Central - Chp 8", rules=["Lvl 30", "Summoning Goggles"], depends=["Chapter 8", "Circle of Life"]),
Data("Entrepreneurial Spirit - Indu Dist: Central - Chp 8", rules=["Credits 130"], depends=["Chapter 8", "The Root of All Evil", "Vainamo, the Bellower"]),
Data("Child of Mira - Indu Dist: Central - Chp 11", rules=["Lvl 39", "Gorkwa"], depends=["Chapter 11", "Pollution Solution", "Cavernous Abyss"]),
Data("Container 1 - Indu Dist: Production Plant - Mechanical 3", rules=["Mechanical 3"]),
Data("Orphean Pluck - Indu Dist: Production Plant - Chp 10", rules=["FNet"], depends=["Chapter 10", "No-show Nenceleg", "Planetary Pioneer IV"]),
Data("Data Probe Progress - Indu Dist: Production Plant - Chp 10", rules=["Miranium 15"], depends=["Chapter 10", "Data Probe Challenge"]),
Data("Data Probe Evolution - Indu Dist: Test Hangar - Chp 12", rules=["Miranium 30"], depends=["Chapter 12", "Data Probe Breakthrough"]),
Data("The Pip-Squeak - Indu Dist: Test Hangar - Chp 5", rules=["Frozen Pizza", "Hot Dog", "Hamburger", "Aganeba Alloy"], depends=["Chapter 5"]),
Data("Professorial - Indu Dist: Test Hangar - Chp 12", rules=["Lvl 43", "Gray Keycard"], depends=["Chapter 12", "Definian Downfall", "Professor Bs Return"]),
Data("Rise of the Blood Lobster - Indu Dist: Test Hangar - Chp 11", rules=["Skell License", "Flight Module", "Lvl 60", "Stuffed Lobster"], depends=["Chapter 3", "Definian Downfall"]),  # TAJ, MenuReset but too hard
Data("Mia 3 H2H - Indu Dist: Test Hangar - Late Night", rules=["Mia 3"], depends=["Mia 2 H2H"]), 
Data("Hope 3 H2H - Indu Dist: Central - Morning ", rules=["Hope 3"], depends=["Hope 2 H2H"]), 
Data("Pack It In - Indu Dist: Central - Chp 9", rules=["FNet Resource", "Lvl 36"], depends=["Chapter 9", "Dead Men Tell No Tales"]),
Data("Irina 1 H2H - Indu Dist: Central - Night", rules=["Irina 1"], depends=["Irina"]), 
Data("Frye 5 H2H - Indu Dist: Production Plant", rules=["Frye 5"], depends=["Frye 4 H2H"]), 
Data("Alexa - Indu Dist: Test Hangar", depends=["Chapter 1"]),
Data("Celica 1 H2H - Indu Dist: Test Hangar - Afternoon", rules=["Celica 1"], depends=["Celica"]), 
Data("Mystery Man - Indu Dist: Central - Chp 5", rules=["Lvl 18", "Tykki Sap"], depends=["Chapter 5"]),
Data("The Voltant Visionary - Indu Dist: Central - Chp 7", rules=["Lvl 29"], depends=["Chapter 7", "Dead Men Tell No Tales", "A Dubious Operation"]), # dubious operation maybe not required
Data("Horonalderon - Aff Shift - Indu Dist: Central - Chp 11", depends=["The Good Thief", "Tree-mendous", "Slovitys Revenge"]),
Data("Frye - Indu Dist: Repenta Diner", depends=["Bottoms Up"]),
Data("The Good Thief - Indu Dist: Repenta Diner - Chp 9", rules=["Lvl 34"], depends=["Chapter 9", "Dead Men Tell No Tales", "Water Woes"]), # you receive voltant only one route
Data("Fitting In - Aff Mission - Indu Dist: Test Hangar - Chp 11", rules=["Celica 3", "Lvl 46", "Aerozium"], depends=["Chapter 11", "BFFs", "New in New LA", "A Girls Wings", "Floating Reef"]),
Data("Professor Bs Return - Indu Dist: Central - Chp 7", rules=["Lvl 30"], depends=["Chapter 7", "Mystery Man", "Great Washington Isle"]),
Data("Gold Rush - Indu Dist: Central - Night - Chp 11", rules=["Lvl 50"], depends=["Chapter 11", "A Challenger Approaches", "The Celeste Three", "Law and Orders"]),
Data("Frye 1 H2H - Indu Dist: Repenta Diner - Late Night", rules=["Frye 1"], depends=["Frye"]), 
Data("Bottoms Up - Aff Mission - Night - Indu Dist: Repenta Diner - Chp 4", rules=["Lvl 19"], depends=["Chapter 4"]),
Data("Going Viral - Comm Dist: West Melville Street - Chp 7", rules=["Lvl 20"], depends=["Chapter 7", "Circle of Life"]),
Data("Gwin 5 H2H - Comm Dist: West Melville Street - Evening", rules=["Gwin 5"], depends=["Gwin 4 H2H"]), 
Data("Alien Nation - Comm Dist: West Melville Street - Chp 7", rules=["Lvl 33"], depends=["Chapter 7"]), # optional a concerned citizen
Data("Lin 2 H2H - Comm Dist: West Melville Street - Afternoon", rules=["Lin 2"], depends=["Lin 1 H2H"]), 
Data("Mia 4 H2H - Comm Dist: West Melville Street - Cat", rules=["Mia 4"], depends=["Mia 3 H2H", "Nine Lives"]), 
Data("Boze - Comm Dist: West Melville Street", depends=["Chapter 1"]),
Data("Celica 3 H2H - Comm Dist: West Melville Street - Morning", rules=["Celica 3"], depends=["Celica 2 H2H"]), 
Data("Container 2 - Comm Dist: West Melville Street - Mechanical 2", rules=["Mechanical 2"]),
Data("Stop, Thief! - Comm Dist: West Melville Street - Chp 9", rules=["Deep Blue Gem"], depends=["Chapter 9", "A Dubious Operation"]),
Data("A Dubious Operation - Comm Dist: West Melville Street - Chp 7", rules=["Lvl 32", "Hazardous Container", "Hazardous Fuel Cell", "Toxic Chemical Bomb"], depends=["Chapter 7", "Dead Men Tell No Tales"]),
Data("Mia 2 H2H - Comm Dist: West Melville Street - Late Night", rules=["Mia 2"], depends=["Mia 1 H2H"]), 
Data("Alien Wreckage 2 - Comm Dist: West Melville Street - Chp 8 - Archeological 4", rules=["Archeological 4"], depends=["Chapter 8"]),
Data("Phog 4 H2H - Comm Dist: Barista Court", rules=["Phog 4"], depends=["Phog 3 H2H", "A Great Divide"]),
Data("A Heros Ride - Comm Dist: Barista Court - Chp 2", depends=["Chapter 2"]),
Data("Better Latte Than Never - Comm Dist: West Melville Street - Day - Chp 2", depends=["Chapter 2"]),
Data("Doug 4 H2H - Comm Dist: West Melville Street", rules=["Doug 4"], depends=["Doug 3 H2H"]), 
Data("Quiquat - Aff Shift - Comm Dist: West Melville Street - Daytime", depends=["Starboard"]),  # just a guess
Data("Lin 4 H2H - Comm Dist: Barista Court - Evening", rules=["Lin 4"], depends=["Lin 3 H2H"]), 
Data("Emotion Commotion - Comm Dist: Barista Court - Chp 7", rules=["Lvl 30", "Bobbys Watch"], depends=["Chapter 7"]),
Data("The Matchmaker - Aff Mission - Comm Dist: Central Melville Street - Chp 6", rules=["Lao 1", "FNet", "Lvl 24"], depends=["Chapter 6"]),
Data("Definian Downfall - Comm Dist: Central Melville Street - Chp 11", rules=["Lvl 54", "First Barrier Key", "Second Barrier Key", "Third Barrier Key"], depends=["Chapter 11", "Professor Bs Return", "Good Fortun"]),
Data("Irina 5 H2H - Comm Dist: North Founder Street", rules=["Irina 5"], depends=["Irina 4 H2H"]), 
Data("Veverta - Aff Shift - Comm Dist: North Founder Street", depends=["Starboard"]),  # just a guess
Data("Nine Lives - Aff Mission - Comm Dist: Barista Court - Chp 5", rules=["Lvl 20"], depends=["Chapter 5"]),
Data("Renewed Will - Aff Mission - Comm Dist: Central Melville Street - Chp 3", rules=["Lvl 15"], depends=["Chapter 3"]),
Data("No Ma-non Need Apply - Comm Dist: Central Melville Street- Chp 5", depends=["Chapter 5", "Thats In-Credible!", "The Pip-Squeak"]),
Data("L 4 H2H - Comm Dist: North Founder Street", rules=["L 4"], depends=["L 3 H2H"]), 
Data("Nagi 3 H2H - Comm Dist: North Founder Street - Morning", rules=["Nagi 3"], depends=["Nagi 2 H2H"]), 
Data("Sparking a Smile - Comm Dist: Barista Court - Chp 8", rules=["Mira 40", "FNet", "Lvl 33", "Nopon Contract"], depends=["Chapter 8", "BFFs"]), # depends the Big Bang
Data("Unsatisfied Customer - Comm Dist: Barista Court - Chp 11", depends=["Chapter 11", "BFFs", "Floating Reef"]),
Data("The Fashionista - Comm Dist: Central Melville Street - Chp 6", rules=["Lvl 4"], depends=["Chapter 6"]),
Data("Planetary Pioneer III - Comm Dist: Central Melville Street - Chp 8", rules=["FNet", "Data Unit FN095"], depends=["Chapter 8", "FN Node 408", "Nectar Scirpo", "Planetary Pioneer II"]), # depends oblivia trailblazing 1/2/3
Data("Yelv - Comm Dist: North Founder Street", depends=["Chapter 1"]),
Data("The Sword of Legendaryness - Comm Dist: Central Melville Street - Chp 11", rules=["Sword of Legendaryness"], depends=["Chapter 11", "Bread and a Circus"]),
Data("Murderess 2 H2H - Comm Dist: North Founder Street - Nighttime", rules=["Murderess 2"], depends=["Murderess 1 H2H"]), 
Data("Serial Thriller - Aff Mission - Comm Dist: North Founder Street - Chp 12", rules=["Murderess 4", "Lvl 53"], depends=["Chapter 12", "A False Hope", "The Little Rich Girl"]),
Data("Frye 4 H2H - Comm Dist: East Melville Street", rules=["Frye 4"], depends=["Frye 3 H2H", "A Challenger Approaches"]), 
Data("My Angel, My Lana - Comm Dist: East Melville Street - Chp 10", rules=["Lvl 42"], depends=["Chapter 10", "BFFs"]),
Data("Alien Wreckage 3 - Comm Dist: East Melville Street - Chp 8 - Archeological 3", rules=["Archeological 3"], depends=["Chapter 8"]),
Data("Hope 5 H2H - Comm Dist: East Melville Street", rules=["Hope 5"], depends=["Hope 4 H2H", "Prone Sweet Prone", "Rescue at the Ensconced Citadel", "A False Hope"]), 
Data("Trade Agreement - Comm Dist: East Melville Street - Chp 7", rules=["Gold Nopopotamus Card"], depends=["Chapter 7", "Dead Men Tell No Tales", "Circle of Life", "Prone Sweet Prone"]),
Data("The Ties That Bind - Aff Mission - Comm Dist: East Melville Street - Chp 4", rules=["Lvl 15", "Dadapons Sunglasses"], depends=["Chapter 4"]),
Data("L 1 H2H - Comm Dist: East Melville Street - Afternoon", rules=["L 1"], depends=["L"]), 
Data("Beats - Aff Shift - Comm Dist: East Melville Street - Nighttime", depends=["The Art of War"]),
Data("Murder Most Foul - Comm Dist: East Melville Street - Chp 9", rules=["Lvl 35", "Grenade Pizza"], depends=["Chapter 9"]),
Data("Wrothian Innovation - Comm Dist: East Melville Street - Chp 10", rules=["Miranium 10", "Practice Data Probe"], depends=["Chapter 10", "A Challenger Approaches", "Orphean Pluck"]),
Data("Hope 2 H2H - Comm Dist: East Melville Street - Evening", rules=["Hope 2"], depends=["Hope 1 H2H"]), 
Data("A Dish Served Cold - Comm Dist: East Melville Street - Chp 11", rules=["Lvl 39", "Three Swords"], depends=["Chapter 11", "A Challenger Approaches"]),
Data("Elma 3 H2H - Comm Dist: East Melville Street - Morning", rules=["Elma 3"], depends=["Elma 2 H2H"]), 
Data("Forbidden Love - Ma-non Ship: Port Side - Chp 8", rules=["Lvl 38", "Ringstone"], depends=["Chapter 8", "Prone Sweet Prone"]),
Data("No-show Nenceleg - Ma-non Ship: Port Side - Chp 10", rules=["Lvl 35"], depends=["Chapter 10", "House Call"]),
Data("Gorkwa Games - Ma-non Ship: Port Side - Chp 7", rules=["Lvl 35", "Troylans Gorkwa", "Troylans Gorkwa Fake"], depends=["Chapter 7", "Dead Men Tell No Tales"]),
Data("House Call - Ma-non Ship: Port Side - Chp 10", rules= ["Lvl 35", "Lumenoa Leaf"], depends=["Chapter 10", "Circle of Life"]),
Data("A New Life - Ma-non Ship: Port Side - Chp 11", rules=["Obli 70", "Lvl 39"], depends=["Chapter 11", "Here Come the Brides", "Kintrees"]), # maybe Kintrees
Data("Here Come the Brides - Ma-non Ship: Port Side - Chp 9", rules=["Lvl 36"], depends=["Chapter 9", "Prone Sweet Prone"]),
Data("The Unbreakable Sword - Ma-non Ship: Port Side - Chp 12", rules=["FNet", "Lvl 39", "Unbreakable Sword"], depends=["Chapter 12", "A Challenger Approaches"]),
Data("A Grim Undertaking - Ma-non Ship: Port Side - Chp 6", rules=["Lvl 23", "Queggas Note", "Dancers Clothes"], depends=["Chapter 6", "Prone Sweet Prone"]),
Data("L 2 H2H - Ma-non Ship: Deck - Nighttime", rules=["L 2"], depends=["L 1 H2H", "Port Side"]), 
Data("The Lurker - Ma-non Ship: Deck - Chp 12", rules=["Lvl 36"], depends=["Chapter 12", "The Duel IV", "A Challenger Approaches"]),
Data("Snipe Hunt - Ma-non Ship: Deck - Chp 12", rules=["Lvl 50"], depends=["Chapter 12"]),
Data("Mia - Ma-non Ship: Deck", depends=["Mia Is Missing!"]),
Data("Sunceleg Rises - Ma-non Ship: Deck", rules=["Lvl 30"], depends=["Chapter 6", "Rescue at the Ensconced Citadel"]),
Data("Zurranik - Aff Shift - Ma-non Ship: Deck", depends=["Deck", "Gold Rush"]),
Data("The Membership - Ma-non Ship: Starboard - Chp 6", rules=["Miranium 10"], depends=["Chapter 6", "Planetary Pioneer III"]),
Data("Tree-mendous - Ma-non Ship: Starboard - Chp 5", rules=["Lvl 30", "Ajibas Key", "Mujibas Key"], depends=["Chapter 5", "Prone Sweet Prone"]), # depends Kidnapped: Uzoma Vassago, Kidnapped: Oll Valdileo, Kidnapped: Rada Valdileo
Data("Elma 4 H2H - Ma-non Ship: Starboard - Evening", rules=["Elma 4"], depends=["Elma 3 H2H", "Starboard"]), 
Data("The Old Gods - Ma-non Ship: Starboard - Chp 12", rules=["Lvl 55", "Zirtodiamond", "Golboggas Disk"], depends=["Chapter 12", "Dead Men Tell No Tales", "Slavebird Isle"]),
Data("An Ancient Legend - Ma-non Ship: Starboard - Chp 12", rules=["Lvl 39"], depends=["Chapter 12", "Slovitys Revenge"]),
Data("Training Day - Ma-non Ship: Starboard - Chp 7", rules=["Lvl 30"], depends=["Chapter 7", "Prone Sweet Prone"]),
Data("The Art of War - Ma-non Ship: Starboard - Chp 8", rules=["Lvl 34"], depends=["Chapter 8", "Prone Sweet Prone"]),
Data("Slovitys Revenge - Ma-non Ship: Starboard - Chp 11", rules=["Lvl 40"], depends=["Chapter 11", "Slovitys Rampage"]),
Data("The Party Line - Ma-non Ship: Starboard - Chp 12", rules=["Traditional Orphean Drug"], depends=["Chapter 12", "A Challenger Approaches", "BFFs", "Circle of Life", "Dead Men Tell No Tales", "Prone Sweet Prone"]),
Data("Phog 1 H2H - Resi Dist: Deliverance Park - Afternoon", rules=["Phog 1"], depends=["Phog"]), 
Data("Circle of Life - Resi Dist: Deliverance Park - Chp 7", rules=["Senirapa Water"], depends=["Chapter 7", "The Journey Begins", "Water Woes"]),
Data("Phog - Resi Dist: Deliverance Park", depends=["Foggy Dilemma"]),
Data("Lin 5 H2H - Resi Dist: Deliverance Park - Morning", rules=["Lin 5"], depends=["Lin 4 H2H", "Chapter 10", "A Girls Wings"]), 
Data("Off the Record Archeological - Resi Dist: Deliverance Park", rules=["Archeological 4", "Blade License"], depends=["Sentinels Nest", "Calore, the Lava Walker", "Land Forfex"]), # not quite sure but dont think it needs the field skill lvls
Data("Phog 3 H2H - Resi Dist: Sports Complex", rules=["Phog 3"], depends=["Phog 2 H2H"]), 
Data("Alien Wreckage 4 - Resi Dist: Sports Complex - Chp 8 - Archeological 4", rules=["Archeological 4"], depends=["Chapter 8"]),
Data("Gwin 2 H2H - Resi Dist: Sports Complex - Late Night", rules=["Gwin 2"], depends=["Gwin 1 H2H"]), 
Data("Herbivores, Unite! - Resi Dist: Deliverance Park - Chp 9", rules=["Noct 45", "Gnarlbranch Sap"], depends=["Chapter 9", "Prone Sweet Prone", "Circle of Life", "Divine Roost"]),
Data("A Present for Hope - Aff Mission - Resi Dist: Deliverance Park - Hope 4 - Chp 10", rules=["Hope 4", "Lvl 44", "Reverends Journal"], depends=["Chapter 10", "A False Hope"]),
Data("The Celeste Three - Resi Dist: Deliverance Park - Chp 5", rules=["Lvl 27", "White Gold Ore", "Briggss Key"], depends=["Chapter 5"]), # maybe Frosdykes/Moorehouses Key
Data("L 5 H2H - Resi Dist: Sports Complex - Early Morning", rules=["L 5"], depends=["L 4 H2H"]), 
Data("Celica 2 H2H - Resi Dist: Sports Complex - Morning", rules=["Celica 2"], depends=["Celica 1 H2H"]), 
Data("Doug 3 H2H - Resi Dist: Sports Complex - Daytime", rules=["Doug 3"], depends=["Doug 2 H2H"]), 
Data("Gwin 3 H2H - Resi Dist: Water Puri Plant - Late Night", rules=["Gwin 3"], depends=["Gwin 2 H2H"]), 
Data("Frye 3 H2H - Resi Dist: Water Purification Plant - Cat", rules=["Frye 3"], depends=["Frye 2 H2H", "A Great Divide", "Nine Lives"]), 
Data("The Line of Fire - Resi Dist: Deliverance Park - Chp 9", rules=["Lvl 40"], depends=["Chapter 9", "Shotgun Diplomacy"]),
Data("Hope - Resi Dist: Deliverance Park", depends=["Hope Springs Eternal"]),
Data("Planetary Pioneer V - Resi Dist: Deliverance Park - Chp 11", rules=["FNet", "Lvl 51", "Data Unit FN097"], depends=["Chapter 11", "FN Node 505", "Planetary Pioneer IV"]), # depends Cauldros Trailblazing 1/2/3
Data("Gwin 4 H2H - Resi Dist: Sports Complex - Dog", rules=["Gwin 4"], depends=["Gwin 3 H2H", "Nine Lives"]), 
Data("Mia 5 H2H - Resi Dist: Sports Complex", rules=["Mia 5"], depends=["Mia 4 H2H", "Mia Grows Up"]), 
Data("Hope 4 H2H - Resi Dist: Sports Complex - Dog", rules=["Hope 4"], depends=["Hope 3 H2H", "Nine Lives"]), 
Data("Phog 5 H2H - Resi Dist: Water Puri Plant", rules=["Phog 5"], depends=["Phog 4 H2H", "Blitzkrieg"]), 
Data("Foggy Dilemma - Aff Mission - Resi Dist: Water Puri Plant - Chp 4", rules=["Blade License", "Lvl 13"], depends=["Chapter 4"]),  # depends: Backup Request
Data("Murderess 1 H2H - Resi Dist: Cathedral - Afternoon", rules=["Murderess 1"], depends=["Murderess"]), 
Data("Murderess 4 H2H - Resi Dist: Deliverance Park - Cat", rules=["Murderess 4"], depends=["Murderess 3 H2H", "Nine Lives"]), 
Data("Alien Wreckage 5 - Resi Dist: Ishmael Hills - Chp 8 - Archeological 3", rules=["Archeological 3"], depends=["Chapter 8"]),
Data("Doug 1 H2H - Resi Dist: Ishmael Hills - Afternoon - Dog", rules=["Doug 1"], depends=["Doug", "Nine Lives"]), 
Data("Bread and a Circus - Resi Dist: Ishmael Hills - Chp 10", rules=["Slice of Bread"], depends=["Chapter 10", "Muimuis Meltdown"]),
Data("Elma 2 H2H - Resi Dist: Water Puri Plant - Night - Cat", rules=["Elma 2"], depends=["Elma 1 H2H", "Nine Lives"]), 
Data("New Frontier - Resi Dist: Cathedral - Chp 12", rules=["FNet", "Miranium 20", "Data Unit FN098"], depends=["Chapter 12", "Planetary Pioneer V", "Entrepreneurial Spirit", "Wrothian Innovation"]),
Data("Off the Record Mechanical - Resi Dist: Cathedral", rules=["Mechanical 4", "Blade License", "Lvl 55"], depends=["Lyla's Galdr", "Mount Edge Peak", "Savage Sketch"]), # not quite sure but dont think it needs the field skill lvls
Data("Mia 1 H2H - Resi Dist: Cathedral - Late Night", rules=["Mia 1"], depends=["Mia"]), 
Data("Caroline - Aff Shift - Resi Dist: Ishmael Hills - Daytime - Chp 7", depends=["Chapter 7", "Circle of Life"]),
Data("Alexs Last Stand - Resi Dist: Ishmael Hills - Chp 10", rules=["Lvl 43"], depends=["Chapter 10", "The Line of Fire"]),
Data("Phog 2 H2H - Resi Dist: Ishmael Hills - Cat", rules=["Phog 2"], depends=["Phog 1 H2H", "Nine Lives"]), 
Data("Konluarb - Aff Shift - Resi Dist: Ishmael Hills - Nighttime - Chp 7", depends=["Circle of Life"]),
Data("Lakeside Getaway - Resi Dist: Water Puri Plant - Chp 6", rules=["Lvl 22", "Ajoas ID Card", "Ians ID Card", "Keycard Lakeside Getaway"], depends=["Chapter 6", "Water Woes", "The Miracle Maker"]),
Data("Water Woes - Resi Dist: Water Puri Plant - Chp 5", rules=["FNet", "Lvl 20", "Sampling Bottle"], depends=["Chapter 5"]),
Data("Irina 2 H2H - Resi Dist: Cathedral - Evening - Dog", rules=["Irina 2"], depends=["Irina 1 H2H", "Nine Lives"]), 
Data("L 3 H2H - Resi Dist: Cathedral - Cat", rules=["L 3"], depends=["L 2 H2H", "Nine Lives"]), 
Data("Murderess 5 H2H - Resi Dist: Ishmael Hills", rules=["Murderess 5"], depends=["Murderess 4 H2H"]), 
Data("Wendy - Aff Shift - Resi Dist: Ishmael Hills - Daytime", depends=["Special Delivery"]),
Data("Nagi 5 H2H - Resi Dist: Ishmael Hills - Afternoon", rules=["Nagi 5"], depends=["Nagi 4 H2H"]), 
Data("H.B. - Resi Dist: Water Puri Plant", depends=["Chapter 1"]),
Data("Hope Springs Eternal - Aff Mission - Resi Dist: Cathedral - Chp 3", rules=["Blade License", "Lvl 21", "Natural Pearl"], depends=["Chapter 3"]),  # depends Marry Me!
Data("The Miracle Maker - Resi Dist: Cathedral - Chp 6", rules=["Malyteths Bottle"], depends=["Chapter 6", "Water Woes"]),
Data("The Divine Nopopon - Resi Dist: Ishmael Hills - Chp 12", rules=["Mira 80", "Lvl 68", "Nopon Gemstone"], depends=["Chapter 12", "BFFs"]),
Data("A Great Divide - Aff Mission - Resi Dist: Ishmael Hills - Phog 2 - Chp 7", rules=["Phog 2", "Lvl 30", "Massive Ring Fragment", "Butte Ruin Fragments", "North Coast Riddle Rock"], depends=["Chapter 7", "Bottoms Up", "Foggy Dilemma"]),
Data("The Bug Whisperer - Resi Dist: Ishmael Hills - Chp 10", rules=["Lvl 36"], depends=["Chapter 10", "Prone Sweet Prone", "Circle of Life", "BFFs"]),
Data("Shotgun Diplomacy - Resi Dist: Cathedral - Chp 8", rules=["Lvl 30"], depends=["Chapter 8", "Alien Nation"]),
Data("Letrick - Aff Shift - Resi Dist: Cathedral - Chp 7", depends=["Emotion Commotion"]),
Data("Rites of Ruin - Resi Dist: Cathedral - Chp 8", rules=["Lvl 30"], depends=["Chapter 8", "The Miracle Maker"]),
Data("Definian Love - Resi Dist: Ishmael Hills - Chp 12", rules=["Lvl 39"], depends=["Chapter 12", "Definian Downfall"]), # can be Fortun and Glory as well
Data("Phoskeran - Aff Shift - Resi Dist: Ishmael Hills", depends=["An Ancient Legend", "The Good Thief"]),
Data("Container 3 - Resi Dist: Cathedral - Mechanical 2", rules=["Mechanical 2"]),
Data("Trailer 1 - Resi Dist: Cathedral - Mechanical 3", rules=["Mechanical 3"]),
Data("A Fateful Choice - Resi Dist: Cathedral - Chp 12", rules=["Noct 85", "Runtonams Right Arm"], depends=["Chapter 12", "Circle of Life", "The Nopon Heir", "Divine Roost"]), # maybe lvl 99, arm might be optional
Data("The Journey Begins - Resi Dist: Cathedral - Chp 7", depends=["Chapter 7", "Sunceleg Rises"]),
Data("Hope 1 H2H - Resi Dist: Ishmael Hills - Afternoon", rules=["Hope 1"], depends=["Hope"]), 
Data("The Duel II - Admi Dist: BLADE Tower - Chp 11", rules=["Lvl 40"], depends=["Chapter 11", "The Duel I"]),
Data("Nagi - Admi Dist: BLADE Tower", depends=["Nagis Time"]),
Data("Cavern Crushers - Admi Dist: BLADE Tower - Chp 9", rules=["Lvl 35"], depends=["Chapter 9", "Prone Sweet Prone"]),
Data("Attack on Biahno Hills - Admi Dist: BLADE Tower - Chp 7", rules=["Lvl 31"], depends=["Chapter 7"]),
Data("Dead Men Tell No Tales - Admi Dist: BLADE Tower - Chp 7", rules=["Prim 50", "Lvl 28"], depends=["Chapter 7"]),
Data("Prone Sweet Prone - Admi Dist: BLADE Tower - Chp 5", rules=["Obli 40", "Internment Camp Key"], depends=["Chapter 5"]),
Data("Large Container - Admi Dist: BLADE Tower - Mechanical 4", rules=["Mechanical 4"]),
Data("Gwin 1 H2H - Admi Dist: Hangar - Afternoon", rules=["Gwin 1"], depends=["Gwin"]), 
Data("Irina 3 H2H - Admi Dist: Hangar - Morning", rules=["Irina 3"], depends=["Irina 2 H2H"]), 
Data("Doug - Admi Dist: Hangar - Chp 3", depends=["Chapter 3"]),
Data("Trailer 2 - Admi Dist: Armory Alley - Mechanical 2", rules=["Mechanical 2"]),
Data("Manhunt - Aff Mission - Admi Dist: BLADE Tower - Chp 8", rules=["Lvl 33"], depends=["Chapter 8"]),
Data("Spy Games - Aff Mission - Admi Dist: BLADE Tower - Chp 7", rules=["Lvl 28"], depends=["Chapter 7"]),
Data("Rescue at the Ensconced Citadel - Admi Dist: BLADE Tower - Chp 6", rules=["Noct 30", "Lvl 24"], depends=["Chapter 6"]),
Data("The Ultimate Price - Admi Dist: BLADE Tower - Chp 10", rules=["Lvl 38", "Crimson Tear"], depends=["Chapter 10", "Cavern Crushers"]),
Data("The Handy Ma-non - Admi Dist: Hangar - Chp 5", rules=["Lvl 21", "Windshield Glass"], depends=["Chapter 5"]),
Data("My Dream - Aff Mission - Admi Dist: Hangar - Chp 5", rules=["Lvl 22", "L-002 Experimental Plant"], depends=["Chapter 5"]),
Data("Cedric - Aff Shift - Admi Dist: Hangar - Nighttime - Chp 5", depends=["Tree-mendous", "A Day in the Life"]),
Data("The Nopon Heir - Aff Mission - Admi Dist: Armory Alley - L 4 - Chp 12", rules=["L 4", "Lvl 49", "Guardian Etherscale"], depends=["Chapter 12", "BFFs", "A Girls Wings", "Ls Conundrum", "Divine Roost"]),
Data("L - Admi Dist: Armory Alley - Chp 4", depends=["Chapter 4"]),
Data("Thats In-Credible! - Admi Dist: BLADE Tower - Chp 5", rules=["Lvl 23", "Quest Thats Incredible"], depends=["Chapter 5"]),
Data("Reporting for Duty - Aff Mission - Admi Dist: BLADE Tower - Nagi 3 - Chp 10", rules=["Nagi 3", "Lvl 41"], depends=["Chapter 10", "Nagis Time"]),
Data("A False Hope - Aff Mission - Admi Dist: BLADE Tower - Hope 2 - Chp 5", rules=["Hope 2", "Lvl 24"], depends=["Chapter 5", "Hope Springs Eternal"]),
Data("Planetary Pioneer II - Admi Dist: BLADE Tower - Chp 5", rules=["FNet", "Data Unit FN094"], depends=["Chapter 5", "Planetary Pioneer I"]), # depends Noctilum Trailblazing 1/2/3
Data("Nopopon - Aff Shift - Admi Dist: BLADE Tower - Chp 12", depends=["The Divine Nopopon"]),
Data("Mamma Mia! - Admi Dist: Hangar - Chp 3", rules=["Shop Mia"], depends=["Chapter 3"]),
Data("Mia Grows Up - Aff Mission - Admi Dist: Hangar - Mia 4 - Chp 12", rules=["Mia 4", "FNet", "Lvl 53", "Floatstone Shard"], depends=["Chapter 12", "Sparking a Smile", "Mia Is Missing!", "Floating Reef"]), # optional Hailing the Chief!
Data("Brotherly Love - Aff Mission - Admi Dist: Hangar - Phog 4 Frye 4 - Chp 11", rules=["Phog 4", "Frye 4", "Lvl 46", "Phogrium"], depends=["Chapter 11"]),
Data("Doug 5 H2H - Admi Dist: Hangar", rules=["Doug 5"], depends=["Doug 4 H2H", "Chapter 12"]), 
Data("Ls Conundrum - Aff Mission - Admi Dist: Armory Alley - L 2 - Chp 10", rules=["L 2", "FNet Resource", "Lvl 38"], depends=["Chapter 10", "Booming Business"]), # depends Material Hunt A/B/C
Data("Booming Business - Admi Dist: Armory Alley - Chp 5", rules=["Obli 30", "Lvl 26"], depends=["Chapter 5"]),
Data("Lend an Ear - Admi Dist: BLADE Tower - Chp 11", rules=["Shop Lend an Ear", "Lvl 38"], depends=["Chapter 11", "A Challenger Approaches"]),
Data("Setting Forth - Admi Dist: Mimeo Maint Center - Chp 8", rules=["Lvl 31", "Smelly Legen-dar", "Legen-dar"], depends=["Chapter 8", "BFFs"]),
Data("Nagi 1 H2H - Admi Dist: Mimeo Maint Center - Afternoon", rules=["Nagi 1"], depends=["Nagi"]), 
Data("Planetary Pioneer IV - Admi Dist: Division Drive - Chp 8", rules=["FNet", "Lvl 25", "Data Unit FN096"], depends=["Chapter 8", "FN Node 408", "Planetary Pioneer III"]), # depends Sylvalum Trailblazing 1/2/3
Data("Waste Not, Want Not - Admi Dist: Hangar - Chp 10", rules=["Cockpit Wreckage", "Engine Wreckage", "Zu Pharg Wreckage"], depends=["Chapter 10"]),
Data("The Skell License - Admi Dist: Hangar - Chp 6", rules=["Credits 15", "Quest Skell License", "Skell License Certificate"], depends=["Chapter 6", "FN Node 117", "Shatskikh, the Flash"]), # depends Proficiency Exam 1-8. only 1 of 3 quests. truncated subquests to not need depends
Data("Frye 2 H2H - Admi Dist: Hangar - Nighttime", rules=["Frye 2"], depends=["Frye 1 H2H"]), 
Data("House of Cards - Admi Dist: Armory Alley - Chp 5", rules=["Keycard House of Cards"], depends=["Chapter 5", "Yardleys Scheme"]),
Data("White Lifehold - Admi Dist: Armory Alley - Chp 11", rules=["Lvl 41", "Communication Data"], depends=["Chapter 11", "Waste Not, Want Not"]),
Data("BLADE Level Basics - Admi Dist: BLADE Concourse - Chp 3", rules=["Blade License"], depends=["Chapter 3"]),
Data("Soldier of the Harriers - Aff Mission - Admi Dist: Mimeo Maint Center - Doug 3 - Chp 7", rules=["Doug 3", "Lvl 30"], depends=["Chapter 7", "Close Comrades"]),
Data("The Probe-fessional - Admi Dist: Mimeo Maint Center - Chp 2", rules=["Quest Probe-fessional"], depends=["Chapter 2"]),
Data("The Duel III - Admi Dist: Mimeo Maint Center - Chp 11", rules=["Lvl 42"], depends=["Chapter 11", "The Duel II", "Prone Sweet Prone"]),
Data("The Little Rich Girl - Aff Mission - Admi Dist: Division Drive - Murderess 2 - Chp 10", rules=["Murderess 2", "Lvl 39"], depends=["Chapter 10", "Haywire!", "My Dream"]), # depends Hackers, Securing Lan'cord
Data("Lao - Admi Dist: Division Drive - Chp 4", depends=["Chapter 4"]),
Data("Gwin - Admi Dist: Division Drive - Chp 3", depends=["Chapter 3"]),
Data("City Saviors - Admi Dist: Division Drive - Chp 3", rules=["Prim 15", "Lvl 8"], depends=["Chapter 3"]),
Data("Close Comrades - Aff Mission - Admi Dist: BLADE Barracks - Chp 4", rules=["Lvl 20"], depends=["Chapter 4"]),
Data("Planetary Pioneer I - Admi Dist: BLADE Concourse - Chp 3", rules=["FNet", "Lvl 8", "Data Unit FN093"], depends=["Chapter 3", "The Probe-fessional"]), # depends Primordia Trailblazing 1/2/3
Data("Wolf - Aff Shift - Admi Dist: BLADE Concourse - Chp 12", depends=["Snipe Hunt"]),
Data("Ovah and Out - Admi Dist: Mimeo Maint Center - Chp 7", rules=["Shop Ovah and Out", "Lvl 20"], depends=["Chapter 7", "Circle of Life", "Going Viral"]),
Data("Cooking Schooled - Admi Dist: Mimeo Maint Center - Chp 12", rules=["Shop Cooking Schooled", "Lvl 42"], depends=["Chapter 12", "Lionhearted"]),
Data("Mia Is Missing! - Admi Dist: Mimeo Maint Center - Chp 11", rules=["Caul 65", "Lvl 50", "Container Key"], depends=["Chapter 11", "Its-a Mia!", "Definian Downfall"]),
Data("Unknown Assailant - Admi Dist: Division Drive - Chp 10", rules=["Lvl 37"], depends=["Chapter 10", "Frontier Spirit"]),
Data("Frontier Spirit - Admi Dist: Division Drive - Chp 6", rules=["Lvl 22"], depends=["Chapter 6"]),
Data("Lin 3 H2H - Admi Dist: Division Drive - Afternoon - Dog", rules=["Lin 3"], depends=["Lin 2 H2H", "Nine Lives"]), 
Data("Close Encounters - Admi Dist: BLADE Barracks - Chp 6", rules=["FNet", "Lvl 28"], depends=["Chapter 6"]),
Data("The Root of All Evil - Admi Dist: BLADE Barracks", rules=["Credits 70"], depends=["Planetary Pioneer IV"]),
Data("Irina - Admi Dist: BLADE Concourse - Chp 3", depends=["Chapter 3"]),
Data("Murderess - Admi Dist: Mimeo Maint Center", depends=["My Dream"]),
Data("Myles to Go - Admi Dist: East Gate - Chp 2", rules=["Lvl 9", "Repair Kit"], depends=["Chapter 2"]),
Data("Slovitys Rampage - Admi Dist: East Gate - Chp 10", rules=["Lvl 37"], depends=["Chapter 10", "Cavern Crushers"]),
Data("Blitzkrieg - Aff Mission - Admi Dist: East Gate - Phog 3 Frye 3 - Chp 8", rules=["Phog 3", "Frye 3", "Lvl 33"], depends=["Chapter 8", "A Great Divide", "Bottoms Up", "Nine Lives"]),
Data("Caesar, the Hundred-Eyed - Prim: Stonelattice Cavern - Tyrant", depends=["Caesar, the Hundred-Eyed", "Stonelattice Cavern"]),
Data("Snipe Hunt - Prim: Bedrock Hold", depends=["Snipe Hunt"]),
Data("Skell Wreckage 1 - Prim: Bedrock Hold - Mechanical 1", rules=["Mechanical 1"]),
Data("Alien Container 1 - Prim: Bedrock Hold - Archeological 5", rules=["Archeological 5"]),
Data("Skell Wreckage 2 - Prim: Headwater Summit - Mechanical 1", rules=["Mechanical 1"]),
Data("Celestin, the Spring Storm - Prim: Headwater Summit - Tyrant", depends=["Celestin, the Spring Storm"]),
Data("The Repair Job - Prim: Starfall Basin", depends=["The Repair Job"]),
Data("The Queen Is Dead - Prim: Stickstone Rise - Chp 11", rules=["Lvl 45"], depends=["Chapter 11", "A Challenger Approaches"]),
Data("Strange Insect Nest - Prim: Greater Gemini Bridge - Biological 1", rules=["Biological 1"]),
Data("Zdenka, the Raucous - Prim: Fallshorn Isle - Tyrant", depends=["Zdenka, the Raucous"]),
Data("White Whale Debris 1 - Prim: Headwater Summit - Mechanical 1", rules=["Mechanical 1"]),
Data("Vehicle Wreckage 1 - Prim: Shadow Rise - Mechanical 1", rules=["Mechanical 1"]),
Data("Sapara, the Laconic - Prim: Unicorn Rock - Tyrant - Rarely", depends=["Sapara, the Laconic"]),
Data("A Day in the Life - Prim: Biahno Grassland", depends=["A Day in the Life"]),
Data("Haywire! - Prim: Water Puri Plant - Chp 9", rules=["Lvl 31"], depends=["Chapter 9", "Good Neighbors"]),
Data("White Whale Debris 2 - Prim: Biahno Lake - Mechanical 1", rules=["Mechanical 1"]),
Data("Forbidden Love - Prim: Shadow Beach", depends=["Forbidden Love"]),
Data("Bohdan, the Mistral - Prim: Unicorn Rock - Tyrant - Daytime", depends=["Bohdan, the Mistral"]),  # TAJ, MenuReset from TalonRock
Data("Skell Wreckage 3 - Prim: Plundered Ruins - Mechanical 2", rules=["Mechanical 2"]),
Data("Cinicula Assault - Prim: Grieving Plains - Chp 2", rules=["Lvl 8"], depends=["Chapter 2", "Welcome Back, Conner"]),
Data("Renewed Will - Prim: Grieving Plains", depends=["Renewed Will"]),
Data("Casper, the Unhealthy Eater - Prim: West Gate Plain - Tyrant - Nighttime", depends=["Casper, the Unhealthy Eater"]),
Data("White Whale Debris 3 - Prim: Talon Rock - Mechanical 5", rules=["Mechanical 5"], depends=["Talon Rock Summit"]),
Data("The Lurker - Prim: Talon Rock Second Terrane", depends=["The Lurker"]),
Data("Eckart, the Indestructible - Prim: Grieving Plains - Tyrant", depends=["Eckart, the Indestructible"]),
Data("Ridill, the Arrogant - Prim: Northpointe Beach - Tyrant - Rarely", depends=["Ridill, the Arrogant"]),
Data("Necro, the Cavelord - Prim: Drop Shaft - Tyrant", depends=["Necro, the Cavelord"]),
Data("Experimental Composite Qmoeva - Prim: Talon Rock - Tyrant - Nighttime", depends=["Experimental Composite Qmoeva"]),
Data("City Saviors - Prim: Sayram Lake", depends=["City Saviors"]),
Data("Alien Wreckage 6 - Prim: Drop Shaft - Archeological 4", rules=["Archeological 4"]),
Data("White Whale Debris 4 - Prim: Talon Rock Second Terrane - Mechanical 1", rules=["Mechanical 1"]),
Data("Dieter, the Epicure - Prim: Talon Rock Second Terrane - Tyrant", depends=["Dieter, the Epicure"]),
Data("Daril, the Eradicator - Prim: Castaway Cavern - Tyrant - Nighttime", depends=["Daril, the Eradicator"]),
Data("Patrol Chopper Wreckage 1 - Prim: Arendt Bridge - Mechanical 1", rules=["Mechanical 1"]),
Data("The Good Thief - Prim: Northpointe Beach", depends=["The Good Thief"]),
Data("White Whale Debris 5 - Prim: Northpointe Beach - Mechanical 3", rules=["Mechanical 3"]),
Data("Mesgen, the Fairweathered - Prim: Sayram Lake - Tyrant", depends=["Mesgen, the Fairweathered"]),
Data("Close Encounters - Prim: Arendt Brdige", depends=["Close Encounters"]),
Data("Nagis Time - Prim: Northpointe Beach", depends=["Nagis Time"]),
Data("Shatskikh, the Flash - Prim: Northpointe Cove - Tyrant - Rarely", depends=["Shatskikh, the Flash"]),
Data("Welcome Back, Conner - Prim: Sayram Northeast Plain - Chp 2", rules=["Conners Comm Device"], depends=["Chapter 2"]),
Data("Here Come the Brides - Prim: Sickle Rock Rise", depends=["Here Come the Brides"]),
Data("Alien Wreckage 7 - Prim: Sickle Rock Rise - Archeological 2", rules=["Archeological 2"]),
Data("Vehicle Wreckage 2 - Prim: East Gate Plain - Mechanical 1", rules=["Mechanical 1"]),
Data("An Ancient Legend - Prim: East Gate Plain", depends=["An Ancient Legend"]),
Data("We Were Soldiers - Prim: Northpointe Cove", depends=["We Were Soldiers"]),
Data("White Whale Debris 6 - Prim: Northpointe Cove - Mechanical 2", rules=["Mechanical 2"]),
Data("Etutanne, the Bloodthirsty - Prim: Silent Mire - Tyrant", depends=["Etutanne, the Bloodthirsty"]),
Data("Hephaestus, the Absconder - Prim: East Gate Plain - Tyrant - Nighttime", depends=["Hephaestus, the Absconder"]),
Data("White Whale Debris 7 - Prim: Tallpack Peak - Mechanical 1", rules=["Mechanical 1"]),
Data("Nine Lives - Prim: East Gate Plain", depends=["Nine Lives"]),
Data("Alien Wreckage 8 - Prim: Seaswept Rise - Archeological 4", rules=["Archeological 4"]),
Data("White Whale Debris 8 - Prim: North Janpath Plain - Mechanical 4", rules=["Mechanical 4"]),
Data("Gugli, the Relentless - Prim: Janpath Lake - Tyrant", depends=["Gugli, the Relentless"]),
Data("Luciel, the Eternal - Prim: Janpath Lake - Tyrant", depends=["Luciel, the Eternal"]),
Data("Eutropio, the Sea Rumble - Prim: Seaswept Ridge - Tyrant", depends=["Eutropio, the Sea Rumble"]),
Data("A Dubious Operation - Prim: Seaswept Ridge", depends=["A Dubious Operation"]),
Data("Muimuis Meltdown - Prim: North Janpath Plain", depends=["Muimuis Meltdown"]),
Data("Training Day - Prim: Janpath Lake", depends=["Training Day"]),
Data("A False Hope - Prim: South Janpath Plain", depends=["A False Hope"]),
Data("Bogdan, the Dense - Prim: Seaswept Base - Tyrant", depends=["Bogdan, the Dense"]),
Data("Alien Wreckage 9 - Prim: North Janpath Plain - Archeological 3", rules=["Archeological 3"]),
Data("Stop, Thief! - Prim: East Janpath Plain", depends=["Stop, Thief!"]),
Data("Ji-ett, the Thunderclap - Prim:  - Tyrant - Nighttime", depends=["Ji-ett, the Thunderclap"]),  #TAJ heavy skells might be not enough
Data("Rajidi, the Cumuliform - Prim: Grieving Plains - Tyrant - Rarely", depends=["Rajidi, the Cumuliform"]),  # TAJ to aggro
Data("Patrol Chopper Wreckage 2 - Prim: West Gate Plains - Mechanical 4", rules=["Mechanical 4"]),
Data("Strange Tree 1 - Noct: Narcissus Tree - Biological 5", rules=["Biological 5"]),
Data("Skell Wreckage 4 - Noct: Sato Headwater - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),
Data("A Fateful Choice - Noct: Divine Roost", depends=["A Fateful Choice"]),
Data("The Nopon Heir - Noct: Divine Roost", depends=["The Nopon Heir"]),
Data("Planetes, the Torrential - Noct: Divine Roost - Tyrant", depends=["Planetes, the Torrential"]),
Data("House Call - Noct: Upper Hush Flood", depends=["House Call"]),
Data("Pyotr, the Shepherd - Noct: Upper Hush Flood  - Tyrant", depends=["Pyotr, the Shepherd"]),
Data("Prospective Partners - Noct: Middle Hush Flood", depends=["Prospective Partners"]),
Data("Strange Tree 2 - Noct: Middle Hush Flood - Biological 4", rules=["Biological 4"], depends=["Chapter 3"]),
Data("Frontier Spirit - Noct: Everwhelm Falls", depends=["Frontier Spirit"]),
Data("Froste, the Courteous - Noct: Vitriol Cesspool - Tyrant", depends=["Froste, the Courteous"]),
Data("Telethia, the Endbringer - Noct: Divine Roost - Tyrant", depends=["Chapter 12", "Telethia, the Endbringer"]),  # TAJ
Data("Joker, the Unknowable - Noct: Divine Roost - Tyrant", depends=["Joker, the Unknowable"]), # TAJ
Data("Frajeel, the Purgatorial - Noct: Divine Roost - Tyrant", depends=["Frajeel, the Purgatorial"]),
Data("The Art of War - Noct: Lotus Keep Building Site", depends=["The Art of War"]),
Data("Rescue at the Ensconced Citadel - Noct: Ensconced Citadel", depends=["Rescue at the Ensconced Citadel"]),
Data("My Dream - Noct: Middle Hushflood", depends=["My Dream"]),
Data("Katerina, the Cliffhanger - Noct: Everwhelm Falls - Tyrant", depends=["Katerina, the Cliffhanger"]),
Data("Schneider, the Cliffpercher - Noct: Everwhelm Falls - Tyrant", depends=["Schneider, the Cliffpercher"]),
Data("The Voltant Visionary - Noct: Serpentine Pass", depends=["The Voltant Visionary"]),
Data("Patrol Chopper Wreckage 3 - Noct: Divie Roost - Mechanical 4", rules=["Mechanical 4"], depends=["Divine Roost"]),
Data("Circle of Life - Noct: Dead Mans Ingress", depends=["Circle of Life"]),
Data("Vehicle Wreckage 3 - Noct: Bloodpond Basin - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("No-show Nenceleg - Noct: Qing Long Glade", depends=["No-show Nenceleg"]),
Data("Trailer Wreckage 1 - Noct: Qing Long Glade - Mechanical 1", rules=["Mechanical 1"], depends=["Chapter 3"]),
Data("Dodonga Caravan - Noct: Cascade Isle", rules=["Lvl 22"], depends=["Chapter 5", "The Ties That Bind"]),
Data("Manhunt - Noct: Dead Mens Ingress", depends=["Manhunt"]),
Data("Demetrio, the Tempestuous - Noct: Ensconced Citadel - Tyrant", depends=["Demetrio, the Tempestuous"]),
Data("Alien Wreckage 10 - Noct: Qing Long Glade - Archeological 2", rules=["Archeological 2"], depends=["Chapter 3"]),  # from Branches atop
Data("Close Comrades - Noct: Qing Long Glade", depends=["Close Comrades"]),
Data("A Proper Chopper - Noct: Sunlit Spring", depends=["A Proper Chopper"]),
Data("Dead Men Tell No Tales - Noct: Millstone Ridge", depends=["Dead Men Tell No Tales"]),
Data("Murder Most Foul - Noct: Weeping Whitewood", depends=["Murder Most Foul"]),
Data("Elena, the Infernal - Noct: Weeping Whitewood - Tyrant - Fog", depends=["Elena, the Infernal"]),
Data("Griffus, the Tartarean - Noct: Fukai Pass - Tyrant", depends=["Griffus, the Tartarean"]),
Data("Adventure! - Noct: Skybound Coil Tree - Chp 5", rules=["Lvl 22", "Mias Comm Device"], depends=["Chapter 5", "Mamma Mia!"]),
Data("Tormenta, the Scarlet-Clad - Noct: Decapotamon - Tyrant", depends=["Tormenta, the Scarlet-Clad"]),
Data("Lone Survivors - Noct: Seabound Coil Tree", depends=["Lone Survivors"]),
Data("Sarcosuchus, the Iron-Eater - Noct: Rust Lake - Tyrant", depends=["Sarcosuchus, the Iron-Eater"]),
Data("Strange Tree 3 - Noct: Old Dragontail Tree - Biological 1", rules=["Biological 1"], depends=["Chapter 3"]),
Data("White Whale Debris 9 - Noct: Fukai Pass - Mechanical 4", rules=["Mechanical 4", "Skell License"], depends=["Chapter 3"]),
Data("Skell Wreckage 5 - Noct: Rockmoles Burrow - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("The Duel II - Noct: Decapotamon", depends=["The Duel II"]),
Data("Clemente, the Iron Meteor - Noct: Nopon Braidbridge - Tyrant", depends=["Clemente, the Iron Meteor"]),
Data("Patrol Chopper Wreckage 4 - Noct: Canopied Nightwood - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),  # maybe should require skell, because probably the most difficult one in the game, advanced jump / menu reset
Data("Skell Wreckage 6 - Noct: Tripod Rock - Mechanical 1", rules=["Mechanical 1"], depends=["Chapter 3"]),
Data("Missing in Action - Noct: Whales Nostril - Chp 5", depends=["Chapter 5", "BFFs"]),
Data("Desdemona, the Subterranean - Noct: Rustpool Banks - Tyrant", depends=["Desdemona, the Subterranean"]),
Data("Buchwald, the Guardian - Noct: Rockmoles Burrow - Tyrant", depends=["Buchwald, the Guardian"]),
Data("Skell Wreckage 7 - Noct: Ensanguined Font - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),
Data("Alien Container 2 - Noct: Lakeview Stronghold - Archeological 4", rules=["Archeological 4"], depends=["Chapter 3"]),
Data("Data Miner - Noct: Potters Rock - Chp 3", rules=["Weapon Test Data"], depends=["Chapter 3"]),
Data("White Whale Debris 10 - Obli: Oblivia Ingress - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("Melanya, the Sound Sleeper - Obli: Oblivia Ingress - Tyrant", depends=["Melanya, the Sound Sleeper"]),
Data("Sunceleg Rises - Obli: Stoyanov Trail", depends=["Sunceleg Rises"]),
Data("Gotthard, the Intimidating - Obli: Yawning Giant - Tyrant", depends=["Gotthard, the Intimidating"]),
Data("Skell Wreckage 8 - Obli: Stoyanov Trail - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),
Data("Indigen Nest 1 - Obli: Big Arch - Biological 4", rules=["Biological 4"], depends=["Chapter 3"]),
Data("Germaine, the Treasure Keeper - Obli: Eddies Conquest - Tyrant", depends=["Germaine, the Treasure Keeper"]),
Data("Vehicle Wreckage 4 - Obli: Twin Arches - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),
Data("Alien Wreckage 11 - Obli: Mesa Fortress - Archeological 2", rules=["Archeological 2"], depends=["Chapter 3"]),
Data("Vendura, the Spellbinder - Obli: Mesa Fortress - Tyrant - Daytime", depends=["Vendura, the Spellbinder"]),
Data("Libra, the Long-Lived - Obli: North Coast - Tyrant", depends=["Libra, the Long-Lived"]),
Data("Jindriska, the Serene - Obli: Twin Arches - Tyrant", depends=["Jindriska, the Serene"]),
Data("Barnabas, the Despot - Obli: Cliffside Camp - Tyrant - Daytime", depends=["Barnabas, the Despot"]),
Data("A Dish Served Cold - Obli: Yawning Giant", depends=["A Dish Served Cold"]),
Data("Indigen Nest 2 - Obli: Yawning Giant - Biological 2", rules=["Biological 2"], depends=["Chapter 3"]),
Data("Prone Sweet Prone - Obli: Scabland Fortress", depends=["Prone Sweet Prone"]),
Data("Edgardo, the Carefree - Obli: North Coast - Tyrant", depends=["Edgardo, the Carefree"]),
Data("Skell Wreckage 9 - Obli: Big Arch - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("Squallo, the Sand Mirer - Obli: Aaroy Plain - Tyrant - Daytime", depends=["Squallo, the Sand Mirer"]),
Data("White Whale Debris 11 - Obli: Aaroy Plain - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),
Data("Foggy Dilemma - Obli: Aaroy Plain", depends=["Foggy Dilemma"]),
Data("Skell Wreckage 10 - Obli: Scabland Fortress - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("Ro-darm, the Demon Claw - Obli: North Coast - Tyrant", depends=["Ro-darm, the Demon Claw"]),
Data("Slovitys Rampage - Obli: Milligan Supply Base", depends=["Slovitys Rampage"]),
Data("Mayday - Obli: Aaroy Plain - Chp 2", rules=["Lvl 12"], depends=["Chapter 2"]),
Data("Skell Wreckage 11 - Obli: Aaroy Plain - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),
Data("Hartmut, the Calamity - Obli: Yawning Giant - Tyrant", depends=["Hartmut, the Calamity"]),
Data("Valeriano, the Rolling Thunder - Obli: Leaning Ring - Tyrant - Electromagnetic storm", depends=["Valeriano, the Rolling Thunder"]),
Data("A Friend in Need - Obli: Rooney Cavern", depends=["A Friend in Need"]),
Data("White Whale Debris 12 - Obli: Milligan Supply Base - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("Skell Wreckage 12 - Obli: Milligan Supply Base - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("Ernest, the Contemplative - Obli: King Falls - Tyrant", depends=["Ernest, the Contemplative"]),
Data("Celedonio, the Battle-Tested - Obli: Keegan Ridge - Tyrant", depends=["Celedonio, the Battle-Tested"]),
Data("Indigen Dung 1 - Obli: Aaroy Plain - Biological 2", rules=["Biological 2"], depends=["Chapter 3"]),
Data("Vittorio, the Battle-Scarred - Obli: Barbarich Desert - Tyrant", depends=["Vittorio, the Battle-Scarred"]),
Data("White Whale Debris 13 - Obli: Barbarich Desert - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),
Data("Mighty Mia - Obli: Leaning Ring - Chp 6", rules=["Lvl 29"], depends=["Chapter 6", "Adventure!"]),
Data("Trailer Wreckage 2 - Obli: Ejiri Promontory - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),
Data("The Duel I - Obli: Ruins on the Sandbank", rules=["Lvl 35"], depends=["Chapter 9", "A Challenger Approaches"]),
Data("Rolf, the Sonorous - Obli: King Falls - Tyrant", depends=["Rolf, the Sonorous"]),
Data("Ludvik, the Picky Eater - Obli: Keegan Ridge - Tyrant - Daytime", depends=["Ludvik, the Picky Eater"]),
Data("A Grim Undertaking - Obli: Barbarich Desert", depends=["A Grim Undertaking"]),
Data("Skell Wreckage 13 - Obli: Drowning Ring - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("The Little Rich Girl - Obli: Lake Basel", depends=["The Little Rich Girl"]),
Data("Elaine, the Lunar Eclipse - Obli: Lake Basel - Tyrant - Nighttime", depends=["Elaine, the Lunar Eclipse"]),
Data("A Challenger Approaches - Obli: Wrothian Stronghold", depends=["A Challenger Approaches"]),
Data("White Whale Debris 14 - Obli: Keegan Ridge - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("Then and Now - Obli: Keegan Ridge", depends=["Then and Now"]),
Data("Eliane, the Unmoved - Obli: Barbarich Desert - Tyrant", depends=["Eliane, the Unmoved"]),
Data("Sviatoslav, the Reproachful - Obli: Balance Rock - Tyrant - Rain", depends=["Sviatoslav, the Reproachful"]),
Data("A Great Divide - Obli: South Coast", depends=["A Great Divide"]),
Data("Skell Wreckage 14 - Obli: Lake Basel - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("Ferdinand, the Fortuitous - Obli: Lake Basel - Tyrant", depends=["Ferdinand, the Fortuitous"]),
Data("Indigen Nest 3 - Obli: Mount Edge Peak - Biological 4", rules=["Biological 4"], depends=["Mount Edge Peak"]),
Data("Bread and a Circus - Obli: Beehive Rock", depends=["Bread and a Circus"]),
Data("Climati, the Chilling Wind - Obli: Central Ibra Ravine - Tyrant", depends=["Climati, the Chilling Wind"]),
Data("Indigen Nest 4 - Obli: Giant Ring - Biological 5", rules=["Biological 5"], depends=["Atop the Giant Ring"]),
Data("Shotgun Diplomacy - Obli: Balance Rock", depends=["Shotgun Diplomacy"]),
Data("Silvestre, the Morning Light - Obli: South Coast - Tyrant", depends=["Silvestre, the Morning Light"]),
Data("White Whale Debris 15 - Obli: Lake Basel - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("Dorian Caravan - Obli: Lake Basel", rules=["Lvl 22"], depends=["Chapter 5", "The Ties That Bind"]),
Data("Vehicle Wreckage 5 - Obli: Lake Basel - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("Indigen Dung 2 - Obli: Victory Rock - Biological 3", rules=["Biological 3"], depends=["Chapter 3"]),
Data("Feliciano, the All-Seeing - Obli: Central Ibra Ravine - Tyrant - Daytime", depends=["Feliciano, the All-Seeing"]),
Data("Vehicle Wreckage 6 - Obli: Balance Rock - Mechanical 3", rules=["Mechanical 3"], depends=["Chapter 3"]),
Data("Skell Wreckage 15 - Obli: South Coast - Mechanical 3", rules=["Mechanical 3"], depends=["Chapter 3"]),
Data("Skell Wreckage 16 - Obli: Washington Isle - Mechanical 4", rules=["Mechanical 4"], depends=["Great Washington Isle"]),
Data("Vilem, the Gold-Scaled - Obli: Lake Basel - Tyrant", depends=["Vilem, the Gold-Scaled"]),
Data("White Whale Debris 16 - Obli: Sea Whisper Valley - Mechanical 3", rules=["Mechanical 3"], depends=["Chapter 3"]),
Data("Bertrand, the Gorge Scourge - Obli: East Ibra Ravine - Tyrant", depends=["Bertrand, the Gorge Scourge"]),
Data("The Trading Floor - Obli: Sea Whisper Valley - Chp 3", depends=["Chapter 3"]),
Data("Alien Container 3 - Obli: Jair Fortress - Archeological 4", rules=["Archeological 4"], depends=["Chapter 3"]),
Data("Spy Games - Obli: Jair Fortress", depends=["Spy Games"]),
Data("White Whale Debris 17 - Caul: Far Isle of Tzuo - Mechanical 1", rules=["Mechanical 1"], depends=["Chapter 3"]),
Data("Alien Reliquary 1 - Caul: Scholes Battlegrounds - Archeological 2", rules=["Archeological 2"], depends=["Chapter 3"]),
Data("Supplies Surprise - Caul: Drongo Caravan - Chp 4", rules=["Nalus Present"], depends=["Chapter 4"]),
Data("Indigen Nest 5 - Caul: Ancient Warscape - Biological 1", rules=["Biological 1"], depends=["Chapter 3"]),
Data("Indigen Nest 6 - Caul: Forgotten Mining Frigate - Biological 5", rules=["Biological 5", "Flight Module"], depends=["Chapter 3"]),
Data("Gorkwa Games - Caul: White Phosphorus", depends=["Gorkwa Games"]),
Data("Sparking a Smile - Caul: Drongo Caravan", depends=["Sparking a Smile"]),
Data("Slovitys Revenge - Caul: Ancient Warscape", depends=["Slovitys Revenge"]),
Data("Lifepod 1 - Caul: Emerian Battlegrounds - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),
Data("Kringe, the Hunting Arrow - Caul: Scholes Battleground - Tyrant", depends=["Kringe, the Hunting Arrow"]),
Data("White Whale Debris 18 - Caul: Wildcat Fortress - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),
Data("White Whale Debris 19 - Caul: Gnahan Villa - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),
Data("The Bodyguard - Caul: FN Site 505", rules=["Shop Bodyguard"], depends=["Chapter 5", "BFFs"]),
Data("My Angel, My Lana - Caul: Emerian Battlegrounds", depends=["My Angel, My Lana"]),
Data("Alien Wreckage 12 - Caul: Emerian Battlegrounds - Archeological 2", rules=["Archeological 2"], depends=["Chapter 3"]),
Data("Definian Downfall - Caul: Ganglion Antropolis", depends=["Definian Downfall"]),
Data("Alien Reliquary 2 - Caul: Emerian Battlegrounds - Archeological 2", rules=["Archeological 2"], depends=["Chapter 3"]),
Data("Coil, the Never-Ending - Caul: Forgotten Mining Frigate - Tyrant - Electromagnetic storm", depends=["Coil, the Never-Ending"]),
Data("Prinsipe, the Ravenous - Caul: Forgotten Mining Frigate - Tyrant - Nighttime", depends=["Prinsipe, the Ravenous"]),  # TAJ
Data("The Old Gods - Caul: Slavebird Isle", depends=["The Old Gods"]),
Data("Alien Reliquary 3 - Caul: Adder Byroad - Archeological 2", rules=["Archeological 2"], depends=["Chapter 3"]),
Data("Mia Is Missing! - Caul: Ganglion Antropolis", depends=["Mia Is Missing!"]),
Data("The Duel IV - Caul: Titans Table", rules=["Lvl 36"], depends=["Chapter 11", "The Duel III"]),
Data("Chantais Galdr - Caul: Orrh Sim Capital Ruins - Tyrant - Daytime", depends=["Chantai's Galdr"]),
Data("Patrol Chopper Wreckage 5 - Caul: Orrh Sim Capital Ruins - Mechanical 3", rules=["Mechanical 3"], depends=["Chapter 3"]),
Data("To Serve Nopon - Caul: Dragonbone Promontory", depends=["To Serve Nopon"]),
Data("Rites of Ruin - Caul: Ternion Fork", depends=["Rites of Ruin"]),
Data("Black Lifehold - Caul: Slavebird Isle - Chp 11", rules=["Caul 50", "Medical Data"], depends=["Chapter 11", "Slavebird Isle"]),
Data("Eisen, the Ebon Rock - Caul: Abandoned Bivouac - Tyrant - Nighttime", depends=["Eisen, the Ebon Rock"]),
Data("Alien Container 4 - Caul: Abandoned Bivouac - Archeological 2", rules=["Archeological 2"], depends=["Chapter 3"]),
Data("Lionhearted - Caul: Ganglion Weapons Hangar - Chp 12", rules=["Lvl 51"], depends=["Chapter 12", "A Challenger Approaches"]),
Data("Pelicollo, the Panzer - Caul: Ternion Fork - Tyrant", depends=["Pelicollo, the Panzer"]),
Data("Alien Container 5 - Caul: Forgotten Mining Frigate - Archeological 3", rules=["Archeological 3"], depends=["Chapter 3"]),
Data("Lifepod 2 - Caul: Slavebird Isle - Mechanical 3", rules=["Mechanical 3"], depends=["Slavebird Isle"]),
Data("Chantai, the Insect Maiden - Caul: Forgotten Mining Frigate - Tyrant - Nighttime", depends=["Chantai, the Insect Maiden"]),
Data("Armored Cruiser Seidr - Caul: Orrh Sim Watchtowers - Tyrant - Daytime", depends=["Armored Cruiser Seidr"]),
Data("Duran, the Draconian - Caul: Tphnom Shelf - Tyrant", depends=["Duran, the Draconian"]),
Data("Ilithios, the Enlightened - Caul: Sunset Falls - Tyrant", depends=["Ilithios, the Enlightened"]),
Data("Lifepod 3 - Caul: Tengus Playground - Mechanical 3", rules=["Mechanical 3"], depends=["Chapter 3"]),
Data("Lifepod 4 - Caul: Kitsune Stronghold - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),
Data("A Present for Hope - Caul: Forgotten Mining Frigate", depends=["A Present for Hope"]),
Data("Alien Wreckage 13 - Caul: Abandoned Bivouac - Archeological 2", rules=["Archeological 2"], depends=["Chapter 3"]),
Data("Indigen Nest 7 - Caul: Capital Wreckage - Biological 2", rules=["Biological 2", "Skell License"], depends=["Chapter 3"]),
Data("Alien Container 6 - Caul: Capital Wreckage - Archeological 2", rules=["Archeological 2"], depends=["Chapter 3"]),
Data("Patrol Chopper Wreckage 6 - Caul: Kwarah Villa - Mechanical 2", rules=["Mechanical 2", "Skell License"], depends=["Chapter 3"]),
Data("Alien Reliquary 4 - Caul: Bestial Utopia - Archeological 2", rules=["Archeological 2"], depends=["Chapter 3"]),
Data("Terenty, the Blademaster - Caul: Mgando Gorge - Tyrant", depends=["Terenty, the Blademaster"]),
Data("Patrol Chopper Wreckage 7 - Caul: Mgando Gorge - Mechanical 2", rules=["Mechanical 2"], depends=["Chapter 3"]),
Data("Until the End - Caul: Mgando Gorge - Chp 11", rules=["Lvl 39", "Vi Sezhas Bracelet", "Ge Jewhes Dagger"], depends=["Chapter 11", "A Challenger Approaches"]),
Data("Gi-zho, the Iron Deity - Caul: Kwarah Villa - Tyrant", depends=["Gi-zho, the Iron Deity"]),  # TAJ
Data("Jia Mian, the Beloved - Caul: Mount Mgando - Tyrant", depends=["Jia Mian, the Beloved"]),
Data("The Queen Is Dead - Caul: Mount Mgando - Caul: Mount Mgando", depends=["The Queen Is Dead"]),
Data("Sharnaak, the Technician - Caul: Mount Mgando - Tyrant - Nighttime", depends=["Sharnaak, the Technician"]),
Data("Alexs Last Stand - Caul: Mount Mgando", depends=["Alexs Last Stand"]),
Data("Patrol Chopper Wreckage 8 - Caul: Kwarah Villa - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("The Unbreakable Sword - Caul: Mount Mgando", depends=["The Unbreakable Sword"]),
Data("Alien Reliquary 5 - Caul: Old Ceremonial Hollow - Archeological 4", rules=["Archeological 4"], depends=["Chapter 3"]),
Data("Alien Wreckage 14 - Caul: Mgando Gorge - Archeological 2", rules=["Archeological 2"], depends=["Chapter 3"]),
Data("Indigen Nest 8 - Caul: Mount Mgando - Biological 3", rules=["Biological 3"], depends=["Chapter 3"]),
Data("Alien Container 7 - Sylv: Shivering Sands - Archeological 4", rules=["Archeological 4"], depends=["Chapter 3"]),
Data("Yune, the Ambusher - Sylv: Seabirds Beak - Tyrant - Rarely", depends=["Yune, the Ambusher"]),
Data("Strange Petrified Tree 1 - Sylv: Seabirds Beak - Biological 3", rules=["Biological 3"], depends=["Chapter 3"]),
Data("Alien Wreckage 15 - Sylv: Cavernous Abyss - Archeological 5", rules=["Archeological 5"], depends=["Cavernous Abyss"]),
Data("Behemoth, the Netherdweller - Sylv: Cavernous Abyss - Tyrant - Rarely", depends=["Behemoth, the Netherdweller"]),
Data("Lesson from the Grave - Sylv: Shivering Sands - Chp 4", rules=["Rectangular Chest"], depends=["Chapter 4"]),
Data("Predator and Prey - Sylv: Shivering Sands - Chp 6", rules=["Lvl 32", "Ice Cream Cake", "Noble Silk"], depends=["Chapter 6"]),
Data("Strange Petrified Tree 2 - Sylv: Hilal Meadow - Biological 2", rules=["Biological 2"], depends=["Chapter 3"]),
Data("Bottoms Up - Sylv: Seabirds Beak", depends=["Bottoms Up"]),
Data("Stola, the Champion - Sylv: Seabirds Beak - Tyrant - Crimson aurora", depends=["Stola, the Champion"]),
Data("Alien Container 8 - Sylv: Badr Stronghold - Archeological 4", rules=["Archeological 4"], depends=["Chapter 3"]),
Data("Alexei, the Jade - Sylv: West Ciel Sandsea - Tyrant", depends=["Alexei, the Jade"]),
Data("Alien Reliquary 6 - Sylv: West Ciel Sandsea - Archeological 4", rules=["Archeological 4"], depends=["Chapter 3"]),
Data("Castle in the Sky - Sylv: Lake Ciel - Night - Chp 4", rules=["Lvl 32", "Kutas Cargo"], depends=["Chapter 4"]),
Data("Florence, the Hell Maggot - Sylv: Hilal Meadow - Tyrant - Nighttime", depends=["Florence, the Hell Maggot"]),
Data("Antara, the Water Diviner - Sylv: West Cinderdunes - Tyrant", depends=["Antara, the Water Diviner"]),
Data("Alien Container 9 - Sylv: Lesser Anvil - Archeological 3", rules=["Archeological 3", "Skell License"], depends=["Chapter 3"]),
Data("Plans of Attack - Sylv: Badr Basin - Chp 11", rules=["Lvl 55", "New Weapon Blueprint"], depends=["Chapter 11", "A Challenger Approaches", "Lend an Ear"]),
Data("Radovan, the Sky Baron - Sylv: Lake Ciel - Tyrant - Daytime", depends=["Radovan, the Sky Baron"]),
Data("Laurencio, the Fog Bow - Sylv: Lake Ciel - Tyrant", depends=["Laurencio, the Fog Bow"]),
Data("Asana, the Azure Star - Sylv: Lake Ciel - Tyrant", depends=["Asana, the Azure Star"]),
Data("The Line of Fire - Sylv: Hilal Meadow", depends=["The Line of Fire"]),
Data("Damaged Zig - Sylv: Hilal Stronghold - Tyrant", depends=["Damaged Zig"]),
Data("Unknown Assailant - Sylv: Banshee Cove", depends=["Unknown Assailant"]),
Data("Strange Petrified Tree 3 - Sylv: Banshee Cove - Biological 5", rules=["Biological 5"], depends=["Chapter 3"]),
Data("Candelario, the Bronze - Sylv: Anvil Sandplain - Tyrant", depends=["Candelario, the Bronze"]),
Data("Alien Container 10 - Sylv: Badr Strongbridge - Archeological 4", rules=["Archeological 4"], depends=["Chapter 3"]),
Data("Soldier of the Harriers - Sylv: South Cinderdunes", depends=["Soldier of the Harriers"]),
Data("Hair Apparent - Sylv: Lake Ciel - Chp 8", rules=["Sapphire Ring", "Nios IOU"], depends=["Chapter 8"]),
Data("Patrol Chopper Wreckage 9 - Sylv: South Ciel Sandsea - Mechanical 3", rules=["Mechanical 3"], depends=["Chapter 3"]),
Data("Alien Container 11 - Sylv: Hilal Stronghold - Archeological 4", rules=["Archeological 4"], depends=["Chapter 3"]),
Data("Luxaars Xern - Sylv: Arc Rock - Tyrant", depends=["Luxaar's Xern"]),
Data("Patrol Chopper Wreckage 10 - Sylv: Anvil Rock Two - Mechanical 5", rules=["Mechanical 5"], depends=["Chapter 3"]),
Data("Law and Orders - Sylv: Anvil Sandplains", rules=["Lvl 43", "Laws Pendant"], depends=["Chapter 11", "A Challenger Approaches", "The Celeste Three"]),
Data("Strange Petrified Tree 4 - Sylv: South Cinderdunes - Biological 3", rules=["Biological 3"], depends=["Chapter 3"]),
Data("Serial Thriller - Sylv: Xanadu Overlook", depends=["Serial Thriller"]),
Data("Alien Reliquary 7 - Sylv: Lake Ciel - Archeological 5", rules=["Archeological 5"], depends=["Chapter 3"]),
Data("Its-a Mia! - Sylv: Lake Ciel - Chp 9", rules=["Lvl 33"], depends=["Chapter 9", "A Girls Wings", "Mighty Mia"]),
Data("Skell Wreckage 17 - Sylv: Hilal Meadow - Mechanical 3", rules=["Mechanical 3"], depends=["Chapter 3"]),
Data("Skell Wreckage 18 - Sylv: Anvil Sandplains - Mechanical 4", rules=["Mechanical 4"], depends=["Chapter 3"]),
Data("Good Fortun - Sylv: Anvil Rock One", depends=["Good Fortun"]),
Data("Gesserith, the Wileworm - Sylv: South Silent Sandsea - Tyrant", depends=["Gesserith, the Wileworm"]),
Data("Ramus, the Supersonic - Sylv: Lake Ciel - Tyrant", depends=["Ramus, the Supersonic"]),
Data("Ignit, the Ultimate Chaos - Sylv: Lake Ciel - Tyrant - Crimson auroras", depends=["Ignit, the Ultimate Chaos"]),
Data("Lockhart, the Killer of Hope - Sylv: Lake Ciel - Tyrant - Rarely", depends=["Lockhart, the Killer of Hope"]),
Data("Alien Wreckage 16 - Sylv: Needle Rock Sandsea - Archeological 3", rules=["Archeological 3"], depends=["Chapter 3"]),
Data("Alien Wreckage 17 - Sylv: North Cinderdunes - Archeological 4", rules=["Archeological 4"], depends=["Chapter 3"]),
Data("Strange Petrified Tree 5 - Sylv: North Silent Sandsea - Biological 4", rules=["Biological 4"], depends=["Chapter 3"]),
Data("Skell Wreckage 19 - Sylv: Lower Delusian Mountains - Mechanical 3", rules=["Mechanical 3"], depends=["Chapter 3"]),
Data("Strange Petrified Tree 6 - Sylv: South Silent Sandsea - Biological 3", rules=["Biological 3"], depends=["Chapter 3"]),
Data("Alien Wreckage 18 - Sylv: South Hardheart Canyon - Archeological 4", rules=["Archeological 4"], depends=["Chapter 3"]),
Data("Manan, the Water Whisperer - Sylv: Lake Ciel - Tyrant", depends=["Man'an, the Water Whisperer"]),
Data("Alien Reliquary 8 - Sylv: Lake Ciel - Archeological 4", rules=["Archeological 4"], depends=["Chapter 3"]),
Data("Thaddaeus, the Ultramafic - Sylv: East Lake Ciel - Tyrant", depends=["Thaddaeus, the Ultramafic"]),
Data("Alien Container 12 - Sylv: Quay Hollows - Archeological 4", rules=["Archeological 4"], depends=["Quay Hollows"]),
Data("Alien Wreckage 19 - Sylv: Cauldros Threshold - Archeological 2", rules=["Archeological 2"], depends=["Chapter 3"]),
Data("Special Delivery - Sylv: North Silent Sandsea - Chp 7", rules=["Lvl 17", "Zazazans Package"], depends=["Chapter 7", "The Bodyguard"]),
Data("The Duel III - Sylv: Delusian North Summit", depends=["The Duel III"]),
Data("Brotherly Love - Sylv: South Hardheart Canyon", depends=["Brotherly Love"]),
Data("Sadars Qmoeva - Sylv: North Ciel Sandsea - Tyrant - Daytime", depends=["Sadar's Qmoeva"]),
Data("Strange Petrified Tree 7 - Sylv: East Ciel Sandsea - Biological 4", rules=["Biological 4"], depends=["Chapter 3"]),
Data("Leaving the Nest - Sylv: Cauldros Threshold", rules=["Lvl 40"], depends=["Chapter 11", "Until the End"]),
Data("Clara, the Pure White - Sylv: North Silent Sandsea - Tyrant - Daytime", depends=["Clara, the Pure White"]),
Data("Alien Container 13 - Sylv: Lower Delusian Mountains - Archeological 4", rules=["Archeological 4"], depends=["Chapter 3"]),
Data("Orphean Pluck - Sylv: Delusians South Summit", depends=["Orphean Pluck"]),
Data("Strange Petrified Tree 8 - Sylv: Southern Searoad - Biological 2", rules=["Biological 2"], depends=["Chapter 3"]),
Data("Strange Petrified Tree 9 - Sylv: Cleansing Spring - Biological 3", rules=["Biological 3"], depends=["Chapter 3"]),
Data("Strange Petrified Tree 10 - Sylv: Northern Searoad - Biological 4", rules=["Biological 4"], depends=["Chapter 3"]),
Data("Alien Container 14 - Sylv: North Hardheart Canyon - Archeological 4", rules=["Archeological 4"], depends=["Chapter 3"]),
Data("The Sword of Legendaryness - Sylv: Behemoths Shadows", depends=["The Sword of Legendaryness"]),
Data("Alien Container 15 - Sylv: Southern Searoad - Archeological 2", rules=["Archeological 2"], depends=["Chapter 3"]),
Data("Oc-serv, the Ancient - Sylv: Sylvalum Searoad - Tyrant", depends=["Oc-serv, the Ancient"]),
Data("The Repair Job - Aff Mission - BLADE Barracks - Lin 1 - Chp 3", rules=["Lin 1", "FNet", "Lvl 13", "L-002 Power Cable"], depends=["Chapter 3"]),
Data("Lin - BLADE Barracks", depends=["Chapter 1"]),
Data("A Day in the Life - Aff Mission - BLADE Barracks - Chp 4", rules=["Lvl 16"], depends=["Chapter 4"]),
Data("Then and Now - Aff Mission - BLADE Barracks - Elma 4 - Chp 12", rules=["Elma 4", "Lvl 58"], depends=["Chapter 12"]),
Data("To Serve Nopon - Aff Mission - BLADE Barracks - Lin 4 - Chp 12", rules=["Lin 4", "Lvl 52"], depends=["Chapter 12", "BFFs"]),
Data("Elma 5 H2H - BLADE Barracks - Night", rules=["Elma 5"], depends=["Elma 4 H2H"]), 
Data("Nagis Time - Aff Mission - BLADE Barracks - Chp 8", rules=["Lvl 32"], depends=["Chapter 8"]),
Data("A Challenger Approaches - Aff Mission - BLADE Barracks - Chp 10", rules=["Lvl 42", "Med Kit NLA", "Med Kit Ganglion"], depends=["Chapter 10", "Prospective Partners"]),
Data("Nagi 4 H2H - BLADE Barracks", rules=["Nagi 4"], depends=["Nagi 3 H2H"]), 
Data("We Were Soldiers - Aff Mission - BLADE Barracks - Elma 1 - Chp 3", rules=["Elma 1", "Lvl 12", "White Whale Parts"], depends=["Chapter 3"]),
Data("Elma - BLADE Barracks", depends=["Chapter 1"]),
Data("Two Peas in a Pod - Aff Mission - BLADE Barracks - Lin 3 - Chp 11", rules=["Lin 3", "FNet Resource", "Lvl 47"], depends=["Chapter 11", "A Day in the Life"]),
Data("Fathers and Sons - Aff Mission - BLADE Barracks - Irina 40 - Chp 11", rules=["Irina 4", "Lvl 50", "Flemtide"], depends=["Chapter 11", "A Girls Wings", "Renewed Will"]),
Data("BFFs - Aff Mission - BLADE Barracks - Chp 5", rules=["Lvl 22", "Dodonga Treaty", "Dorian Treaty"], depends=["Chapter 5", "The Ties That Bind", "Dodonga Caravan", "Dorian Caravan"]), # need the items the missions are the way to get them
Data("Prospective Partners - Aff Mission - BLADE Barracks - Chp 9", rules=["Mira 18", "Mira 20", "Lvl 34", "Wrothian Part"], depends=["Chapter 9"]),
Data("A Friend in Need - Aff Mission - BLADE Barracks - Chp 5", rules=["Lvl 19"], depends=["Chapter 5"]),
]
# use helper
# id: https://xenoblade.github.io/xbx/bdat/common_local_us/SEG_NormalList.html
# text: https://xenoblade.github.io/xbx/bdat/common_ms/SEG_Segment_ms.html
