import dataclasses
from typing import cast
from typing_extensions import override
from rule_builder.field_resolvers import FieldResolver
from rule_builder.options import OptionFilter
from rule_builder.rules import Has, Rule
from worlds.AutoWorld import World
from ..Options import LogicLevelSteps, XenobladeXOptions


# Convert the real level into the required logic count
def get_logic_level_count(real_level: int, step_size: int) -> int:
    if step_size == 0:
        return 0
    return 1 + int(min(real_level, 50) / step_size) + int(max(real_level - 50, 0) / (step_size + 5))


# Convert the logic level count back into the real level
def get_upper_real_level_from_logic_count(logic_level: int, step_size: int) -> int:
    if step_size == 0:
        return 0
    lower_count = int(50 / step_size)
    if logic_level <= lower_count:
        return (logic_level * step_size) - 1
    return 50 - 1 + (logic_level - lower_count) * (step_size + 5)


@dataclasses.dataclass(frozen=True)
class LogicLevelResolv(FieldResolver, game="Xenoblade X"):
    logic_level: int

    @override
    def resolve(self, world: "World") -> int:
        step_size = cast(XenobladeXOptions, world.options).logic_level_steps.value
        count = get_logic_level_count(self.logic_level, step_size)
        return count

    @override
    def __str__(self) -> str:
        return f"(Lvl {self.logic_level})"


level_rules: dict[str, Rule] = {
    "Lvl 1": Has("KEY: Level", count=LogicLevelResolv(1), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                 filtered_resolution=True),
    "Lvl 2": Has("KEY: Level", count=LogicLevelResolv(2), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                 filtered_resolution=True),
    "Lvl 3": Has("KEY: Level", count=LogicLevelResolv(3), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                 filtered_resolution=True),
    "Lvl 4": Has("KEY: Level", count=LogicLevelResolv(4), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                 filtered_resolution=True),
    "Lvl 5": Has("KEY: Level", count=LogicLevelResolv(5), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                 filtered_resolution=True),
    "Lvl 6": Has("KEY: Level", count=LogicLevelResolv(6), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                 filtered_resolution=True),
    "Lvl 7": Has("KEY: Level", count=LogicLevelResolv(7), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                 filtered_resolution=True),
    "Lvl 8": Has("KEY: Level", count=LogicLevelResolv(8), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                 filtered_resolution=True),
    "Lvl 9": Has("KEY: Level", count=LogicLevelResolv(9), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                 filtered_resolution=True),
    "Lvl 10": Has("KEY: Level", count=LogicLevelResolv(10), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 11": Has("KEY: Level", count=LogicLevelResolv(11), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 12": Has("KEY: Level", count=LogicLevelResolv(12), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 13": Has("KEY: Level", count=LogicLevelResolv(13), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 14": Has("KEY: Level", count=LogicLevelResolv(14), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 15": Has("KEY: Level", count=LogicLevelResolv(15), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 16": Has("KEY: Level", count=LogicLevelResolv(16), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 17": Has("KEY: Level", count=LogicLevelResolv(17), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 18": Has("KEY: Level", count=LogicLevelResolv(18), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 19": Has("KEY: Level", count=LogicLevelResolv(19), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 20": Has("KEY: Level", count=LogicLevelResolv(20), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 21": Has("KEY: Level", count=LogicLevelResolv(21), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 22": Has("KEY: Level", count=LogicLevelResolv(22), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 23": Has("KEY: Level", count=LogicLevelResolv(23), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 24": Has("KEY: Level", count=LogicLevelResolv(24), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 25": Has("KEY: Level", count=LogicLevelResolv(25), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 26": Has("KEY: Level", count=LogicLevelResolv(26), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 27": Has("KEY: Level", count=LogicLevelResolv(27), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 28": Has("KEY: Level", count=LogicLevelResolv(28), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 29": Has("KEY: Level", count=LogicLevelResolv(29), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 30": Has("KEY: Level", count=LogicLevelResolv(30), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 31": Has("KEY: Level", count=LogicLevelResolv(31), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 32": Has("KEY: Level", count=LogicLevelResolv(32), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 33": Has("KEY: Level", count=LogicLevelResolv(33), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 34": Has("KEY: Level", count=LogicLevelResolv(34), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 35": Has("KEY: Level", count=LogicLevelResolv(35), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 36": Has("KEY: Level", count=LogicLevelResolv(36), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 37": Has("KEY: Level", count=LogicLevelResolv(37), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 38": Has("KEY: Level", count=LogicLevelResolv(38), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 39": Has("KEY: Level", count=LogicLevelResolv(39), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 40": Has("KEY: Level", count=LogicLevelResolv(40), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 41": Has("KEY: Level", count=LogicLevelResolv(41), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 42": Has("KEY: Level", count=LogicLevelResolv(42), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 43": Has("KEY: Level", count=LogicLevelResolv(43), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 44": Has("KEY: Level", count=LogicLevelResolv(44), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 45": Has("KEY: Level", count=LogicLevelResolv(45), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 46": Has("KEY: Level", count=LogicLevelResolv(46), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 47": Has("KEY: Level", count=LogicLevelResolv(47), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 48": Has("KEY: Level", count=LogicLevelResolv(48), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 49": Has("KEY: Level", count=LogicLevelResolv(49), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 50": Has("KEY: Level", count=LogicLevelResolv(50), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 51": Has("KEY: Level", count=LogicLevelResolv(51), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 52": Has("KEY: Level", count=LogicLevelResolv(52), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 53": Has("KEY: Level", count=LogicLevelResolv(53), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 54": Has("KEY: Level", count=LogicLevelResolv(54), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 55": Has("KEY: Level", count=LogicLevelResolv(55), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 56": Has("KEY: Level", count=LogicLevelResolv(56), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 57": Has("KEY: Level", count=LogicLevelResolv(57), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 58": Has("KEY: Level", count=LogicLevelResolv(58), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 59": Has("KEY: Level", count=LogicLevelResolv(59), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 60": Has("KEY: Level", count=LogicLevelResolv(60), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 61": Has("KEY: Level", count=LogicLevelResolv(61), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 62": Has("KEY: Level", count=LogicLevelResolv(62), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 63": Has("KEY: Level", count=LogicLevelResolv(63), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 64": Has("KEY: Level", count=LogicLevelResolv(64), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 65": Has("KEY: Level", count=LogicLevelResolv(65), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 66": Has("KEY: Level", count=LogicLevelResolv(66), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 67": Has("KEY: Level", count=LogicLevelResolv(67), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 68": Has("KEY: Level", count=LogicLevelResolv(68), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 69": Has("KEY: Level", count=LogicLevelResolv(69), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 70": Has("KEY: Level", count=LogicLevelResolv(70), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 71": Has("KEY: Level", count=LogicLevelResolv(71), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 72": Has("KEY: Level", count=LogicLevelResolv(72), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 73": Has("KEY: Level", count=LogicLevelResolv(73), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 74": Has("KEY: Level", count=LogicLevelResolv(74), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 75": Has("KEY: Level", count=LogicLevelResolv(75), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 76": Has("KEY: Level", count=LogicLevelResolv(76), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 77": Has("KEY: Level", count=LogicLevelResolv(77), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 78": Has("KEY: Level", count=LogicLevelResolv(78), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 79": Has("KEY: Level", count=LogicLevelResolv(79), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 80": Has("KEY: Level", count=LogicLevelResolv(80), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 81": Has("KEY: Level", count=LogicLevelResolv(81), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 82": Has("KEY: Level", count=LogicLevelResolv(82), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 83": Has("KEY: Level", count=LogicLevelResolv(83), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 84": Has("KEY: Level", count=LogicLevelResolv(84), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 85": Has("KEY: Level", count=LogicLevelResolv(85), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 86": Has("KEY: Level", count=LogicLevelResolv(86), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 87": Has("KEY: Level", count=LogicLevelResolv(87), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 88": Has("KEY: Level", count=LogicLevelResolv(88), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 89": Has("KEY: Level", count=LogicLevelResolv(89), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 90": Has("KEY: Level", count=LogicLevelResolv(90), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 91": Has("KEY: Level", count=LogicLevelResolv(91), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 92": Has("KEY: Level", count=LogicLevelResolv(92), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 93": Has("KEY: Level", count=LogicLevelResolv(93), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 94": Has("KEY: Level", count=LogicLevelResolv(94), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 95": Has("KEY: Level", count=LogicLevelResolv(95), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 96": Has("KEY: Level", count=LogicLevelResolv(96), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 97": Has("KEY: Level", count=LogicLevelResolv(97), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 98": Has("KEY: Level", count=LogicLevelResolv(98), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
    "Lvl 99": Has("KEY: Level", count=LogicLevelResolv(99), options=[OptionFilter(LogicLevelSteps, 0, operator="ne")],
                  filtered_resolution=True),
}
