# --- MWGG bootstrap: skip all installs, then synthesize a minimal `mwgg_igdb`
# shim from each -g slug's archipelago.json before anything imports `worlds.*`
# (which would otherwise pull the real index from GitHub). os/sys/ap_path are
# owned by the host fuzz.py at the splice point (hence the per-line F821 noqa).
os.environ["SKIP_ALL_INSTALLS"] = "1"  # noqa: F821

import argparse as _bootstrap_argparse
import json as _bootstrap_json
import sysconfig as _bootstrap_sysconfig
import importlib as _bootstrap_importlib
from pathlib import Path as _BootstrapPath

# Upstream fuzz.py hand-builds the generation Namespace with a fixed key set,
# so Generate.main can read args it never set. Seed defaults as Namespace CLASS
# attributes (instances inherit; real argparse runs override). Add drifted args here.
for _attr, _default in {"allow_quantity": False}.items():
    setattr(_bootstrap_argparse.Namespace, _attr, _default)

_pre_parser = _bootstrap_argparse.ArgumentParser(add_help=False)
_pre_parser.add_argument("-g", "--game", action="append", default=[])
_pre_args, _ = _pre_parser.parse_known_args()

# Spawn workers re-import with sys.argv = ['-c', ...]; argparse sees nothing,
# so fall back to an env var the parent sets.
_games = _pre_args.game or [
    s for s in os.environ.get("APFUZZ_GAMES", "").split(",") if s  # noqa: F821
]
if _games:
    os.environ["APFUZZ_GAMES"] = ",".join(_games)  # noqa: F821

_name_to_slug: dict = {}
if _games:
    _search_roots = [
        _BootstrapPath(ap_path) / "worlds",  # noqa: F821
        _BootstrapPath(_bootstrap_sysconfig.get_paths()["purelib"]) / "worlds",
    ]
    for _slug in _games:
        _manifest_path = None
        for _root in _search_roots:
            _candidate = _root / _slug / "archipelago.json"
            if _candidate.is_file():
                _manifest_path = _candidate
                break
        if _manifest_path is None:
            raise SystemExit(
                f"fuzz.py: archipelago.json not found for slug {_slug!r} "
                f"(searched {[str(r) for r in _search_roots]})"
            )
        with open(_manifest_path, "r", encoding="utf-8") as _fd:
            _manifest = _bootstrap_json.load(_fd)
        _name = _manifest.get("game")
        if not _name:
            raise SystemExit(
                f"fuzz.py: {_manifest_path} missing 'game' field"
            )
        _name_to_slug[_name] = _slug

# Always write the shim, even with no -g: Generate.py's module-top
# `from mwgg_igdb import GameIndex` runs unconditionally on import.
_shim_src = (
    "# Auto-generated by fuzz.py - overwritten on every run.\n"
    "class GameIndex:\n"
    f"    game_names = {_name_to_slug!r}\n"
    "    @classmethod\n"
    "    def get_all_games(cls):\n"
    "        return {slug: {'game_name': name} for name, slug in cls.game_names.items()}\n"
    "    @classmethod\n"
    "    def get_game_name_for_module(cls, module_name):\n"
    "        for name, slug in cls.game_names.items():\n"
    "            if slug == module_name:\n"
    "                return name\n"
    "        return None\n"
    "    @classmethod\n"
    "    def get_game(cls, module_name):\n"
    "        return {'game_name': cls.get_game_name_for_module(module_name)}\n"
    "    @classmethod\n"
    "    def get_module_for_game(cls, game_name, worlds=True):\n"
    "        slug = cls.game_names.get(game_name)\n"
    "        if slug is None:\n"
    "            return None\n"
    "        return f'worlds.{slug}' if worlds else slug\n"
    "    @classmethod\n"
    "    def add_game(cls, module_name, entry):\n"
    "        name = entry.get('game_name')\n"
    "        if name:\n"
    "            cls.game_names[name] = module_name\n"
)
_shim_path = _BootstrapPath(_bootstrap_sysconfig.get_paths()["purelib"]) / "mwgg_igdb.py"
_shim_path.write_text(_shim_src, encoding="utf-8")
_bootstrap_importlib.invalidate_caches()
sys.modules.pop("mwgg_igdb", None)  # noqa: F821

if _games:
    from Utils import set_game_names
    set_game_names(list(_name_to_slug.keys()))
# --- end MWGG bootstrap
