from BaseClasses import Item


class HPItem(Item):
    game = "Hunie Pop"


panties_item_start = 0
panties_item = {
    "tiffany's panties": panties_item_start + 1,
    "aiko's panties": panties_item_start + 2,
    "kyanna's panties": panties_item_start + 3,
    "audrey's panties": panties_item_start + 4,
    "lola's panties": panties_item_start + 5,
    "nikki's panties": panties_item_start + 6,
    "jessie's panties": panties_item_start + 7,
    "beli's panties": panties_item_start + 8,
    "kyu's panties": panties_item_start + 9,
    "momo's panties": panties_item_start + 10,
    "celeste's panties": panties_item_start + 11,
    "venus's panties": panties_item_start + 12,
}

girl_unlock_start = panties_item_start + 12
girl_unlock = {
    "Unlock Girl(tiffany)": girl_unlock_start + 1,
    "Unlock Girl(aiko)": girl_unlock_start + 2,
    "Unlock Girl(kyanna)": girl_unlock_start + 3,
    "Unlock Girl(audrey)": girl_unlock_start + 4,
    "Unlock Girl(lola)": girl_unlock_start + 5,
    "Unlock Girl(nikki)": girl_unlock_start + 6,
    "Unlock Girl(jessie)": girl_unlock_start + 7,
    "Unlock Girl(beli)": girl_unlock_start + 8,
    "Unlock Girl(kyu)": girl_unlock_start + 9,
    "Unlock Girl(momo)": girl_unlock_start + 10,
    "Unlock Girl(celeste)": girl_unlock_start + 11,
    "Unlock Girl(venus)": girl_unlock_start + 12,
}

gift_item_start = girl_unlock_start + 12
gift_item = {
    "Decorative Pens": gift_item_start + 1,
    "Glossy Notebook": gift_item_start + 2,
    "Graduation Cap": gift_item_start + 3,
    "Textbooks": gift_item_start + 4,
    "Girly Backpack": gift_item_start + 5,
    "Laptop Pro": gift_item_start + 6,
    "Old Fashioned Yoyo": gift_item_start + 7,
    "Puzzle Cube": gift_item_start + 8,
    "Sudoku Books": gift_item_start + 9,
    "Dart Board": gift_item_start + 10,
    "Board Game": gift_item_start + 11,
    "Chess Set": gift_item_start + 12,
    "Water Bottle": gift_item_start + 13,
    "Cardio Weights": gift_item_start + 14,
    "Skipping Rope": gift_item_start + 15,
    "Kettle Bell": gift_item_start + 16,
    "Boxing Gloves": gift_item_start + 17,
    "Punching Bag": gift_item_start + 18,
    "Baby Binky": gift_item_start + 19,
    "Bead Bracelet": gift_item_start + 20,
    "Glow Sticks": gift_item_start + 21,
    "Rainbow Wig": gift_item_start + 22,
    "Fuzzy Boots": gift_item_start + 23,
    "Fairy Wings": gift_item_start + 24,
    "Tennis Balls": gift_item_start + 25,
    "Tennis Racket": gift_item_start + 26,
    "Flying Disc": gift_item_start + 27,
    "Basket Ball": gift_item_start + 28,
    "Volley Ball": gift_item_start + 29,
    "Soccer Ball": gift_item_start + 30,
    "Sketching Pencils": gift_item_start + 31,
    "Paint Brushes": gift_item_start + 32,
    "Drawing Mannequin": gift_item_start + 33,
    "Sketch Pad": gift_item_start + 34,
    "Paint Palette": gift_item_start + 35,
    "Canvas & Easel": gift_item_start + 36,
    "Baking Utensils": gift_item_start + 37,
    "Measuring Cup": gift_item_start + 38,
    "Rolling Pin": gift_item_start + 39,
    "Oven Timer": gift_item_start + 40,
    "Mixing Bowl": gift_item_start + 41,
    "Oven Mitts": gift_item_start + 42,
    "Yoga Belt": gift_item_start + 43,
    "Yoga Blocks": gift_item_start + 44,
    "Yoga Bag": gift_item_start + 45,
    "Yoga Mat": gift_item_start + 46,
    "Yoga Ball": gift_item_start + 47,
    "Yoga Outfit": gift_item_start + 48,
    "Tango Rose": gift_item_start + 49,
    "Sweatbands": gift_item_start + 50,
    "Leg Warmers": gift_item_start + 51,
    "Dancing Fan": gift_item_start + 52,
    "Pink Tutu": gift_item_start + 53,
    "Stripper Pole": gift_item_start + 54,
    "Synthetic Seaweed": gift_item_start + 55,
    "Synthetic Coral": gift_item_start + 56,
    "Tank Gravel": gift_item_start + 57,
    "Bag of Goldfish": gift_item_start + 58,
    "Fishy Castle": gift_item_start + 59,
    "Fish Tank": gift_item_start + 60,
    "Swimmers Cap": gift_item_start + 61,
    "Goggles": gift_item_start + 62,
    "Snorkel": gift_item_start + 63,
    "Flippers": gift_item_start + 64,
    "Lifesaver": gift_item_start + 65,
    "Diving Tank": gift_item_start + 66,
    "Flower Seeds": gift_item_start + 67,
    "Garden Shovel": gift_item_start + 68,
    "Flower Pots": gift_item_start + 69,
    "Watering Can": gift_item_start + 70,
    "Garden Gnome": gift_item_start + 71,
    "Wooden Birdhouse": gift_item_start + 72,
    "Double Hair Bow": gift_item_start + 73,
    "Glitter Bottles": gift_item_start + 74,
    "Twirly Baton": gift_item_start + 75,
    "Megaphone": gift_item_start + 76,
    "Pom-poms": gift_item_start + 77,
    "Cheerleading Uniform": gift_item_start + 78,
    "Chopsticks": gift_item_start + 79,
    "Riceballs": gift_item_start + 80,
    "Bonsai Tree": gift_item_start + 81,
    "Wooden Sandals": gift_item_start + 82,
    "Kimono": gift_item_start + 83,
    "Samurai Helmet": gift_item_start + 84,
    "Maracas": gift_item_start + 85,
    "Sombrero": gift_item_start + 86,
    "Poncho": gift_item_start + 87,
    "Luchador Mask": gift_item_start + 88,
    "Pinata": gift_item_start + 89,
    "Vinuela": gift_item_start + 90,
    "Cigarette Pack": gift_item_start + 91,
    "Lighter": gift_item_start + 92,
    "Glass Pipe": gift_item_start + 93,
    "Glass Bong": gift_item_start + 94,
    "Blotter Tabs": gift_item_start + 95,
    "Happy Pills": gift_item_start + 96,
    "Wing Pin": gift_item_start + 97,
    "Compass": gift_item_start + 98,
    "Pilot's Cap": gift_item_start + 99,
    "Travel Suitcase": gift_item_start + 100,
    "Rolling Luggage": gift_item_start + 101,
    "High Def Camera": gift_item_start + 102,
    "Retro Controller": gift_item_start + 103,
    "Arcade Joystick": gift_item_start + 104,
    "Zappy Gun": gift_item_start + 105,
    "Gamer Glove": gift_item_start + 106,
    "Handheld Game": gift_item_start + 107,
    "Arcade Cabinet": gift_item_start + 108,
    "Mistletoe": gift_item_start + 109,
    "Gingerbread Man": gift_item_start + 110,
    "Round Ornament": gift_item_start + 111,
    "Ribbon Wreath": gift_item_start + 112,
    "Fuzzy Stocking": gift_item_start + 113,
    "Jolly Old Cap": gift_item_start + 114,
    "Acorns": gift_item_start + 115,
    "Maple Leaf": gift_item_start + 116,
    "Pinecone": gift_item_start + 117,
    "Mushrooms": gift_item_start + 118,
    "Seashell": gift_item_start + 119,
    "Four Leaf Clover": gift_item_start + 120,
    "Endurance Ring": gift_item_start + 121,
    "Pocket Vibe": gift_item_start + 122,
    "Fairy's Tail": gift_item_start + 123,
    "Bliss Beads": gift_item_start + 124,
    "Magic Wand": gift_item_start + 125,
    "Royal Scepter": gift_item_start + 126,
    "Ball of Yarn": gift_item_start + 127,
    "Lattice Ball": gift_item_start + 128,
    "Squeaky Mouse": gift_item_start + 129,
    "Feather Pole": gift_item_start + 130,
    "Laser Pointer": gift_item_start + 131,
    "Scratch Post": gift_item_start + 132,
    "Model Rocket": gift_item_start + 133,
    "Miniature UFO": gift_item_start + 134,
    "Armillary Sphere": gift_item_start + 135,
    "Telescope": gift_item_start + 136,
    "Space Helmet": gift_item_start + 137,
    "Moonrock": gift_item_start + 138,
    "Sapphire": gift_item_start + 139,
    "Ruby": gift_item_start + 140,
    "Emerald": gift_item_start + 141,
    "Topaz": gift_item_start + 142,
    "Amethyst": gift_item_start + 143,
    "Diamond": gift_item_start + 144,
}

token_item_start = gift_item_start + 144
token_item = {
    "progressive talent lv-up": token_item_start + 1,
    "progressive flirtation lv-up": token_item_start + 2,
    "progressive romance lv-up": token_item_start + 3,
    "progressive sexuality lv-up": token_item_start + 4,
    "progressive passion lv-up": token_item_start + 5,
    "progressive sensitivity lv-up": token_item_start + 6,
    "progressive charisma lv-up": token_item_start + 7,
    "progressive luck lv-up": token_item_start + 8,
}

junk_item_start = token_item_start + 8
junk_item = {
    # FOODS
    "Coffee": junk_item_start + 1,
    "Orange Juice": junk_item_start + 2,
    "Bagel": junk_item_start + 3,
    "Muffin": junk_item_start + 4,
    "Omelette": junk_item_start + 5,
    "Pancakes": junk_item_start + 6,
    "Cookies": junk_item_start + 7,
    "Cupcakes": junk_item_start + 8,
    "Sundae": junk_item_start + 9,
    "Pumpkin Pie": junk_item_start + 10,
    "Fruit Tart Pie": junk_item_start + 11,
    "Wedding Cake": junk_item_start + 12,
    "Orange": junk_item_start + 13,
    "Lemon": junk_item_start + 14,
    "Mango": junk_item_start + 15,
    "Pinapple": junk_item_start + 16,
    "Coconut": junk_item_start + 17,
    "Watermelon": junk_item_start + 18,
    "Carrot": junk_item_start + 19,
    "Cucumber": junk_item_start + 20,
    "Tomatos": junk_item_start + 21,
    "Bell Peppers": junk_item_start + 22,
    "Eggplant": junk_item_start + 23,
    "Cabbage": junk_item_start + 24,
    "Heart Candies": junk_item_start + 25,
    "Jelly Beans": junk_item_start + 26,
    "Bubble Gum": junk_item_start + 27,
    "Lollipop": junk_item_start + 28,
    "Cotton Candy": junk_item_start + 29,
    "Chocolate": junk_item_start + 30,
    "Soda": junk_item_start + 31,
    "Popcorn": junk_item_start + 32,
    "French Fries": junk_item_start + 33,
    "Corndog": junk_item_start + 34,
    "Hamburger": junk_item_start + 35,
    "Pizza": junk_item_start + 36,
    # DRINKS
    "Beer": junk_item_start + 37,
    "Sake": junk_item_start + 38,
    "Wine": junk_item_start + 39,
    "Champagne": junk_item_start + 40,
    "Pina Colada": junk_item_start + 41,
    "Daiquiri": junk_item_start + 42,
    "Mojito": junk_item_start + 43,
    "Lime Margarita": junk_item_start + 44,
    "Martini": junk_item_start + 45,
    "Cocktail": junk_item_start + 46,
    "Lemon Drop": junk_item_start + 47,
    "Whisky": junk_item_start + 48,
    # DATE GIFTS
    "Hoop Earrings": junk_item_start + 49,
    "Gold Earrings": junk_item_start + 50,
    "Heart Necklace": junk_item_start + 51,
    "Pearl Necklace": junk_item_start + 52,
    "Silver Ring": junk_item_start + 53,
    "Lovely Ring": junk_item_start + 54,
    "Nail Polish": junk_item_start + 55,
    "Shiny Lipstick": junk_item_start + 56,
    "Hair Brush": junk_item_start + 57,
    "Makeup Kit": junk_item_start + 58,
    "Eyelash Curler": junk_item_start + 59,
    "Compact Mirror": junk_item_start + 60,
    "Peep Toe Heels": junk_item_start + 61,
    "Cork Wedge Sandals": junk_item_start + 62,
    "Vintage Platforms": junk_item_start + 63,
    "Leopard Print Pumps": junk_item_start + 64,
    "Pink Mary Janes": junk_item_start + 65,
    "Suede Ankle Booties": junk_item_start + 66,
    "Blue Orchid": junk_item_start + 67,
    "White Pansy": junk_item_start + 68,
    "Orange Cosmos": junk_item_start + 69,
    "Red Tulip": junk_item_start + 70,
    "Pink Lily": junk_item_start + 71,
    "Sunflower": junk_item_start + 72,
    "Stuffed Bear": junk_item_start + 73,
    "Stuffed Cat": junk_item_start + 74,
    "Stuffed Sheep": junk_item_start + 75,
    "Stuffed Monkey": junk_item_start + 76,
    "Stuffed Penguin": junk_item_start + 77,
    "Stuffed Whale": junk_item_start + 78,
    "Sea Breeze Perfume": junk_item_start + 79,
    "Green Tea Perfume": junk_item_start + 80,
    "Peach Perfume": junk_item_start + 81,
    "Cinnamon Perfume": junk_item_start + 82,
    "Rose Perfume": junk_item_start + 83,
    "Lilac Perfume": junk_item_start + 84,
}

item_table = {
    "Nothing": junk_item_start + 85,
    "Goal Achieved": junk_item_start + 86,
    **panties_item,
    **girl_unlock,
    **gift_item,
    **token_item,
    **junk_item,
}

item_datapackage = {
    "panties_item_start": panties_item_start,
    "girl_unlock_start": girl_unlock_start,
    "gift_item_start": gift_item_start,
    "token_item_start": token_item_start,
    "junk_item_start": junk_item_start,
}

filler_items = {
    **junk_item,
    "Nothing": item_table["Nothing"]
}