from BaseClasses import Item


class HP2Item(Item):
    game = "Hunie Pop 2"

#TODO MODIFY FOR ALL PAIRS
fairy_wings_item_start = 0
fairy_wings_item = {
    "Fairy Wings (abia/lola)": fairy_wings_item_start + 1,
    "Fairy Wings (lola/nora)": fairy_wings_item_start + 2,
    "Fairy Wings (candace/nora)": fairy_wings_item_start + 3,
    "Fairy Wings (ashley/polly)": fairy_wings_item_start + 4,
    "Fairy Wings (ashley/lillian)": fairy_wings_item_start + 5,
    "Fairy Wings (lillian/zoey)": fairy_wings_item_start + 6,
    "Fairy Wings (lailani/sarah)": fairy_wings_item_start + 7,
    "Fairy Wings (jessie/lailani)": fairy_wings_item_start + 8,
    "Fairy Wings (brooke/jessie)": fairy_wings_item_start + 9,
    "Fairy Wings (jessie/lola)": fairy_wings_item_start + 10,
    "Fairy Wings (lola/zoey)": fairy_wings_item_start + 11,
    "Fairy Wings (abia/jessie)": fairy_wings_item_start + 12,
    "Fairy Wings (lailani/lillian)": fairy_wings_item_start + 13,
    "Fairy Wings (abia/lillian)": fairy_wings_item_start + 14,
    "Fairy Wings (sarah/zoey)": fairy_wings_item_start + 15,
    "Fairy Wings (polly/zoey)": fairy_wings_item_start + 16,
    "Fairy Wings (nora/sarah)": fairy_wings_item_start + 17,
    "Fairy Wings (brooke/sarah)": fairy_wings_item_start + 18,
    "Fairy Wings (candace/lailani)": fairy_wings_item_start + 19,
    "Fairy Wings (abia/candace)": fairy_wings_item_start + 20,
    "Fairy Wings (candace/polly)": fairy_wings_item_start + 21,
    "Fairy Wings (ashley/nora)": fairy_wings_item_start + 22,
    "Fairy Wings (ashley/brooke)": fairy_wings_item_start + 23,
    "Fairy Wings (brooke/polly)": fairy_wings_item_start + 24,
}

token_item_start = fairy_wings_item_start + 24
token_item = {
    "Progressive Talent Lv-Up": token_item_start + 1,
    "Progressive Romance Lv-Up": token_item_start + 2,
    "Progressive Flirtation Lv-Up": token_item_start + 3,
    "Progressive Sexual Lv-Up": token_item_start + 4,
    "Progressive Passion Lv-Up": token_item_start + 5,
    "Progressive Style Lv-Up": token_item_start + 6,
}
token_item_amounts = {
    "Progressive Talent Lv-Up": 4,
    "Progressive Romance Lv-Up": 4,
    "Progressive Flirtation Lv-Up": 4,
    "Progressive Sexual Lv-Up": 4,
    "Progressive Passion Lv-Up": 8,
    "Progressive Style Lv-Up": 8,
}

#TODO MODIFY FOR ALL GIRLS
girl_unlock_item_start = token_item_start + 6
girl_unlock_item = {
    "Unlock Girl(lola)": girl_unlock_item_start + 1,
    "Unlock Girl(jessie)": girl_unlock_item_start + 2,
    "Unlock Girl(lillian)": girl_unlock_item_start + 3,
    "Unlock Girl(zoey)": girl_unlock_item_start + 4,
    "Unlock Girl(sarah)": girl_unlock_item_start + 5,
    "Unlock Girl(lailani)": girl_unlock_item_start + 6,
    "Unlock Girl(candace)": girl_unlock_item_start + 7,
    "Unlock Girl(nora)": girl_unlock_item_start + 8,
    "Unlock Girl(brooke)": girl_unlock_item_start + 9,
    "Unlock Girl(ashley)": girl_unlock_item_start + 10,
    "Unlock Girl(abia)": girl_unlock_item_start + 11,
    "Unlock Girl(polly)": girl_unlock_item_start + 12,
}

#TODO MODIFY FOR ALL PAIRS
pair_unlock_item_start = girl_unlock_item_start + 12
pair_unlock_item = {
    "Pair Unlock (abia/lola)": pair_unlock_item_start + 1,
    "Pair Unlock (lola/nora)": pair_unlock_item_start + 2,
    "Pair Unlock (candace/nora)": pair_unlock_item_start + 3,
    "Pair Unlock (ashley/polly)": pair_unlock_item_start + 4,
    "Pair Unlock (ashley/lillian)": pair_unlock_item_start + 5,
    "Pair Unlock (lillian/zoey)": pair_unlock_item_start + 6,
    "Pair Unlock (lailani/sarah)": pair_unlock_item_start + 7,
    "Pair Unlock (jessie/lailani)": pair_unlock_item_start + 8,
    "Pair Unlock (brooke/jessie)": pair_unlock_item_start + 9,
    "Pair Unlock (jessie/lola)": pair_unlock_item_start + 10,
    "Pair Unlock (lola/zoey)": pair_unlock_item_start + 11,
    "Pair Unlock (abia/jessie)": pair_unlock_item_start + 12,
    "Pair Unlock (lailani/lillian)": pair_unlock_item_start + 13,
    "Pair Unlock (abia/lillian)": pair_unlock_item_start + 14,
    "Pair Unlock (sarah/zoey)": pair_unlock_item_start + 15,
    "Pair Unlock (polly/zoey)": pair_unlock_item_start + 16,
    "Pair Unlock (nora/sarah)": pair_unlock_item_start + 17,
    "Pair Unlock (brooke/sarah)": pair_unlock_item_start + 18,
    "Pair Unlock (candace/lailani)": pair_unlock_item_start + 19,
    "Pair Unlock (abia/candace)": pair_unlock_item_start + 20,
    "Pair Unlock (candace/polly)": pair_unlock_item_start + 21,
    "Pair Unlock (ashley/nora)": pair_unlock_item_start + 22,
    "Pair Unlock (ashley/brooke)": pair_unlock_item_start + 23,
    "Pair Unlock (brooke/polly)": pair_unlock_item_start + 24,
}

gift_unique_item_start = pair_unlock_item_start + 24
gift_unique_item = {
    "Scissors Unique Gift": gift_unique_item_start+ 1,
    "Spool Of Thread Unique Gift": gift_unique_item_start+ 2,
    "Buttons Unique Gift": gift_unique_item_start+ 3,
    "Pincushion Unique Gift": gift_unique_item_start+ 4,
    "Measuring Tape Unique Gift": gift_unique_item_start+ 5,
    "Gin Unique Gift": gift_unique_item_start+ 6,
    "Rum Unique Gift": gift_unique_item_start+ 7,
    "Whisky Unique Gift": gift_unique_item_start+ 8,
    "Vodka Unique Gift": gift_unique_item_start+ 9,
    "Tequila Unique Gift": gift_unique_item_start+ 10,
    "Witch Hat Unique Gift": gift_unique_item_start+ 11,
    "Jack O Lantern Unique Gift": gift_unique_item_start+ 12,
    "Ouija Board Unique Gift": gift_unique_item_start+ 13,
    "Voodoo Doll Unique Gift": gift_unique_item_start+ 14,
    "Goat Skull Unique Gift": gift_unique_item_start+ 15,
    "Crystals Unique Gift": gift_unique_item_start+ 16,
    "Crystal Ball Unique Gift": gift_unique_item_start+ 17,
    "Incense Unique Gift": gift_unique_item_start+ 18,
    "Hourglass Unique Gift": gift_unique_item_start+ 19,
    "Tarot Cards Unique Gift": gift_unique_item_start+ 20,
    "Manga Book Unique Gift": gift_unique_item_start+ 21,
    "Booby Mousepad Unique Gift": gift_unique_item_start+ 22,
    "Cellphone Cover Unique Gift": gift_unique_item_start+ 23,
    "Chibi Figurine Unique Gift": gift_unique_item_start+ 24,
    "Japanese Candy Unique Gift": gift_unique_item_start+ 25,
    "Bath Salts Unique Gift": gift_unique_item_start+ 26,
    "Hot Stones Unique Gift": gift_unique_item_start+ 27,
    "Loofah Sponge Unique Gift": gift_unique_item_start+ 28,
    "Warm Towels Unique Gift": gift_unique_item_start+ 29,
    "Cucumber Slices Unique Gift": gift_unique_item_start+ 30,
    "Letter Blocks Unique Gift": gift_unique_item_start+ 31,
    "Ring Stacker Unique Gift": gift_unique_item_start+ 32,
    "Mini Xylophone Unique Gift": gift_unique_item_start+ 33,
    "Shapes Block Unique Gift": gift_unique_item_start+ 34,
    "Animal Wheel Unique Gift": gift_unique_item_start+ 35,
    "Binky Unique Gift": gift_unique_item_start+ 36,
    "Baby Cap Unique Gift": gift_unique_item_start+ 37,
    "Diapers Unique Gift": gift_unique_item_start+ 38,
    "Baby Bottle Unique Gift": gift_unique_item_start+ 39,
    "Car Carrier Unique Gift": gift_unique_item_start+ 40,
    "Clutch Purse Unique Gift": gift_unique_item_start+ 41,
    "Shoulder Bag Unique Gift": gift_unique_item_start+ 42,
    "Quilted Handbag Unique Gift": gift_unique_item_start+ 43,
    "Fancy Handbag Unique Gift": gift_unique_item_start+ 44,
    "Elegant Tote Bag Unique Gift": gift_unique_item_start+ 45,
    "Microphone Unique Gift": gift_unique_item_start+ 46,
    "Bass Guitar Unique Gift": gift_unique_item_start+ 47,
    "Drum Kit Unique Gift": gift_unique_item_start+ 48,
    "Drum Sticks Unique Gift": gift_unique_item_start+ 49,
    "Guitar Amp Unique Gift": gift_unique_item_start+ 50,
    "Spanking Paddle Unique Gift": gift_unique_item_start+ 51,
    "Ball Gag Unique Gift": gift_unique_item_start+ 52,
    "Nipple Clamps Unique Gift": gift_unique_item_start+ 53,
    "Handcuffs Unique Gift": gift_unique_item_start+ 54,
    "Chain Collar Unique Gift": gift_unique_item_start+ 55,
    "Television Unique Gift": gift_unique_item_start+ 56,
    "Jukebox Unique Gift": gift_unique_item_start+ 57,
    "Phonograph Unique Gift": gift_unique_item_start+ 58,
    "Radio Unique Gift": gift_unique_item_start+ 59,
    "Soda Machine Unique Gift": gift_unique_item_start+ 60,
}

gift_shoe_item_start = gift_unique_item_start+ 60
gift_shoe_item = {
    "Knitted Boots Gift": gift_shoe_item_start+ 1,
    "Seasonal Boots Gift": gift_shoe_item_start+ 2,
    "Heavy Boots Gift": gift_shoe_item_start+ 3,
    "Fuzzy Boots Gift": gift_shoe_item_start+ 4,
    "Festive Boots Gift": gift_shoe_item_start+ 5,
    "Elegant Peep Toes Gift": gift_shoe_item_start+ 6,
    "Angel Peep Toes Gift": gift_shoe_item_start+ 7,
    "Plaid Peep Toes Gift": gift_shoe_item_start+ 8,
    "Ribbon Peep Toes Gift": gift_shoe_item_start+ 9,
    "Leopard Peep Toes Gift": gift_shoe_item_start+ 10,
    "Suede Booties Gift": gift_shoe_item_start+ 11,
    "Striped Booties Gift": gift_shoe_item_start+ 12,
    "Goth Booties Gift": gift_shoe_item_start+ 13,
    "Abstract Booties Gift": gift_shoe_item_start+ 14,
    "Satanic Booties Gift": gift_shoe_item_start+ 15,
    "Astro Boots Gift": gift_shoe_item_start+ 16,
    "Sacred Boots Gift": gift_shoe_item_start+ 17,
    "Sherbet Boots Gift": gift_shoe_item_start+ 18,
    "Hydro Boots Gift": gift_shoe_item_start+ 19,
    "Cosmic Boots Gift": gift_shoe_item_start+ 20,
    "Geta Platforms Gift": gift_shoe_item_start+ 21,
    "Candy Platforms Gift": gift_shoe_item_start+ 22,
    "Light Up Platforms Gift": gift_shoe_item_start+ 23,
    "Rainbow Platforms Gift": gift_shoe_item_start+ 24,
    "Star Platforms Gift": gift_shoe_item_start+ 25,
    "Comfy Flip Flops Gift": gift_shoe_item_start+ 26,
    "Palm Flip Flops Gift": gift_shoe_item_start+ 27,
    "Melon Flip Flops Gift": gift_shoe_item_start+ 28,
    "Aqua Flip Flops Gift": gift_shoe_item_start+ 29,
    "Garden Flip Flops Gift": gift_shoe_item_start+ 30,
    "Glittery Heels Gift": gift_shoe_item_start+ 31,
    "Golden Heels Gift": gift_shoe_item_start+ 32,
    "Studded Heels Gift": gift_shoe_item_start+ 33,
    "Neon Heels Gift": gift_shoe_item_start+ 34,
    "Clear Heels Gift": gift_shoe_item_start+ 35,
    "Skater Sneakers Gift": gift_shoe_item_start+ 36,
    "Ballin' Sneakers Gift": gift_shoe_item_start+ 37,
    "High Top Sneakers Gift": gift_shoe_item_start+ 38,
    "Airy Sneakers Gift": gift_shoe_item_start+ 39,
    "Training Sneakers Gift": gift_shoe_item_start+ 40,
    "Patriotic Wedges Gift": gift_shoe_item_start+ 41,
    "Charcoal Wedges Gift": gift_shoe_item_start+ 42,
    "Cork Wedges Gift": gift_shoe_item_start+ 43,
    "Wooden Wedges Gift": gift_shoe_item_start+ 44,
    "Denim Wedges Gift": gift_shoe_item_start+ 45,
    "Zip Up Gladiators Gift": gift_shoe_item_start+ 46,
    "Strap Gladiators Gift": gift_shoe_item_start+ 47,
    "Weave Gladiators Gift": gift_shoe_item_start+ 48,
    "Modest Gladiators Gift": gift_shoe_item_start+ 49,
    "Web Gladiators Gift": gift_shoe_item_start+ 50,
    "Crafted Flats Gift": gift_shoe_item_start+ 51,
    "Basic Flats Gift": gift_shoe_item_start+ 52,
    "Floral Flats Gift": gift_shoe_item_start+ 53,
    "Open Flats Gift": gift_shoe_item_start+ 54,
    "Cozy Flats Gift": gift_shoe_item_start+ 55,
    "Girly Pumps Gift": gift_shoe_item_start+ 56,
    "Classy Pumps Gift": gift_shoe_item_start+ 57,
    "Shiny Pumps Gift": gift_shoe_item_start+ 58,
    "Polka Dot Pumps Gift": gift_shoe_item_start+ 59,
    "Fancy Pumps Gift": gift_shoe_item_start+ 60,
}

lola_baggage_item_start = gift_shoe_item_start+ 60
lola_baggage_item = {
    "Found lola's Busy Schedule Baggage": lola_baggage_item_start+ 1,
    "Found lola's Caffeine Junkie Baggage": lola_baggage_item_start+ 2,
    "Found lola's Miss Independent Baggage": lola_baggage_item_start+ 3,
    "Found lola's Depression Baggage": lola_baggage_item_start+ 4,
    "Found lola's Emphysema Baggage": lola_baggage_item_start+ 5,
    "Found lola's Busted Vadge Baggage": lola_baggage_item_start+ 6,
    "Found lola's The Darkness Baggage": lola_baggage_item_start+ 7,
    "Found lola's Asthma Baggage": lola_baggage_item_start+ 8,
    "Found lola's Teen Angst Baggage": lola_baggage_item_start+ 9,
    "Found lola's Aquaphobic Baggage": lola_baggage_item_start+ 10,
    "Found lola's Tinnitus Baggage": lola_baggage_item_start+ 11,
    "Found lola's Kinda Crazy Baggage": lola_baggage_item_start+ 12,
    "Found lola's Annoying as Fuck Baggage": lola_baggage_item_start+ 13,
    "Found lola's Attention Whore Baggage": lola_baggage_item_start+ 14,
    "Found lola's Smelly Pussy Baggage": lola_baggage_item_start+ 15,
    "Found lola's Old Fashioned Baggage": lola_baggage_item_start+ 16,
    "Found lola's Low Self-Esteem Baggage": lola_baggage_item_start+ 17,
    "Found lola's Sheepish Baggage": lola_baggage_item_start+ 18,
    "Found lola's Intellectually Challenged Baggage": lola_baggage_item_start+ 19,
    "Found lola's Hypersensitive Baggage": lola_baggage_item_start+ 20,
    "Found lola's Forgetful Baggage": lola_baggage_item_start+ 21,
    "Found lola's Emotionally Guarded Baggage": lola_baggage_item_start+ 22,
    "Found lola's Abandonment Issues Baggage": lola_baggage_item_start+ 23,
    "Found lola's Vindictive Baggage": lola_baggage_item_start+ 24,
    "Found lola's Gold Digger Baggage": lola_baggage_item_start+ 25,
    "Found lola's Unsentimental Baggage": lola_baggage_item_start+ 26,
    "Found lola's Expensive Tastes Baggage": lola_baggage_item_start+ 27,
    "Found lola's Commitment Issues Baggage": lola_baggage_item_start+ 28,
    "Found lola's Easily Bored Baggage": lola_baggage_item_start+ 29,
    "Found lola's Allergies Baggage": lola_baggage_item_start+ 30,
    "Found lola's Self-Effacing Baggage": lola_baggage_item_start+ 31,
    "Found lola's One Pump Chump Baggage": lola_baggage_item_start+ 32,
    "Found lola's Sex Addict Baggage": lola_baggage_item_start+ 33,
    "Found lola's Jealousy Baggage": lola_baggage_item_start+ 34,
    "Found lola's Drama Queen Baggage": lola_baggage_item_start+ 35,
    "Found lola's Brand Loyalist Baggage": lola_baggage_item_start+ 36,
}

jessie_baggage_item_start = lola_baggage_item_start+ 36
jessie_baggage_item = {
    "Found jessie's Busy Schedule Baggage": jessie_baggage_item_start+ 1,
    "Found jessie's Caffeine Junkie Baggage": jessie_baggage_item_start+ 2,
    "Found jessie's Miss Independent Baggage": jessie_baggage_item_start+ 3,
    "Found jessie's Depression Baggage": jessie_baggage_item_start+ 4,
    "Found jessie's Emphysema Baggage": jessie_baggage_item_start+ 5,
    "Found jessie's Busted Vadge Baggage": jessie_baggage_item_start+ 6,
    "Found jessie's The Darkness Baggage": jessie_baggage_item_start+ 7,
    "Found jessie's Asthma Baggage": jessie_baggage_item_start+ 8,
    "Found jessie's Teen Angst Baggage": jessie_baggage_item_start+ 9,
    "Found jessie's Aquaphobic Baggage": jessie_baggage_item_start+ 10,
    "Found jessie's Tinnitus Baggage": jessie_baggage_item_start+ 11,
    "Found jessie's Kinda Crazy Baggage": jessie_baggage_item_start+ 12,
    "Found jessie's Annoying as Fuck Baggage": jessie_baggage_item_start+ 13,
    "Found jessie's Attention Whore Baggage": jessie_baggage_item_start+ 14,
    "Found jessie's Smelly Pussy Baggage": jessie_baggage_item_start+ 15,
    "Found jessie's Old Fashioned Baggage": jessie_baggage_item_start+ 16,
    "Found jessie's Low Self-Esteem Baggage": jessie_baggage_item_start+ 17,
    "Found jessie's Sheepish Baggage": jessie_baggage_item_start+ 18,
    "Found jessie's Intellectually Challenged Baggage": jessie_baggage_item_start+ 19,
    "Found jessie's Hypersensitive Baggage": jessie_baggage_item_start+ 20,
    "Found jessie's Forgetful Baggage": jessie_baggage_item_start+ 21,
    "Found jessie's Emotionally Guarded Baggage": jessie_baggage_item_start+ 22,
    "Found jessie's Abandonment Issues Baggage": jessie_baggage_item_start+ 23,
    "Found jessie's Vindictive Baggage": jessie_baggage_item_start+ 24,
    "Found jessie's Gold Digger Baggage": jessie_baggage_item_start+ 25,
    "Found jessie's Unsentimental Baggage": jessie_baggage_item_start+ 26,
    "Found jessie's Expensive Tastes Baggage": jessie_baggage_item_start+ 27,
    "Found jessie's Commitment Issues Baggage": jessie_baggage_item_start+ 28,
    "Found jessie's Easily Bored Baggage": jessie_baggage_item_start+ 29,
    "Found jessie's Allergies Baggage": jessie_baggage_item_start+ 30,
    "Found jessie's Self-Effacing Baggage": jessie_baggage_item_start+ 31,
    "Found jessie's One Pump Chump Baggage": jessie_baggage_item_start+ 32,
    "Found jessie's Sex Addict Baggage": jessie_baggage_item_start+ 33,
    "Found jessie's Jealousy Baggage": jessie_baggage_item_start+ 34,
    "Found jessie's Drama Queen Baggage": jessie_baggage_item_start+ 35,
    "Found jessie's Brand Loyalist Baggage": jessie_baggage_item_start+ 36,
}

lillian_baggage_item_start = jessie_baggage_item_start+ 36
lillian_baggage_item = {
    "Found lillian's Busy Schedule Baggage": lillian_baggage_item_start+ 1,
    "Found lillian's Caffeine Junkie Baggage": lillian_baggage_item_start+ 2,
    "Found lillian's Miss Independent Baggage": lillian_baggage_item_start+ 3,
    "Found lillian's Depression Baggage": lillian_baggage_item_start+ 4,
    "Found lillian's Emphysema Baggage": lillian_baggage_item_start+ 5,
    "Found lillian's Busted Vadge Baggage": lillian_baggage_item_start+ 6,
    "Found lillian's The Darkness Baggage": lillian_baggage_item_start+ 7,
    "Found lillian's Asthma Baggage": lillian_baggage_item_start+ 8,
    "Found lillian's Teen Angst Baggage": lillian_baggage_item_start+ 9,
    "Found lillian's Aquaphobic Baggage": lillian_baggage_item_start+ 10,
    "Found lillian's Tinnitus Baggage": lillian_baggage_item_start+ 11,
    "Found lillian's Kinda Crazy Baggage": lillian_baggage_item_start+ 12,
    "Found lillian's Annoying as Fuck Baggage": lillian_baggage_item_start+ 13,
    "Found lillian's Attention Whore Baggage": lillian_baggage_item_start+ 14,
    "Found lillian's Smelly Pussy Baggage": lillian_baggage_item_start+ 15,
    "Found lillian's Old Fashioned Baggage": lillian_baggage_item_start+ 16,
    "Found lillian's Low Self-Esteem Baggage": lillian_baggage_item_start+ 17,
    "Found lillian's Sheepish Baggage": lillian_baggage_item_start+ 18,
    "Found lillian's Intellectually Challenged Baggage": lillian_baggage_item_start+ 19,
    "Found lillian's Hypersensitive Baggage": lillian_baggage_item_start+ 20,
    "Found lillian's Forgetful Baggage": lillian_baggage_item_start+ 21,
    "Found lillian's Emotionally Guarded Baggage": lillian_baggage_item_start+ 22,
    "Found lillian's Abandonment Issues Baggage": lillian_baggage_item_start+ 23,
    "Found lillian's Vindictive Baggage": lillian_baggage_item_start+ 24,
    "Found lillian's Gold Digger Baggage": lillian_baggage_item_start+ 25,
    "Found lillian's Unsentimental Baggage": lillian_baggage_item_start+ 26,
    "Found lillian's Expensive Tastes Baggage": lillian_baggage_item_start+ 27,
    "Found lillian's Commitment Issues Baggage": lillian_baggage_item_start+ 28,
    "Found lillian's Easily Bored Baggage": lillian_baggage_item_start+ 29,
    "Found lillian's Allergies Baggage": lillian_baggage_item_start+ 30,
    "Found lillian's Self-Effacing Baggage": lillian_baggage_item_start+ 31,
    "Found lillian's One Pump Chump Baggage": lillian_baggage_item_start+ 32,
    "Found lillian's Sex Addict Baggage": lillian_baggage_item_start+ 33,
    "Found lillian's Jealousy Baggage": lillian_baggage_item_start+ 34,
    "Found lillian's Drama Queen Baggage": lillian_baggage_item_start+ 35,
    "Found lillian's Brand Loyalist Baggage": lillian_baggage_item_start+ 36,
}

zoey_baggage_item_start = lillian_baggage_item_start+ 36
zoey_baggage_item = {
    "Found zoey's Busy Schedule Baggage": zoey_baggage_item_start+ 1,
    "Found zoey's Caffeine Junkie Baggage": zoey_baggage_item_start+ 2,
    "Found zoey's Miss Independent Baggage": zoey_baggage_item_start+ 3,
    "Found zoey's Depression Baggage": zoey_baggage_item_start+ 4,
    "Found zoey's Emphysema Baggage": zoey_baggage_item_start+ 5,
    "Found zoey's Busted Vadge Baggage": zoey_baggage_item_start+ 6,
    "Found zoey's The Darkness Baggage": zoey_baggage_item_start+ 7,
    "Found zoey's Asthma Baggage": zoey_baggage_item_start+ 8,
    "Found zoey's Teen Angst Baggage": zoey_baggage_item_start+ 9,
    "Found zoey's Aquaphobic Baggage": zoey_baggage_item_start+ 10,
    "Found zoey's Tinnitus Baggage": zoey_baggage_item_start+ 11,
    "Found zoey's Kinda Crazy Baggage": zoey_baggage_item_start+ 12,
    "Found zoey's Annoying as Fuck Baggage": zoey_baggage_item_start+ 13,
    "Found zoey's Attention Whore Baggage": zoey_baggage_item_start+ 14,
    "Found zoey's Smelly Pussy Baggage": zoey_baggage_item_start+ 15,
    "Found zoey's Old Fashioned Baggage": zoey_baggage_item_start+ 16,
    "Found zoey's Low Self-Esteem Baggage": zoey_baggage_item_start+ 17,
    "Found zoey's Sheepish Baggage": zoey_baggage_item_start+ 18,
    "Found zoey's Intellectually Challenged Baggage": zoey_baggage_item_start+ 19,
    "Found zoey's Hypersensitive Baggage": zoey_baggage_item_start+ 20,
    "Found zoey's Forgetful Baggage": zoey_baggage_item_start+ 21,
    "Found zoey's Emotionally Guarded Baggage": zoey_baggage_item_start+ 22,
    "Found zoey's Abandonment Issues Baggage": zoey_baggage_item_start+ 23,
    "Found zoey's Vindictive Baggage": zoey_baggage_item_start+ 24,
    "Found zoey's Gold Digger Baggage": zoey_baggage_item_start+ 25,
    "Found zoey's Unsentimental Baggage": zoey_baggage_item_start+ 26,
    "Found zoey's Expensive Tastes Baggage": zoey_baggage_item_start+ 27,
    "Found zoey's Commitment Issues Baggage": zoey_baggage_item_start+ 28,
    "Found zoey's Easily Bored Baggage": zoey_baggage_item_start+ 29,
    "Found zoey's Allergies Baggage": zoey_baggage_item_start+ 30,
    "Found zoey's Self-Effacing Baggage": zoey_baggage_item_start+ 31,
    "Found zoey's One Pump Chump Baggage": zoey_baggage_item_start+ 32,
    "Found zoey's Sex Addict Baggage": zoey_baggage_item_start+ 33,
    "Found zoey's Jealousy Baggage": zoey_baggage_item_start+ 34,
    "Found zoey's Drama Queen Baggage": zoey_baggage_item_start+ 35,
    "Found zoey's Brand Loyalist Baggage": zoey_baggage_item_start+ 36,
}

sarah_baggage_item_start = zoey_baggage_item_start+ 36
sarah_baggage_item = {
    "Found sarah's Busy Schedule Baggage": sarah_baggage_item_start+ 1,
    "Found sarah's Caffeine Junkie Baggage": sarah_baggage_item_start+ 2,
    "Found sarah's Miss Independent Baggage": sarah_baggage_item_start+ 3,
    "Found sarah's Depression Baggage": sarah_baggage_item_start+ 4,
    "Found sarah's Emphysema Baggage": sarah_baggage_item_start+ 5,
    "Found sarah's Busted Vadge Baggage": sarah_baggage_item_start+ 6,
    "Found sarah's The Darkness Baggage": sarah_baggage_item_start+ 7,
    "Found sarah's Asthma Baggage": sarah_baggage_item_start+ 8,
    "Found sarah's Teen Angst Baggage": sarah_baggage_item_start+ 9,
    "Found sarah's Aquaphobic Baggage": sarah_baggage_item_start+ 10,
    "Found sarah's Tinnitus Baggage": sarah_baggage_item_start+ 11,
    "Found sarah's Kinda Crazy Baggage": sarah_baggage_item_start+ 12,
    "Found sarah's Annoying as Fuck Baggage": sarah_baggage_item_start+ 13,
    "Found sarah's Attention Whore Baggage": sarah_baggage_item_start+ 14,
    "Found sarah's Smelly Pussy Baggage": sarah_baggage_item_start+ 15,
    "Found sarah's Old Fashioned Baggage": sarah_baggage_item_start+ 16,
    "Found sarah's Low Self-Esteem Baggage": sarah_baggage_item_start+ 17,
    "Found sarah's Sheepish Baggage": sarah_baggage_item_start+ 18,
    "Found sarah's Intellectually Challenged Baggage": sarah_baggage_item_start+ 19,
    "Found sarah's Hypersensitive Baggage": sarah_baggage_item_start+ 20,
    "Found sarah's Forgetful Baggage": sarah_baggage_item_start+ 21,
    "Found sarah's Emotionally Guarded Baggage": sarah_baggage_item_start+ 22,
    "Found sarah's Abandonment Issues Baggage": sarah_baggage_item_start+ 23,
    "Found sarah's Vindictive Baggage": sarah_baggage_item_start+ 24,
    "Found sarah's Gold Digger Baggage": sarah_baggage_item_start+ 25,
    "Found sarah's Unsentimental Baggage": sarah_baggage_item_start+ 26,
    "Found sarah's Expensive Tastes Baggage": sarah_baggage_item_start+ 27,
    "Found sarah's Commitment Issues Baggage": sarah_baggage_item_start+ 28,
    "Found sarah's Easily Bored Baggage": sarah_baggage_item_start+ 29,
    "Found sarah's Allergies Baggage": sarah_baggage_item_start+ 30,
    "Found sarah's Self-Effacing Baggage": sarah_baggage_item_start+ 31,
    "Found sarah's One Pump Chump Baggage": sarah_baggage_item_start+ 32,
    "Found sarah's Sex Addict Baggage": sarah_baggage_item_start+ 33,
    "Found sarah's Jealousy Baggage": sarah_baggage_item_start+ 34,
    "Found sarah's Drama Queen Baggage": sarah_baggage_item_start+ 35,
    "Found sarah's Brand Loyalist Baggage": sarah_baggage_item_start+ 36,
}

lailani_baggage_item_start = sarah_baggage_item_start+ 36
lailani_baggage_item = {
    "Found lailani's Busy Schedule Baggage": lailani_baggage_item_start+ 1,
    "Found lailani's Caffeine Junkie Baggage": lailani_baggage_item_start+ 2,
    "Found lailani's Miss Independent Baggage": lailani_baggage_item_start+ 3,
    "Found lailani's Depression Baggage": lailani_baggage_item_start+ 4,
    "Found lailani's Emphysema Baggage": lailani_baggage_item_start+ 5,
    "Found lailani's Busted Vadge Baggage": lailani_baggage_item_start+ 6,
    "Found lailani's The Darkness Baggage": lailani_baggage_item_start+ 7,
    "Found lailani's Asthma Baggage": lailani_baggage_item_start+ 8,
    "Found lailani's Teen Angst Baggage": lailani_baggage_item_start+ 9,
    "Found lailani's Aquaphobic Baggage": lailani_baggage_item_start+ 10,
    "Found lailani's Tinnitus Baggage": lailani_baggage_item_start+ 11,
    "Found lailani's Kinda Crazy Baggage": lailani_baggage_item_start+ 12,
    "Found lailani's Annoying as Fuck Baggage": lailani_baggage_item_start+ 13,
    "Found lailani's Attention Whore Baggage": lailani_baggage_item_start+ 14,
    "Found lailani's Smelly Pussy Baggage": lailani_baggage_item_start+ 15,
    "Found lailani's Old Fashioned Baggage": lailani_baggage_item_start+ 16,
    "Found lailani's Low Self-Esteem Baggage": lailani_baggage_item_start+ 17,
    "Found lailani's Sheepish Baggage": lailani_baggage_item_start+ 18,
    "Found lailani's Intellectually Challenged Baggage": lailani_baggage_item_start+ 19,
    "Found lailani's Hypersensitive Baggage": lailani_baggage_item_start+ 20,
    "Found lailani's Forgetful Baggage": lailani_baggage_item_start+ 21,
    "Found lailani's Emotionally Guarded Baggage": lailani_baggage_item_start+ 22,
    "Found lailani's Abandonment Issues Baggage": lailani_baggage_item_start+ 23,
    "Found lailani's Vindictive Baggage": lailani_baggage_item_start+ 24,
    "Found lailani's Gold Digger Baggage": lailani_baggage_item_start+ 25,
    "Found lailani's Unsentimental Baggage": lailani_baggage_item_start+ 26,
    "Found lailani's Expensive Tastes Baggage": lailani_baggage_item_start+ 27,
    "Found lailani's Commitment Issues Baggage": lailani_baggage_item_start+ 28,
    "Found lailani's Easily Bored Baggage": lailani_baggage_item_start+ 29,
    "Found lailani's Allergies Baggage": lailani_baggage_item_start+ 30,
    "Found lailani's Self-Effacing Baggage": lailani_baggage_item_start+ 31,
    "Found lailani's One Pump Chump Baggage": lailani_baggage_item_start+ 32,
    "Found lailani's Sex Addict Baggage": lailani_baggage_item_start+ 33,
    "Found lailani's Jealousy Baggage": lailani_baggage_item_start+ 34,
    "Found lailani's Drama Queen Baggage": lailani_baggage_item_start+ 35,
    "Found lailani's Brand Loyalist Baggage": lailani_baggage_item_start+ 36,
}

candace_baggage_item_start = lailani_baggage_item_start+ 36
candace_baggage_item = {
    "Found candace's Busy Schedule Baggage": candace_baggage_item_start+ 1,
    "Found candace's Caffeine Junkie Baggage": candace_baggage_item_start+ 2,
    "Found candace's Miss Independent Baggage": candace_baggage_item_start+ 3,
    "Found candace's Depression Baggage": candace_baggage_item_start+ 4,
    "Found candace's Emphysema Baggage": candace_baggage_item_start+ 5,
    "Found candace's Busted Vadge Baggage": candace_baggage_item_start+ 6,
    "Found candace's The Darkness Baggage": candace_baggage_item_start+ 7,
    "Found candace's Asthma Baggage": candace_baggage_item_start+ 8,
    "Found candace's Teen Angst Baggage": candace_baggage_item_start+ 9,
    "Found candace's Aquaphobic Baggage": candace_baggage_item_start+ 10,
    "Found candace's Tinnitus Baggage": candace_baggage_item_start+ 11,
    "Found candace's Kinda Crazy Baggage": candace_baggage_item_start+ 12,
    "Found candace's Annoying as Fuck Baggage": candace_baggage_item_start+ 13,
    "Found candace's Attention Whore Baggage": candace_baggage_item_start+ 14,
    "Found candace's Smelly Pussy Baggage": candace_baggage_item_start+ 15,
    "Found candace's Old Fashioned Baggage": candace_baggage_item_start+ 16,
    "Found candace's Low Self-Esteem Baggage": candace_baggage_item_start+ 17,
    "Found candace's Sheepish Baggage": candace_baggage_item_start+ 18,
    "Found candace's Intellectually Challenged Baggage": candace_baggage_item_start+ 19,
    "Found candace's Hypersensitive Baggage": candace_baggage_item_start+ 20,
    "Found candace's Forgetful Baggage": candace_baggage_item_start+ 21,
    "Found candace's Emotionally Guarded Baggage": candace_baggage_item_start+ 22,
    "Found candace's Abandonment Issues Baggage": candace_baggage_item_start+ 23,
    "Found candace's Vindictive Baggage": candace_baggage_item_start+ 24,
    "Found candace's Gold Digger Baggage": candace_baggage_item_start+ 25,
    "Found candace's Unsentimental Baggage": candace_baggage_item_start+ 26,
    "Found candace's Expensive Tastes Baggage": candace_baggage_item_start+ 27,
    "Found candace's Commitment Issues Baggage": candace_baggage_item_start+ 28,
    "Found candace's Easily Bored Baggage": candace_baggage_item_start+ 29,
    "Found candace's Allergies Baggage": candace_baggage_item_start+ 30,
    "Found candace's Self-Effacing Baggage": candace_baggage_item_start+ 31,
    "Found candace's One Pump Chump Baggage": candace_baggage_item_start+ 32,
    "Found candace's Sex Addict Baggage": candace_baggage_item_start+ 33,
    "Found candace's Jealousy Baggage": candace_baggage_item_start+ 34,
    "Found candace's Drama Queen Baggage": candace_baggage_item_start+ 35,
    "Found candace's Brand Loyalist Baggage": candace_baggage_item_start+ 36,
}

nora_baggage_item_start = candace_baggage_item_start+ 36
nora_baggage_item = {
    "Found nora's Busy Schedule Baggage": nora_baggage_item_start+ 1,
    "Found nora's Caffeine Junkie Baggage": nora_baggage_item_start+ 2,
    "Found nora's Miss Independent Baggage": nora_baggage_item_start+ 3,
    "Found nora's Depression Baggage": nora_baggage_item_start+ 4,
    "Found nora's Emphysema Baggage": nora_baggage_item_start+ 5,
    "Found nora's Busted Vadge Baggage": nora_baggage_item_start+ 6,
    "Found nora's The Darkness Baggage": nora_baggage_item_start+ 7,
    "Found nora's Asthma Baggage": nora_baggage_item_start+ 8,
    "Found nora's Teen Angst Baggage": nora_baggage_item_start+ 9,
    "Found nora's Aquaphobic Baggage": nora_baggage_item_start+ 10,
    "Found nora's Tinnitus Baggage": nora_baggage_item_start+ 11,
    "Found nora's Kinda Crazy Baggage": nora_baggage_item_start+ 12,
    "Found nora's Annoying as Fuck Baggage": nora_baggage_item_start+ 13,
    "Found nora's Attention Whore Baggage": nora_baggage_item_start+ 14,
    "Found nora's Smelly Pussy Baggage": nora_baggage_item_start+ 15,
    "Found nora's Old Fashioned Baggage": nora_baggage_item_start+ 16,
    "Found nora's Low Self-Esteem Baggage": nora_baggage_item_start+ 17,
    "Found nora's Sheepish Baggage": nora_baggage_item_start+ 18,
    "Found nora's Intellectually Challenged Baggage": nora_baggage_item_start+ 19,
    "Found nora's Hypersensitive Baggage": nora_baggage_item_start+ 20,
    "Found nora's Forgetful Baggage": nora_baggage_item_start+ 21,
    "Found nora's Emotionally Guarded Baggage": nora_baggage_item_start+ 22,
    "Found nora's Abandonment Issues Baggage": nora_baggage_item_start+ 23,
    "Found nora's Vindictive Baggage": nora_baggage_item_start+ 24,
    "Found nora's Gold Digger Baggage": nora_baggage_item_start+ 25,
    "Found nora's Unsentimental Baggage": nora_baggage_item_start+ 26,
    "Found nora's Expensive Tastes Baggage": nora_baggage_item_start+ 27,
    "Found nora's Commitment Issues Baggage": nora_baggage_item_start+ 28,
    "Found nora's Easily Bored Baggage": nora_baggage_item_start+ 29,
    "Found nora's Allergies Baggage": nora_baggage_item_start+ 30,
    "Found nora's Self-Effacing Baggage": nora_baggage_item_start+ 31,
    "Found nora's One Pump Chump Baggage": nora_baggage_item_start+ 32,
    "Found nora's Sex Addict Baggage": nora_baggage_item_start+ 33,
    "Found nora's Jealousy Baggage": nora_baggage_item_start+ 34,
    "Found nora's Drama Queen Baggage": nora_baggage_item_start+ 35,
    "Found nora's Brand Loyalist Baggage": nora_baggage_item_start+ 36,
}

brooke_baggage_item_start = nora_baggage_item_start+ 36
brooke_baggage_item = {
    "Found brooke's Busy Schedule Baggage": brooke_baggage_item_start+ 1,
    "Found brooke's Caffeine Junkie Baggage": brooke_baggage_item_start+ 2,
    "Found brooke's Miss Independent Baggage": brooke_baggage_item_start+ 3,
    "Found brooke's Depression Baggage": brooke_baggage_item_start+ 4,
    "Found brooke's Emphysema Baggage": brooke_baggage_item_start+ 5,
    "Found brooke's Busted Vadge Baggage": brooke_baggage_item_start+ 6,
    "Found brooke's The Darkness Baggage": brooke_baggage_item_start+ 7,
    "Found brooke's Asthma Baggage": brooke_baggage_item_start+ 8,
    "Found brooke's Teen Angst Baggage": brooke_baggage_item_start+ 9,
    "Found brooke's Aquaphobic Baggage": brooke_baggage_item_start+ 10,
    "Found brooke's Tinnitus Baggage": brooke_baggage_item_start+ 11,
    "Found brooke's Kinda Crazy Baggage": brooke_baggage_item_start+ 12,
    "Found brooke's Annoying as Fuck Baggage": brooke_baggage_item_start+ 13,
    "Found brooke's Attention Whore Baggage": brooke_baggage_item_start+ 14,
    "Found brooke's Smelly Pussy Baggage": brooke_baggage_item_start+ 15,
    "Found brooke's Old Fashioned Baggage": brooke_baggage_item_start+ 16,
    "Found brooke's Low Self-Esteem Baggage": brooke_baggage_item_start+ 17,
    "Found brooke's Sheepish Baggage": brooke_baggage_item_start+ 18,
    "Found brooke's Intellectually Challenged Baggage": brooke_baggage_item_start+ 19,
    "Found brooke's Hypersensitive Baggage": brooke_baggage_item_start+ 20,
    "Found brooke's Forgetful Baggage": brooke_baggage_item_start+ 21,
    "Found brooke's Emotionally Guarded Baggage": brooke_baggage_item_start+ 22,
    "Found brooke's Abandonment Issues Baggage": brooke_baggage_item_start+ 23,
    "Found brooke's Vindictive Baggage": brooke_baggage_item_start+ 24,
    "Found brooke's Gold Digger Baggage": brooke_baggage_item_start+ 25,
    "Found brooke's Unsentimental Baggage": brooke_baggage_item_start+ 26,
    "Found brooke's Expensive Tastes Baggage": brooke_baggage_item_start+ 27,
    "Found brooke's Commitment Issues Baggage": brooke_baggage_item_start+ 28,
    "Found brooke's Easily Bored Baggage": brooke_baggage_item_start+ 29,
    "Found brooke's Allergies Baggage": brooke_baggage_item_start+ 30,
    "Found brooke's Self-Effacing Baggage": brooke_baggage_item_start+ 31,
    "Found brooke's One Pump Chump Baggage": brooke_baggage_item_start+ 32,
    "Found brooke's Sex Addict Baggage": brooke_baggage_item_start+ 33,
    "Found brooke's Jealousy Baggage": brooke_baggage_item_start+ 34,
    "Found brooke's Drama Queen Baggage": brooke_baggage_item_start+ 35,
    "Found brooke's Brand Loyalist Baggage": brooke_baggage_item_start+ 36,
}

ashley_baggage_item_start = brooke_baggage_item_start+ 36
ashley_baggage_item = {
    "Found ashley's Busy Schedule Baggage": ashley_baggage_item_start+ 1,
    "Found ashley's Caffeine Junkie Baggage": ashley_baggage_item_start+ 2,
    "Found ashley's Miss Independent Baggage": ashley_baggage_item_start+ 3,
    "Found ashley's Depression Baggage": ashley_baggage_item_start+ 4,
    "Found ashley's Emphysema Baggage": ashley_baggage_item_start+ 5,
    "Found ashley's Busted Vadge Baggage": ashley_baggage_item_start+ 6,
    "Found ashley's The Darkness Baggage": ashley_baggage_item_start+ 7,
    "Found ashley's Asthma Baggage": ashley_baggage_item_start+ 8,
    "Found ashley's Teen Angst Baggage": ashley_baggage_item_start+ 9,
    "Found ashley's Aquaphobic Baggage": ashley_baggage_item_start+ 10,
    "Found ashley's Tinnitus Baggage": ashley_baggage_item_start+ 11,
    "Found ashley's Kinda Crazy Baggage": ashley_baggage_item_start+ 12,
    "Found ashley's Annoying as Fuck Baggage": ashley_baggage_item_start+ 13,
    "Found ashley's Attention Whore Baggage": ashley_baggage_item_start+ 14,
    "Found ashley's Smelly Pussy Baggage": ashley_baggage_item_start+ 15,
    "Found ashley's Old Fashioned Baggage": ashley_baggage_item_start+ 16,
    "Found ashley's Low Self-Esteem Baggage": ashley_baggage_item_start+ 17,
    "Found ashley's Sheepish Baggage": ashley_baggage_item_start+ 18,
    "Found ashley's Intellectually Challenged Baggage": ashley_baggage_item_start+ 19,
    "Found ashley's Hypersensitive Baggage": ashley_baggage_item_start+ 20,
    "Found ashley's Forgetful Baggage": ashley_baggage_item_start+ 21,
    "Found ashley's Emotionally Guarded Baggage": ashley_baggage_item_start+ 22,
    "Found ashley's Abandonment Issues Baggage": ashley_baggage_item_start+ 23,
    "Found ashley's Vindictive Baggage": ashley_baggage_item_start+ 24,
    "Found ashley's Gold Digger Baggage": ashley_baggage_item_start+ 25,
    "Found ashley's Unsentimental Baggage": ashley_baggage_item_start+ 26,
    "Found ashley's Expensive Tastes Baggage": ashley_baggage_item_start+ 27,
    "Found ashley's Commitment Issues Baggage": ashley_baggage_item_start+ 28,
    "Found ashley's Easily Bored Baggage": ashley_baggage_item_start+ 29,
    "Found ashley's Allergies Baggage": ashley_baggage_item_start+ 30,
    "Found ashley's Self-Effacing Baggage": ashley_baggage_item_start+ 31,
    "Found ashley's One Pump Chump Baggage": ashley_baggage_item_start+ 32,
    "Found ashley's Sex Addict Baggage": ashley_baggage_item_start+ 33,
    "Found ashley's Jealousy Baggage": ashley_baggage_item_start+ 34,
    "Found ashley's Drama Queen Baggage": ashley_baggage_item_start+ 35,
    "Found ashley's Brand Loyalist Baggage": ashley_baggage_item_start+ 36,
}

abia_baggage_item_start = ashley_baggage_item_start+ 36
abia_baggage_item = {
    "Found abia's Busy Schedule Baggage": abia_baggage_item_start+ 1,
    "Found abia's Caffeine Junkie Baggage": abia_baggage_item_start+ 2,
    "Found abia's Miss Independent Baggage": abia_baggage_item_start+ 3,
    "Found abia's Depression Baggage": abia_baggage_item_start+ 4,
    "Found abia's Emphysema Baggage": abia_baggage_item_start+ 5,
    "Found abia's Busted Vadge Baggage": abia_baggage_item_start+ 6,
    "Found abia's The Darkness Baggage": abia_baggage_item_start+ 7,
    "Found abia's Asthma Baggage": abia_baggage_item_start+ 8,
    "Found abia's Teen Angst Baggage": abia_baggage_item_start+ 9,
    "Found abia's Aquaphobic Baggage": abia_baggage_item_start+ 10,
    "Found abia's Tinnitus Baggage": abia_baggage_item_start+ 11,
    "Found abia's Kinda Crazy Baggage": abia_baggage_item_start+ 12,
    "Found abia's Annoying as Fuck Baggage": abia_baggage_item_start+ 13,
    "Found abia's Attention Whore Baggage": abia_baggage_item_start+ 14,
    "Found abia's Smelly Pussy Baggage": abia_baggage_item_start+ 15,
    "Found abia's Old Fashioned Baggage": abia_baggage_item_start+ 16,
    "Found abia's Low Self-Esteem Baggage": abia_baggage_item_start+ 17,
    "Found abia's Sheepish Baggage": abia_baggage_item_start+ 18,
    "Found abia's Intellectually Challenged Baggage": abia_baggage_item_start+ 19,
    "Found abia's Hypersensitive Baggage": abia_baggage_item_start+ 20,
    "Found abia's Forgetful Baggage": abia_baggage_item_start+ 21,
    "Found abia's Emotionally Guarded Baggage": abia_baggage_item_start+ 22,
    "Found abia's Abandonment Issues Baggage": abia_baggage_item_start+ 23,
    "Found abia's Vindictive Baggage": abia_baggage_item_start+ 24,
    "Found abia's Gold Digger Baggage": abia_baggage_item_start+ 25,
    "Found abia's Unsentimental Baggage": abia_baggage_item_start+ 26,
    "Found abia's Expensive Tastes Baggage": abia_baggage_item_start+ 27,
    "Found abia's Commitment Issues Baggage": abia_baggage_item_start+ 28,
    "Found abia's Easily Bored Baggage": abia_baggage_item_start+ 29,
    "Found abia's Allergies Baggage": abia_baggage_item_start+ 30,
    "Found abia's Self-Effacing Baggage": abia_baggage_item_start+ 31,
    "Found abia's One Pump Chump Baggage": abia_baggage_item_start+ 32,
    "Found abia's Sex Addict Baggage": abia_baggage_item_start+ 33,
    "Found abia's Jealousy Baggage": abia_baggage_item_start+ 34,
    "Found abia's Drama Queen Baggage": abia_baggage_item_start+ 35,
    "Found abia's Brand Loyalist Baggage": abia_baggage_item_start+ 36,
}

polly_baggage_item_start = abia_baggage_item_start+ 36
polly_baggage_item = {
    "Found polly's Busy Schedule Baggage": polly_baggage_item_start+ 1,
    "Found polly's Caffeine Junkie Baggage": polly_baggage_item_start+ 2,
    "Found polly's Miss Independent Baggage": polly_baggage_item_start+ 3,
    "Found polly's Depression Baggage": polly_baggage_item_start+ 4,
    "Found polly's Emphysema Baggage": polly_baggage_item_start+ 5,
    "Found polly's Busted Vadge Baggage": polly_baggage_item_start+ 6,
    "Found polly's The Darkness Baggage": polly_baggage_item_start+ 7,
    "Found polly's Asthma Baggage": polly_baggage_item_start+ 8,
    "Found polly's Teen Angst Baggage": polly_baggage_item_start+ 9,
    "Found polly's Aquaphobic Baggage": polly_baggage_item_start+ 10,
    "Found polly's Tinnitus Baggage": polly_baggage_item_start+ 11,
    "Found polly's Kinda Crazy Baggage": polly_baggage_item_start+ 12,
    "Found polly's Annoying as Fuck Baggage": polly_baggage_item_start+ 13,
    "Found polly's Attention Whore Baggage": polly_baggage_item_start+ 14,
    "Found polly's Smelly Pussy Baggage": polly_baggage_item_start+ 15,
    "Found polly's Old Fashioned Baggage": polly_baggage_item_start+ 16,
    "Found polly's Low Self-Esteem Baggage": polly_baggage_item_start+ 17,
    "Found polly's Sheepish Baggage": polly_baggage_item_start+ 18,
    "Found polly's Intellectually Challenged Baggage": polly_baggage_item_start+ 19,
    "Found polly's Hypersensitive Baggage": polly_baggage_item_start+ 20,
    "Found polly's Forgetful Baggage": polly_baggage_item_start+ 21,
    "Found polly's Emotionally Guarded Baggage": polly_baggage_item_start+ 22,
    "Found polly's Abandonment Issues Baggage": polly_baggage_item_start+ 23,
    "Found polly's Vindictive Baggage": polly_baggage_item_start+ 24,
    "Found polly's Gold Digger Baggage": polly_baggage_item_start+ 25,
    "Found polly's Unsentimental Baggage": polly_baggage_item_start+ 26,
    "Found polly's Expensive Tastes Baggage": polly_baggage_item_start+ 27,
    "Found polly's Commitment Issues Baggage": polly_baggage_item_start+ 28,
    "Found polly's Easily Bored Baggage": polly_baggage_item_start+ 29,
    "Found polly's Allergies Baggage": polly_baggage_item_start+ 30,
    "Found polly's Self-Effacing Baggage": polly_baggage_item_start+ 31,
    "Found polly's One Pump Chump Baggage": polly_baggage_item_start+ 32,
    "Found polly's Sex Addict Baggage": polly_baggage_item_start+ 33,
    "Found polly's Jealousy Baggage": polly_baggage_item_start+ 34,
    "Found polly's Drama Queen Baggage": polly_baggage_item_start+ 35,
    "Found polly's Brand Loyalist Baggage": polly_baggage_item_start+ 36,
}

outfits_item_start = polly_baggage_item_start+ 36
outfits_item = {
    "lola Poppin' Off Outfit": outfits_item_start + 1,
    "lola Stewardess Outfit": outfits_item_start + 2,
    "lola Elegance Outfit": outfits_item_start + 3,
    "lola Cream Puff Outfit": outfits_item_start + 4,
    "lola Jamaikini Outfit": outfits_item_start + 5,
    "lola Mocha Latte Outfit": outfits_item_start + 6,
    "lola Afrikini Outfit": outfits_item_start + 7,
    "lola Tennis Outfit": outfits_item_start + 8,
    "lola Basketball Outfit": outfits_item_start + 9,
    "lola Football Outfit": outfits_item_start + 10,
    "jessie Hibiscus Outfit": outfits_item_start + 11,
    "jessie Leopard Outfit": outfits_item_start + 12,
    "jessie Pillow Talk Outfit": outfits_item_start + 13,
    "jessie Tiffany Outfit": outfits_item_start + 14,
    "jessie Blue Wave Outfit": outfits_item_start + 15,
    "jessie Cloud Nine Outfit": outfits_item_start + 16,
    "jessie Naughty List Outfit": outfits_item_start + 17,
    "jessie Sweet Angel Outfit": outfits_item_start + 18,
    "jessie Sinful Devil Outfit": outfits_item_start + 19,
    "jessie Wrapped Up Outfit": outfits_item_start + 20,
    "lillian Panda Bare Outfit": outfits_item_start + 21,
    "lillian Mall Goth Outfit": outfits_item_start + 22,
    "lillian Pentagram Outfit": outfits_item_start + 23,
    "lillian Trapped Soul Outfit": outfits_item_start + 24,
    "lillian Bat Wings Outfit": outfits_item_start + 25,
    "lillian Vampiress Outfit": outfits_item_start + 26,
    "lillian Candy Corn Outfit": outfits_item_start + 27,
    "lillian Dark Queen Outfit": outfits_item_start + 28,
    "lillian Sweet Dreams Outfit": outfits_item_start + 29,
    "lillian Mega Bitch Outfit": outfits_item_start + 30,
    "zoey Citrus Acid Outfit": outfits_item_start + 31,
    "zoey Toxicity Outfit": outfits_item_start + 32,
    "zoey Sacrilege Outfit": outfits_item_start + 33,
    "zoey Sugar High Outfit": outfits_item_start + 34,
    "zoey Cheetah Outfit": outfits_item_start + 35,
    "zoey Dreamsicle Outfit": outfits_item_start + 36,
    "zoey Scarehoe Outfit": outfits_item_start + 37,
    "zoey Cyber Slave Outfit": outfits_item_start + 38,
    "zoey Gamer Girl Outfit": outfits_item_start + 39,
    "zoey Luvendass Outfit": outfits_item_start + 40,
    "sarah Kimonochi Outfit": outfits_item_start + 41,
    "sarah Ganguro Outfit": outfits_item_start + 42,
    "sarah Over All Outfit": outfits_item_start + 43,
    "sarah Sailor Outfit": outfits_item_start + 44,
    "sarah Bubble Bath Outfit": outfits_item_start + 45,
    "sarah Kitty Kat Outfit": outfits_item_start + 46,
    "sarah Cow Girl Outfit": outfits_item_start + 47,
    "sarah Panda Hoodie Outfit": outfits_item_start + 48,
    "sarah Turbo Skank Outfit": outfits_item_start + 49,
    "sarah Healing Touch Outfit": outfits_item_start + 50,
    "lailani Sea Foam Outfit": outfits_item_start + 51,
    "lailani Sarong Song Outfit": outfits_item_start + 52,
    "lailani Sunny Day Outfit": outfits_item_start + 53,
    "lailani Hula Dancer Outfit": outfits_item_start + 54,
    "lailani Infinity Outfit": outfits_item_start + 55,
    "lailani Masseuse Outfit": outfits_item_start + 56,
    "lailani Koimono Outfit": outfits_item_start + 57,
    "lailani Native Chic Outfit": outfits_item_start + 58,
    "lailani Blupee Outfit": outfits_item_start + 59,
    "lailani Closet Freak Outfit": outfits_item_start + 60,
    "candace Buckled Up Outfit": outfits_item_start + 61,
    "candace Candy Wrapper Outfit": outfits_item_start + 62,
    "candace Vanilla Cream Outfit": outfits_item_start + 63,
    "candace Shiny Treasure Outfit": outfits_item_start + 64,
    "candace Splish Splash Outfit": outfits_item_start + 65,
    "candace Strawberry Milk Outfit": outfits_item_start + 66,
    "candace Onahole Outfit": outfits_item_start + 67,
    "candace Law & Order Outfit": outfits_item_start + 68,
    "candace Health Care Outfit": outfits_item_start + 69,
    "candace Flasher Outfit": outfits_item_start + 70,
    "nora Housekeeping Outfit": outfits_item_start + 71,
    "nora Caliente Outfit": outfits_item_start + 72,
    "nora Badass Bitch Outfit": outfits_item_start + 73,
    "nora Streetwear Outfit": outfits_item_start + 74,
    "nora Aquarius Outfit": outfits_item_start + 75,
    "nora Nighty Night Outfit": outfits_item_start + 76,
    "nora Spiral Scout Outfit": outfits_item_start + 77,
    "nora Tough Gal Outfit": outfits_item_start + 78,
    "nora Gangster Outfit": outfits_item_start + 79,
    "nora Cousinly Love Outfit": outfits_item_start + 80,
    "brooke Bath Time Outfit": outfits_item_start + 81,
    "brooke Professional Outfit": outfits_item_start + 82,
    "brooke Priceless Outfit": outfits_item_start + 83,
    "brooke Kitchen Cook Outfit": outfits_item_start + 84,
    "brooke Vikini Outfit": outfits_item_start + 85,
    "brooke Cougar Outfit": outfits_item_start + 86,
    "brooke Stars & Stripes Outfit": outfits_item_start + 87,
    "brooke Captain Mommy Outfit": outfits_item_start + 88,
    "brooke Glamorous Outfit": outfits_item_start + 89,
    "brooke Love Goddess Outfit": outfits_item_start + 90,
    "ashley Stay Black Outfit": outfits_item_start + 91,
    "ashley Skater Girl Outfit": outfits_item_start + 92,
    "ashley Punk Rock Outfit": outfits_item_start + 93,
    "ashley On Brand Outfit": outfits_item_start + 94,
    "ashley Red Thread Outfit": outfits_item_start + 95,
    "ashley Black Fly Outfit": outfits_item_start + 96,
    "ashley Clamouflage Outfit": outfits_item_start + 97,
    "ashley Bumble Bea Outfit": outfits_item_start + 98,
    "ashley Astronautical Outfit": outfits_item_start + 99,
    "ashley Lazy Teacher Outfit": outfits_item_start + 100,
    "abia Traditional Outfit": outfits_item_start + 101,
    "abia Flarora Outfit": outfits_item_start + 102,
    "abia Modesty Outfit": outfits_item_start + 103,
    "abia Arabian Allure Outfit": outfits_item_start + 104,
    "abia Invisikini Outfit": outfits_item_start + 105,
    "abia Silk Road Outfit": outfits_item_start + 106,
    "abia Morning Delight Outfit": outfits_item_start + 107,
    "abia Airport Security Outfit": outfits_item_start + 108,
    "abia Assassin Outfit": outfits_item_start + 109,
    "abia Birthday Suit Outfit": outfits_item_start + 110,
    "polly Fifties Outfit": outfits_item_start + 111,
    "polly Forties Outfit": outfits_item_start + 112,
    "polly Seventies Outfit": outfits_item_start + 113,
    "polly Eighties Outfit": outfits_item_start + 114,
    "polly Pin-up Girl Outfit": outfits_item_start + 115,
    "polly Wife Material Outfit": outfits_item_start + 116,
    "polly Tuxedo Outfit": outfits_item_start + 117,
    "polly Sex Symbol Outfit": outfits_item_start + 118,
    "polly Roller Skate Outfit": outfits_item_start + 119,
    "polly Wedding Night Outfit": outfits_item_start + 120,
}

filler_item_start = outfits_item_start + 120
filler_item = {
    "Ocean Breeze Candle" : filler_item_start + 1,
    "Pine Forest Candle" : filler_item_start + 2,
    "Pumpkin Spice Candle" : filler_item_start + 3,
    "Cinnamon Cider Candle" : filler_item_start + 4,
    "Tropical Sunset Candle" : filler_item_start + 5,
    "Midnight Moonlight Candle" : filler_item_start + 6,
    "Sweet Honeycomb Candle" : filler_item_start + 7,
    "Spring Rain Candle" : filler_item_start + 8,
    "Cotton Pillows Candle" : filler_item_start + 9,
    "Exfoliating Scrub" : filler_item_start + 10,
    "Eyelash Kit" : filler_item_start + 11,
    "Powder Brush" : filler_item_start + 12,
    "Makeup Palette" : filler_item_start + 13,
    "Lipstick" : filler_item_start + 14,
    "Moisturizer" : filler_item_start + 15,
    "Hair Brush" : filler_item_start + 16,
    "Blow Dryer" : filler_item_start + 17,
    "Blue Orchid Flowers" : filler_item_start + 18,
    "Green Clover Flowers" : filler_item_start + 19,
    "Orange Daisy Flowers" : filler_item_start + 20,
    "Red Rose Flowers" : filler_item_start + 21,
    "Pink Cosmos Flowers" : filler_item_start + 22,
    "Violet Pansy Flowers" : filler_item_start + 23,
    "Yellow Narcissus Flowers" : filler_item_start + 24,
    "Turquoise Tulip Flowers" : filler_item_start + 25,
    "White Lily Flowers" : filler_item_start + 26,
    "Sanitary Pad" : filler_item_start + 27,
    "Tampon" : filler_item_start + 28,
    "Feminine Wash" : filler_item_start + 29,
    "Feminine Cream" : filler_item_start + 30,
    "Feminine Wipes" : filler_item_start + 31,
    "Douche" : filler_item_start + 32,
    "Sapphire Ring" : filler_item_start + 33,
    "Emerald Bracelet" : filler_item_start + 34,
    "Citrine Bracelet" : filler_item_start + 35,
    "Ruby Ring" : filler_item_start + 36,
    "Spinel Necklace" : filler_item_start + 37,
    "Amethyst Necklace" : filler_item_start + 38,
    "Topaz Earrings" : filler_item_start + 39,
    "Aquamarine Earrings" : filler_item_start + 40,
    "Diamond Tiara" : filler_item_start + 41,
    "Peacock Plush" : filler_item_start + 42,
    "Frog Plush" : filler_item_start + 43,
    "Goldfish Plush" : filler_item_start + 44,
    "Ladybug Plush" : filler_item_start + 45,
    "Pig Plush" : filler_item_start + 46,
    "Octopus Plush" : filler_item_start + 47,
    "Chick Plush" : filler_item_start + 48,
    "Elephant Plush" : filler_item_start + 49,
    "Bunny Plush" : filler_item_start + 50,
    "Fox Plush" : filler_item_start + 51,
    "Cow Plush" : filler_item_start + 52,
    "Magic Wand" : filler_item_start + 53,
    "Egg Vibrator" : filler_item_start + 54,
    "Butt Plug" : filler_item_start + 55,
    "Anal Beads" : filler_item_start + 56,
    "Lube" : filler_item_start + 57,
    "Dirty Dice" : filler_item_start + 58,
    "Kamasutra" : filler_item_start + 59,
    "Breast Pump" : filler_item_start + 60,
    "Beach Ball" : filler_item_start + 61,
    "Inner Tube" : filler_item_start + 62,
    "Tiki Head Charm" : filler_item_start + 63,
    "Surfboard" : filler_item_start + 64,
    "Snorkel Mask" : filler_item_start + 65,
    "Flippers" : filler_item_start + 66,
    "Suntan Lotion" : filler_item_start + 67,
    "Beach Towel" : filler_item_start + 68,
    "Tropical Lei" : filler_item_start + 69,
    "Ceramic Fish" : filler_item_start + 70,
    "Pinwheel" : filler_item_start + 71,
    "Hemp Bracelet" : filler_item_start + 72,
    "Glass Dolphin" : filler_item_start + 73,
    "Postcard" : filler_item_start + 74,
    "Snow Globe" : filler_item_start + 75,
}

arch_item_start = filler_item_start + 75
arch_item = {
    "nothing": arch_item_start + 1,
    "Fruit Seeds": arch_item_start + 2,
    "Boss Unlocked": arch_item_start + 3,
    "Goal Achieved": arch_item_start + 4,
}

item_list = {
    **fairy_wings_item,
    **token_item,
    **girl_unlock_item,
    **pair_unlock_item,
    **gift_unique_item,
    **gift_shoe_item,
    **lola_baggage_item,
    **jessie_baggage_item,
    **lillian_baggage_item,
    **zoey_baggage_item,
    **sarah_baggage_item,
    **lailani_baggage_item,
    **candace_baggage_item,
    **nora_baggage_item,
    **brooke_baggage_item,
    **ashley_baggage_item,
    **abia_baggage_item,
    **polly_baggage_item,
    **outfits_item,
    **filler_item,
    **arch_item,
}

item_datapackage = {
"fairy_wings_item_start":fairy_wings_item_start,
"token_item_start":token_item_start,
"girl_unlock_item_start":girl_unlock_item_start,
"pair_unlock_item_start":pair_unlock_item_start,
"gift_unique_item_start":gift_unique_item_start,
"gift_shoe_item_start":gift_shoe_item_start,
"lola_baggage_item_start":lola_baggage_item_start,
"jessie_baggage_item_start":jessie_baggage_item_start,
"lillian_baggage_item_start":lillian_baggage_item_start,
"zoey_baggage_item_start":zoey_baggage_item_start,
"sarah_baggage_item_start":sarah_baggage_item_start,
"lailani_baggage_item_start":lailani_baggage_item_start,
"candace_baggage_item_start":candace_baggage_item_start,
"nora_baggage_item_start":nora_baggage_item_start,
"brooke_baggage_item_start":brooke_baggage_item_start,
"ashley_baggage_item_start":ashley_baggage_item_start,
"abia_baggage_item_start":abia_baggage_item_start,
"polly_baggage_item_start":polly_baggage_item_start,
"outfits_item_start":outfits_item_start,
"filler_item_start":filler_item_start,
"arch_item_start":arch_item_start,
}

mixed_filler_items = {
    **filler_item,
    "nothing": arch_item_start + 1,
    "Fruit Seeds": arch_item_start + 2,

}
