"""
Cache I/O for world data packages and world settings.

Pure I/O — no imports from the worlds package, no circular dependencies.
Call sites in worlds/__init__.py pass world_sources explicitly.
"""
import gzip
import hashlib
import json
import logging
import os
import tempfile
import time
from typing import TYPE_CHECKING, Dict, List

from Utils import local_path, version_tuple

if TYPE_CHECKING:
    from worlds import WorldSource

_DATAPACKAGE_CACHE_PATH = local_path("data", "world_datapackage_cache.json.gz")
_WORLD_SETTINGS_CACHE_PATH = local_path("data", "world_settings_cache.json.gz")


def _normalize_cache_path(path: str) -> str:
    return path.replace("\\", "/")


def _calculate_datapackage_cache_key(world_sources: "List[WorldSource]") -> str:
    entries: list[tuple] = [
        ("core_version", int(version_tuple.major), int(version_tuple.minor), int(version_tuple.build)),
    ]

    for world_source in world_sources:
        source_id = _normalize_cache_path(world_source.path if world_source.relative else world_source.resolved_path)

        if world_source.is_zip:
            try:
                stat_result = os.stat(world_source.resolved_path)
            except OSError:
                entries.append(("zip_missing", source_id))
            else:
                entries.append(("zip", source_id, int(stat_result.st_size), int(stat_result.st_mtime_ns)))
            continue

        try:
            for dirpath, dirnames, filenames in os.walk(world_source.resolved_path):
                # Exclude generated bytecode dirs — importing worlds creates/updates .pyc files
                # inside __pycache__, which would change the key on every run after first load.
                dirnames[:] = [d for d in dirnames if d != "__pycache__"]

                relative_dir = os.path.relpath(dirpath, world_source.resolved_path)
                relative_dir = "" if relative_dir == "." else _normalize_cache_path(relative_dir)

                for filename in sorted(filenames):
                    full_path = os.path.join(dirpath, filename)
                    relative_path = filename if not relative_dir else f"{relative_dir}/{filename}"
                    file_id = f"{source_id}/{_normalize_cache_path(relative_path)}"

                    try:
                        stat_result = os.stat(full_path)
                    except OSError:
                        entries.append(("file_missing", file_id))
                    else:
                        entries.append(("file", file_id, int(stat_result.st_size), int(stat_result.st_mtime_ns)))
        except OSError:
            entries.append(("dir_missing", source_id))

    digest = hashlib.sha256()
    for entry in sorted(entries):
        digest.update(repr(entry).encode("utf-8"))
        digest.update(b"\n")
    return digest.hexdigest()


def _load_datapackage_from_cache(expected_cache_key: str) -> Dict[str, dict] | None:
    if not os.path.isfile(_DATAPACKAGE_CACHE_PATH):
        return None

    try:
        with gzip.open(_DATAPACKAGE_CACHE_PATH, mode="rt", encoding="utf-8") as cache_file:
            payload = json.load(cache_file)
    except Exception as exc:
        logging.warning(f"Failed to read datapackage cache from {_DATAPACKAGE_CACHE_PATH}: {exc}")
        return None

    cache_key = payload.get("cache_key")
    games = payload.get("games")
    if not isinstance(cache_key, str) or not isinstance(games, dict):
        logging.info("Datapackage cache has malformed structure, rebuilding.")
        return None

    required_game_keys = ("item_name_to_id", "location_name_to_id", "item_name_groups", "location_name_groups")
    for game_name, game_data in games.items():
        if not isinstance(game_name, str) or not isinstance(game_data, dict):
            logging.info("Datapackage cache has malformed game entry, rebuilding.")
            return None
        for required_key in required_game_keys:
            if required_key not in game_data or not isinstance(game_data[required_key], dict):
                logging.info("Datapackage cache has malformed game entry, rebuilding.")
                return None

    if cache_key != expected_cache_key:
        logging.info("Datapackage cache is stale (world files changed), rebuilding.")
        return None

    logging.debug(f"Loaded datapackage cache from {_DATAPACKAGE_CACHE_PATH}.")
    return games


def _write_datapackage_cache(cache_key: str, games: Dict[str, dict]) -> None:
    cache_dir = os.path.dirname(_DATAPACKAGE_CACHE_PATH)
    if cache_dir:
        os.makedirs(cache_dir, exist_ok=True)

    payload = {
        "cache_key": cache_key,
        "core_version": [int(version_tuple.major), int(version_tuple.minor), int(version_tuple.build)],
        "games": games,
    }

    write_start = time.perf_counter()
    temp_file_path = ""
    try:
        file_descriptor, temp_file_path = tempfile.mkstemp(
            prefix="world_datapackage_cache.",
            suffix=".tmp",
            dir=cache_dir or None,
        )
        with os.fdopen(file_descriptor, mode="wb") as temp_file:
            with gzip.GzipFile(fileobj=temp_file, mode="wb") as gzip_file:
                gzip_file.write(json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8"))
            temp_file.flush()
            if hasattr(os, "fsync"):
                os.fsync(temp_file.fileno())

        os.replace(temp_file_path, _DATAPACKAGE_CACHE_PATH)
        logging.info(f"Wrote datapackage cache to {_DATAPACKAGE_CACHE_PATH} in {time.perf_counter() - write_start:.2f}s.")
    except Exception as exc:
        logging.warning(f"Failed to write datapackage cache to {_DATAPACKAGE_CACHE_PATH}: {exc}")
    finally:
        if temp_file_path and os.path.exists(temp_file_path):
            try:
                os.unlink(temp_file_path)
            except OSError:
                pass


def _load_world_settings_cache(expected_cache_key: str) -> Dict[str, str] | None:
    if not os.path.isfile(_WORLD_SETTINGS_CACHE_PATH):
        return None

    try:
        with gzip.open(_WORLD_SETTINGS_CACHE_PATH, mode="rt", encoding="utf-8") as cache_file:
            payload = json.load(cache_file)
    except Exception as exc:
        logging.warning(f"Failed to read world settings cache from {_WORLD_SETTINGS_CACHE_PATH}: {exc}")
        return None

    cache_key = payload.get("cache_key")
    settings_cache = payload.get("settings")
    if not isinstance(cache_key, str) or not isinstance(settings_cache, dict):
        logging.info("World settings cache has malformed structure, rebuilding.")
        return None

    for settings_key, world_ref in settings_cache.items():
        if not isinstance(settings_key, str) or not isinstance(world_ref, str):
            logging.info("World settings cache has malformed entry, rebuilding.")
            return None

    if cache_key != expected_cache_key:
        logging.info("World settings cache is stale (world files changed), rebuilding.")
        return None

    logging.debug(f"Loaded world settings cache from {_WORLD_SETTINGS_CACHE_PATH}.")
    return settings_cache


def _write_world_settings_cache(cache_key: str, settings_cache: Dict[str, str]) -> None:
    cache_dir = os.path.dirname(_WORLD_SETTINGS_CACHE_PATH)
    if cache_dir:
        os.makedirs(cache_dir, exist_ok=True)

    payload = {
        "cache_key": cache_key,
        "settings": settings_cache,
    }

    write_start = time.perf_counter()
    temp_file_path = ""
    try:
        file_descriptor, temp_file_path = tempfile.mkstemp(
            prefix="world_settings_cache.",
            suffix=".tmp",
            dir=cache_dir or None,
        )
        with os.fdopen(file_descriptor, mode="wb") as temp_file:
            with gzip.GzipFile(fileobj=temp_file, mode="wb") as gzip_file:
                gzip_file.write(json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8"))
            temp_file.flush()
            if hasattr(os, "fsync"):
                os.fsync(temp_file.fileno())

        os.replace(temp_file_path, _WORLD_SETTINGS_CACHE_PATH)
        logging.info(
            f"Wrote world settings cache to {_WORLD_SETTINGS_CACHE_PATH} in "
            f"{time.perf_counter() - write_start:.2f}s."
        )
    except Exception as exc:
        logging.warning(f"Failed to write world settings cache to {_WORLD_SETTINGS_CACHE_PATH}: {exc}")
    finally:
        if temp_file_path and os.path.exists(temp_file_path):
            try:
                os.unlink(temp_file_path)
            except OSError:
                pass


def is_datapackage_cache_current(cache_key: str) -> bool:
    return _load_datapackage_from_cache(cache_key) is not None


def is_world_settings_cache_current(cache_key: str) -> bool:
    return _load_world_settings_cache(cache_key) is not None


def _build_world_settings_cache_data() -> Dict[str, str]:
    from worlds.AutoWorld import AutoWorldRegister
    settings_cache: Dict[str, str] = {}
    for world in AutoWorldRegister.world_types.values():
        annotation = world.__annotations__.get("settings", None)
        if annotation is None or annotation == "ClassVar[Optional['Group']]":
            continue
        settings_cache[world.settings_key] = f"{world.__module__}.{world.__name__}"
    return settings_cache


def calculate_world_cache_key() -> str:
    from worlds import world_sources
    return _calculate_datapackage_cache_key(world_sources)


def load_world_settings_cache(cache_key: str | None = None) -> Dict[str, str] | None:
    from worlds import world_sources
    cache_key = cache_key or _calculate_datapackage_cache_key(world_sources)
    return _load_world_settings_cache(cache_key)


def rebuild_world_settings_cache(cache_key: str | None = None) -> None:
    import worlds
    if not worlds._worlds_loaded:
        return
    cache_key = cache_key or _calculate_datapackage_cache_key(worlds.world_sources)
    _write_world_settings_cache(cache_key, _build_world_settings_cache_data())


def is_launcher_cache_current(cache_key: str) -> bool:
    try:
        from worlds import LauncherComponents
    except Exception:
        return False
    return LauncherComponents.is_launcher_cache_current(cache_key)


def are_world_caches_current(cache_key: str | None = None) -> bool:
    from worlds import world_sources
    cache_key = cache_key or _calculate_datapackage_cache_key(world_sources)
    return (
        is_datapackage_cache_current(cache_key)
        and is_launcher_cache_current(cache_key)
        and is_world_settings_cache_current(cache_key)
    )


def rebuild_world_caches() -> None:
    """Rebuild cache files from current in-memory world state.

    Unlike ensure_worlds_loaded(), this bypasses the _worlds_loaded guard so it can be called
    after hot-loading a new world (e.g. after install_apworld) to keep cache files current
    for subsequent processes without requiring a full reload.
    Does nothing if worlds have not been loaded yet.
    """
    import worlds
    if not worlds._worlds_loaded:
        return
    cache_key = _calculate_datapackage_cache_key(worlds.world_sources)
    worlds._build_network_data_packages()
    _write_datapackage_cache(cache_key, worlds.network_data_package["games"])
    _write_world_settings_cache(cache_key, _build_world_settings_cache_data())
    try:
        from worlds import LauncherComponents
        LauncherComponents.write_launcher_cache(cache_key)
    except Exception as exc:
        logging.warning(f"Failed to write launcher cache during rebuild: {exc}")
