RENAMED_DICT = {
    "Mage's Staff": "Mages Staff",
    "Mage's Staff Slot": "Mages Staff Slot",
    "Kingdom Key D Slot": "FAKE Slot",
    "Alpha Weapon Slot": "Detection Saber Slot",
    "Omega Weapon Slot": "Edge of Ultima Slot",
    "Olympus Coliseum Hades Paradox Event": "Olympus Coliseum Hade's Paradox Event",
    "(LoD) Shan Yu": "(LoD) Hidden Dragon",
    "(AG) Elemental Lords": "(AG) Lamp Charm",
    "(TR) Future Pete": "(TR) Monochrome",
    "(OC) Hydra": "(OC) Hero's Crest",
    "(OC2) Hades": "(OC2) Guardian Soul",
    "(BC) Dark Thorn": "(BC) Dark Thorn Cure Element",
    "(SP) Hostile Program": "(SP) Photon Debugger",
    "(SP2) MCP": "(SP2) MCP Bonus: Sora Slot 1",
    "(HT) Oogie Boogie": "(HT) Oogie Boogie Magnet Element",
    "(HT2) Experiment": "(HT2) Decisive Pumpkin",
    "(PR) Barbossa": "(PR) Follow the Wind",
    "(HB2) Secret Ansem Report 1 (1000 Heartless)": "(HB2) 1000 Heartless Secret Ansem Report 1",
    "(Post HB2: Crystal Fissure) Sephiroth Bonus: Sora Slot 1":  "Sephiroth Bonus: Sora Slot 1",
    "(Post HB2: Crystal Fissure) Sephiroth":  "Sephiroth Fenrir",
    "(PL) Scar": "(PL) Scar Fire Element",
    "(PL2) Groundshaker": "(PL2) Groundshaker Bonus: Sora Slot 1",
    "(TT) Secret Ansem Report 2 (Station Plaza)": "(TT) Station Plaza Secret Ansem Report 2",
    "(TWTNW2) Secret Ansem Report 8 (Roxas)": "(TWTNW2) Roxas Secret Ansem Report 8",
    "(TWTNW2) Secret Ansem Report 3 (Xigbar)": "(TWTNW2) Xigbar Secret Ansem Report 3",
    "(TWTNW2) Secret Ansem Report 9 (Luxord)": "(TWTNW2) Luxord Secret Ansem Report 9",
    "(TWTNW2) Secret Ansem Report 12 (Saix)": "(TWTNW2) Saix Secret Ansem Report 12",
}